/**
 * Base Gap Definitions — entries that the original definition database
 * referenced but never defined (forward references). Added so the wiki
 * database has NO dangling relation targets. Descriptions are verbatim
 * fragments or minimal faithful derivations from the cited corpus sections.
 */

import type { Definition } from '../definitions';

export const BASE_GAP_DEFINITIONS: Definition[] = [
  // events (doc 03, doc 15)
  { id: "event.breakthrough", kind: "event", name: "Breakthrough", tags: ["realm_transition","tribulation_gated"], description: "The transition between realm stations. Breakthrough timing varies by ±30% based on talent, resources, and environment; the typical values are canonical, the range is procedural.", source: "doc 03 §1, doc 03 §6", relations: [{ type: "PREREQUISITE_FOR", target: "realm.foundation_establishment" }], simulationHooks: ["cultivation", "deviation", "aging"], version: "0.1.0" },
  { id: "event.tribulation", kind: "event", name: "Tribulation", tags: ["realm_transition","heavenly_ordeal"], description: "The heavenly ordeal a cultivator must pass to advance across major realm boundaries; yao face additional tribulations at each major realm boundary.", source: "doc 03 §6, doc 25 §3, doc 15", relations: [{ type: "PREREQUISITE_FOR", target: "realm.core_formation" }, { type: "PREREQUISITE_FOR", target: "realm.nascent_soul" }, { type: "PREREQUISITE_FOR", target: "realm.spirit_severance" }, { type: "PREREQUISITE_FOR", target: "realm.tribulation_crossing" }], simulationHooks: ["cultivation", "combat", "weather", "ritual"], version: "0.1.0" },

  // realm (doc 48)
  { id: "realm.xianren", kind: "realm", name: "Xianren", tags: ["station_11","immortal","beyond_mahayana","higher_worlds"], description: "The immortal realm beyond Mahayana — the higher immortal worlds the genre demands and the prior corpus deferred; the substrate there is ran, from which qi is derived.", source: "doc 48, doc 00 §6", relations: [{ type: "REQUIRES", target: "realm.mahayana" }, { type: "TRANSFORMS", target: "essence.ran" }], simulationHooks: ["cultivation", "aging", "physics", "history"], version: "0.1.0" },

  // skills (doc 03 Station 5)
  { id: "skill.perceive_anchors", kind: "skill", name: "Perceive Spirit Anchors", tags: ["core_formation","perception","spirit_anchor"], description: "A self-contained internal authority forms; qi does not need external replenishment. You can perceive spirit anchors.", source: "doc 03 Station 5", relations: [{ type: "REQUIRES", target: "realm.core_formation" }], simulationHooks: ["perception", "cultivation"], version: "0.1.0" },

  // practices — deviation counterplays (doc 05 §3, doc 24 §1.2)
  { id: "practice.stabilizing_herbs", kind: "cultivation_practice", name: "Stabilizing Herbs", tags: ["corrective","somatic","herbal"], description: "Rest, specific stabilizing herbs, and the slow re-establishment of the correct flow — the counterplay to Cross-Current deviation, which feels boring after the surge's intensity.", source: "doc 05 §3.1", relations: [{ type: "COUNTERS", target: "deviation.cross_current" }], simulationHooks: ["cultivation", "deviation"], version: "0.1.0" },
  { id: "practice.diverse_routing", kind: "cultivation_practice", name: "Diverse Routing", tags: ["corrective","somatic","habit_breaking"], description: "The counterplay to Route Fixation: deliberately practicing diverse qi routes so no single route becomes habitual and the others atrophy.", source: "doc 05 §3.1", relations: [{ type: "COUNTERS", target: "deviation.route_fixation" }], simulationHooks: ["cultivation", "deviation"], version: "0.1.0" },
  { id: "practice.phase_matched_venting", kind: "cultivation_practice", name: "Phase-Matched Venting", tags: ["corrective","somatic","qi_signature"], description: "The counterplay to Borrowed Signature Adhesion: venting the absorbed qi through the matching phase to shed the foreign qi-signature.", source: "doc 24 §1.2", relations: [{ type: "COUNTERS", target: "deviation.borrowed_signature" }], simulationHooks: ["cultivation", "deviation", "combat"], version: "0.1.0" },
  { id: "practice.confront_fixation", kind: "cultivation_practice", name: "Confront Fixation", tags: ["corrective","psychospiritual","heart_mind"], description: "Time, distance, the deliberate cultivation of other attachments, the intervention of a teacher or friend who can perceive the fixation — the counterplay to Obsession.", source: "doc 05 §3.2", relations: [{ type: "COUNTERS", target: "deviation.obsession" }], simulationHooks: ["cultivation", "deviation", "social"], version: "0.1.0" },
  { id: "practice.interruption", kind: "cultivation_practice", name: "Interruption", tags: ["corrective","psychospiritual","behavioral"], description: "Deliberate interruption, the substitution of a different behavior, and — if deep — the confrontation of the compulsion's root: the counterplay to Compulsion.", source: "doc 05 §3.2", relations: [{ type: "COUNTERS", target: "deviation.compulsion" }], simulationHooks: ["cultivation", "deviation"], version: "0.1.0" },
  { id: "practice.integration", kind: "cultivation_practice", name: "Integration", tags: ["corrective","psychospiritual","multiple_selves"], description: "Stabilization practices (grounding in the body, in the breath, in the present), the intervention of a teacher or healer — the counterplay to Personality Fragmentation.", source: "doc 05 §3.2", relations: [{ type: "COUNTERS", target: "deviation.fragmentation" }], simulationHooks: ["cultivation", "deviation", "social"], version: "0.1.0" },
  { id: "practice.encounter_contradicting_evidence", kind: "cultivation_practice", name: "Encounter Contradicting Evidence", tags: ["corrective","psychospiritual","belief"], description: "The counterplay to Delusional Conviction: encountering evidence that contradicts the elevated partial truth, breaking the serene certainty.", source: "doc 24 §1.2", relations: [{ type: "COUNTERS", target: "deviation.delusional_conviction" }], simulationHooks: ["cultivation", "deviation", "perception"], version: "0.1.0" },

  // technique (doc 32 §3.3)
  { id: "technique.water_shield", kind: "technique", name: "Water Shield", tags: ["water_phase","defensive","counter_fire"], description: "Water-phase defensive technique that counters fire-phase attacks such as Burning Palm.", source: "doc 32 §3.3", relations: [{ type: "COUNTERS", target: "technique.burning_palm" }, { type: "REQUIRES", target: "realm.qi_condensation" }], simulationHooks: ["combat", "physics", "cultivation"], version: "0.1.0" },
];
