/**
 * Economy / history definitions extracted from the corpus-extension docs:
 * doc 18 (Economy System), doc 47 (Cosmic Resources and Economy),
 * doc 37 (Cosmic History), doc 25 (Folk Religion Metaphysics — named spirits only).
 *
 * Only things NAMED in the docs: the four currencies, the three markets, the
 * named cosmic resources and currencies (qi-authority, veneration, law-fragments,
 * the Thinning, the time-debt, the Law Reaches), the named historical events
 * (the cosmos's 48,000-year age, the six epochs, the Fourth-Stratum Attempt,
 * the Sundering, the Courts' founding, the three fallen civilizations, the
 * Sky-Devouring Beast's sealing, the Zhou Wugui incursion), and the named
 * folk-religion beings (Wang Tugeng, Lord Cangli, Magistrate Cang, Lady Bai,
 * the Black Creek Serpent, Old Cypress, the Underworld). Descriptions are
 * faithful condensed paraphrases with the docs' exact numbers; no numbers are
 * invented. Hanzi appear exactly as in the corpus. Where an entity's hanzi is
 * not given in the corpus (e.g. Zhou Wugui), it is omitted.
 */
import type { Definition } from '../definitions';

export const ECONOMY_HISTORY_DEFINITIONS: Definition[] = [
  // ============================ DOC 18 — THE MORTAL ECONOMY ============================

  {
    id: "economy.currency_copper_cash",
    kind: "custom",
    name: "Copper Cash",
    nameHanzi: "文",
    tags: ["currency","mortal","daily_transaction"],
    description: "The daily currency of the mortal world: used for salt, tools, cloth, daily labor, and small transactions. 1 string of 1000 cash = 1 tael of silver (nominal; the ratio fluctuates). Most mortal households rarely see silver; they live in cash.",
    source: "doc 18 §1.1",
    relations: [
      { type: "EXCHANGES_WITH", target: "economy.currency_silver", note: "1 string of 1000 cash = 1 tael of silver (nominal)" },
    ],
    simulationHooks: ["economy","trade","social"],
    version: "0.1.0",
  },
  {
    id: "economy.currency_silver",
    kind: "custom",
    name: "Silver",
    nameHanzi: "銀",
    tags: ["currency","mortal","tax","large_transaction"],
    description: "The tax and large-transaction currency of the mortal world, denominated in taels (兩): used for land purchases, bride prices, tax payments, and sect tribute. The silver-grain price ratio is the peasant's economic weather — silver scarcity in a bad harvest year (when grain prices fall) is the classic crisis.",
    source: "doc 18 §1.2",
    relations: [
      { type: "EXCHANGES_WITH", target: "economy.currency_copper_cash" },
      { type: "EXCHANGES_WITH", target: "economy.currency_spirit_stones", note: "rate not fixed: 100 taels in a spirit-vein-rich region, 500 in a barren one" },
    ],
    simulationHooks: ["economy","trade","politics"],
    version: "0.1.0",
  },
  {
    id: "economy.currency_spirit_stones",
    kind: "custom",
    name: "Spirit Stones",
    nameHanzi: "靈石",
    tags: ["currency","cultivation","crystallized_qi"],
    description: "The cultivation world's currency: a crystallized qi concentrate, produced by spirit veins (rare) or by Core Formation+ cultivators (expensive); used for cultivation resources, pills, talismans, formations, sect dues, and mercenary contracts. The silver exchange rate is not fixed — a spirit stone might be worth 100 taels in a spirit-vein-rich region and 500 taels in a barren one. In the cosmic economy it remains the subsidiary currency, at 10-50 taels of silver per stone (doc 24 §3.1).",
    source: "doc 18 §1.3, doc 47 §2.2, doc 24 §3.1",
    relations: [
      { type: "EXCHANGES_WITH", target: "economy.currency_silver" },
      { type: "USED_IN", target: "market.cultivation_market" },
      { type: "EXCHANGES_WITH", target: "resource.veneration", note: "in the Precelestial: 1 spirit stone ≈ a Qi Condensation cultivator's daily veneration-pulse, 100 ≈ Foundation Establishment, 10,000 ≈ Core Formation" },
    ],
    simulationHooks: ["economy","trade","cultivation","politics"],
    version: "0.1.0",
  },
  {
    id: "economy.currency_grain",
    kind: "custom",
    name: "Grain",
    nameHanzi: "穀",
    tags: ["currency","mortal","reserve","store_of_value"],
    description: "The reserve currency — not transactional, but the ultimate store of value: a household's grain reserves are its real wealth. Grain is hoarded, lent (at 50-100% annual interest in bad years), and used to pay labor; when the grain runs out, the household starves or borrows.",
    source: "doc 18 §1.4",
    relations: [
      { type: "INSTRUMENT_OF", target: "economy.debt_cycle", note: "grain is borrowed at 50-100% annual interest in bad years" },
    ],
    simulationHooks: ["economy","trade","disease","social"],
    version: "0.1.0",
  },
  {
    id: "market.mortal_market",
    kind: "institution",
    name: "The Mortal Market",
    nameHanzi: "鎮",
    tags: ["market","mortal","periodic","news_network"],
    description: "The market town's periodic market, held on the 1st, 5th, 10th, 15th, 20th, and 25th of each lunar month (per doc 04 §6.2). Villagers sell grain, cloth, and pigs; buy salt, iron, paper, and incense. The market is also the news network.",
    source: "doc 18 §2.1, doc 04 §6.2",
    relations: [
      { type: "LOCATED_IN", target: "place.qinghe_market_town" },
      { type: "PART_OF", target: "region.cangli_riverlands" },
    ],
    simulationHooks: ["economy","trade","social","politics"],
    version: "0.1.0",
  },
  {
    id: "market.cultivation_market",
    kind: "institution",
    name: "The Cultivation Market",
    nameHanzi: "坊市",
    tags: ["market","cultivation","cross_economy"],
    description: "A market for cultivators, held at specific locations (usually near sects or at crossroads): sells spirit herbs, pills, talismans, formation materials, beast parts, and technique manuals; buys the same, plus spirit stones. The point where the two economies meet — a mortal herb gatherer can sell a spirit herb for spirit stones, if they find a buyer who doesn't cheat them.",
    source: "doc 18 §2.2",
    relations: [
      { type: "INTERFACES_WITH", target: "market.mortal_market", note: "the cultivation market is where the two economies meet" },
    ],
    simulationHooks: ["economy","trade","cultivation","social"],
    version: "0.1.0",
  },
  {
    id: "market.auction",
    kind: "institution",
    name: "The Auction",
    nameHanzi: "拍賣",
    tags: ["market","high_value","social_event"],
    description: "The auction for high-value items (breakthrough pills, rare treasures, inheritance manuals), held by sects or the Immortal Alliance; bidders pay in spirit stones. The auction is a social event — who bids what reveals alliances and rivalries.",
    source: "doc 18 §2.3",
    relations: [
      { type: "HOSTED_BY", target: "institution.immortal_alliance" },
    ],
    simulationHooks: ["economy","social","politics","trade"],
    version: "0.1.0",
  },
  {
    id: "economy.herb_gathering",
    kind: "custom",
    name: "Herb Gathering",
    nameHanzi: "採藥",
    tags: ["production","herbs","dangerous","low_realm"],
    description: "Mortals or low-realm cultivators gather spirit herbs from the wild — dangerous (spirit beasts, contamination, terrain); the gatherer's skill is in finding and identifying herbs, not in combat. Herbs take decades to mature (a 100-year ginseng, a 500-year lingzhi); a spirit herb gathered by a mortal is the economy's link from the wild to the cultivation market.",
    source: "doc 18 §3.2, doc 18 §3.3",
    relations: [
      { type: "FEEDS", target: "market.cultivation_market" },
    ],
    simulationHooks: ["ecology","economy","cultivation","trade"],
    version: "0.1.0",
  },
  {
    id: "economy.beast_hunting",
    kind: "custom",
    name: "Beast Hunting",
    nameHanzi: "獵妖",
    tags: ["production","spirit_beasts","cores","qi_condensation_plus"],
    description: "Qi Condensation+ cultivators hunt spirit beasts for their cores (內丹, the crystallized qi of a peak beast, worth 10-100 spirit stones), hides, bones, and organs. The core is the most valuable part — refinable into pills or usable directly for cultivation. Beasts take decades to cultivate, so the hunting economy's tempo is measured in years.",
    source: "doc 18 §3.2, doc 47 §1.3",
    relations: [
      { type: "REQUIRES", target: "realm.qi_condensation" },
    ],
    simulationHooks: ["ecology","economy","combat","trade"],
    version: "0.1.0",
  },
  {
    id: "economy.debt_cycle",
    kind: "custom",
    name: "The Debt Cycle",
    tags: ["mortal","poverty","grain_loan","tenant"],
    description: "The engine of rural poverty: a bad harvest (flood, drought, pest) creates a grain deficit; grain is borrowed at 50-100% annual interest; a second bad year forces asset sales (pig, dryland, surface rights); the spiral ends in selling children (as servants, brides, apprentices), losing the land, becoming a tenant on what was once one's own farm, or fleeing. The player who begins as a Wang tenant household member experiences this directly.",
    source: "doc 18 §5.1",
    relations: [
      { type: "AFFECTS", target: "location.wang_family_bend" },
    ],
    simulationHooks: ["economy","social","aging","migration","disease"],
    version: "0.1.0",
  },
  {
    id: "economy.cultivation_escape",
    kind: "custom",
    name: "The Cultivation Escape",
    tags: ["mortal","economic_fact","escape","genre_central_fact"],
    description: "The genre's central economic fact: a Qi Condensation cultivator can earn 10-50 spirit stones per month (hunting, gathering, mercenary work); one spirit stone ≈ 100-500 taels of silver and one tael ≈ 1000 cash — one month of cultivation work equals 10-50 years of mortal labor. The escape is not free: it costs time (training), risk (deviation, death), and social cost (leaving the mortal world behind).",
    source: "doc 18 §5.2, doc 24 §3.1",
    relations: [
      { type: "REQUIRES", target: "realm.qi_condensation" },
    ],
    simulationHooks: ["economy","cultivation","social"],
    version: "0.1.0",
  },
  {
    id: "economy.sect_economy",
    kind: "custom",
    name: "The Sect Economy",
    tags: ["sect","revenue","expenses","tribute"],
    description: "Sect revenue: spirit-vein tithes (10-30% of a cultivator's harvest for access), disciple labor as dues, pill/talisman/formation sales, mercenary contracts (Core Formation+ cultivators rented for high-danger jobs), and land tax where sects control mortal territories (rare, usually only great sects). Expenses: disciple support, sect maintenance, treasure acquisition, and tribute (to the Immortal Alliance for members, or to a higher-ranking sect for vassals). A new sect is poor; a great sect is wealthier than any mortal kingdom — but a single failed tribulation of the sect master can collapse the sect's political power and trigger a wealth-grab.",
    source: "doc 18 §6",
    relations: [
      { type: "PART_OF", target: "institution.immortal_alliance", note: "member sects pay tribute to the alliance" },
    ],
    simulationHooks: ["economy","politics","social","cultivation"],
    version: "0.1.0",
  },

  // ============================ DOC 47 — THE COSMIC ECONOMY ============================

  {
    id: "resource.qi_authority",
    kind: "custom",
    name: "Qi-Authority",
    tags: ["currency","reserve","finite","non_substitutable"],
    description: "The cosmic economy's reserve currency: the substrate's measurable qi-density, in a cultivator's anchor or in a court's reservoir. Qi-authority is finite (the cosmos is non-regenerating, doc 00 §1) and non-substitutable — every cosmic-scale transaction consumes it, directly or indirectly. It is not traded directly (too fundamental to transfer in discrete units); it is conserved, spent, or wasted, and the conservation is the cosmic economy's central practice. The Thinning is the decline of the Acquired stratum's total qi-authority.",
    source: "doc 47 §2.2, doc 00 §1",
    relations: [
      { type: "DERIVED_FROM", target: "essence.qi" },
      { type: "DECLINED_BY", target: "resource.thinning" },
    ],
    simulationHooks: ["economy","cultivation","politics","history"],
    version: "0.1.0",
  },
  {
    id: "resource.veneration",
    kind: "custom",
    name: "Veneration",
    tags: ["currency","ancestral_court","lineage_bound","non_transferable"],
    description: "The ancestral court currency (per doc 46 §5): the qi-pulse a lineage's living cultivators generate by the veneration rite — it flows from the living to the dead, sustains the ancestral courts, and is the medium in which the courts' interventions are denominated. Non-transferable (bound to the lineage's qi-connection to its court), except in the restricted form of inter-court donations — the named instance is the Garden Court's veneration-pulse donation to the Mourner's Court six hundred years ago, which cost the donating ancestor Muyuan approximately one percent of her remaining persistence-budget.",
    source: "doc 47 §2.2, doc 47 §1.4, doc 46 §5",
    relations: [
      { type: "INSTRUMENT_OF", target: "economy.ancestral_court_economy" },
    ],
    simulationHooks: ["economy","ritual","social","politics"],
    version: "0.1.0",
  },
  {
    id: "resource.law_fragment",
    kind: "custom",
    name: "Law-Fragments",
    tags: ["currency","high_tier","law_authorship","depreciating"],
    description: "The cosmic economy's highest-tier currency: the residue of failed law-authorship and of contested law-authorship (when a Mahayana's law is amended, the original law's residue persists in the substrate, fading over millennia). The only resource usable at Mahayana to study another Mahayana's law-authorship directly. Cannot be reused or repaired; fades over millennia (faster for shallower substrate and lower author realm). Tracked in the Records Department's Register of Law-Fragments (法殘錄). By the pantheon's collective assessment, a fragment's value is approximately a Tribulation Crossing cultivator's persistence-budget; the nine Mahayana hold, between them, perhaps fifty fragments worth studying, mostly hoarded.",
    source: "doc 47 §1.6, doc 47 §2.2",
    relations: [
      { type: "PART_OF", target: "resource.ancient_inheritances" },
    ],
    simulationHooks: ["economy","cultivation","history","politics"],
    version: "0.1.0",
  },
  {
    id: "resource.ancient_inheritances",
    kind: "treasure",
    name: "Ancient Inheritances",
    tags: ["treasure_class","ruins","residues","asymmetric"],
    description: "The cosmic economy's primary treasure-class resource — the ruins and residues of past cultivators, lineages, and civilizations, the cosmic-scale equivalent of mortal inheritance manuals. Categories: dispersed Mahayana anchor-residues (readable below Mahayana only through the law-legacy perception; tracked in the Register of Dispersed Mahayana, 散尊錄; the cosmos's property under the founding compact's jurisdiction 6, accessed by rare and costly pantheon permission); law-fragments of failed Reach-authorship (Lie Fa's fragment, the only known surviving Reach-collapse fragment, is the cosmos's most dangerous text, restricted to Mahayana); and the ruins of fallen civilizations (bark-strip libraries, partial Code-survivals, sealed grotto-heaven libraries). The inheritance-economy is structurally asymmetric: the past's catastrophes are the present's resources.",
    source: "doc 47 §1.1",
    relations: [
      { type: "PRODUCED_BY", target: "institution.pillar_dynasty", note: "the dynasty's collapse left the Pillar Cities' ruins and bark-strip libraries" },
      { type: "PRODUCED_BY", target: "institution.crimson_vow_alliance", note: "its collapse left the collapsed-anchor grotto and the fragmentary Crimson Vow Code" },
    ],
    simulationHooks: ["economy","history","cultivation","politics"],
    version: "0.1.0",
  },
  {
    id: "resource.time_debt",
    kind: "custom",
    name: "The Time-Debt",
    tags: ["constraint","precelestial","365x_multiplier","restricted_trade"],
    description: "The Precelestial-Acquired time-debt (1 Precelestial day = 1 Acquired year, per doc 15 §7.1): a lawful, non-negotiable 365x labor multiplier for a Precelestial being performing Acquired-stratum work. Restricted by three constraints: symmetry (the being's Precelestial day is one Acquired year of mortal-world aging), Acquired-time binding during in-stratum intervention (the being is 1x, not 365x, while acting in the stratum), and the Roads department's permit system. Actual volume is small — the nine Mahayana collectively visit the Acquired stratum perhaps once per Precelestial year. Time is the cosmic economy's master constraint, not a currency.",
    source: "doc 47 §1.5, doc 47 §2.2, doc 15 §7.1",
    relations: [
      { type: "GOVERNED_BY", target: "institution.courts_of_heaven", note: "the Roads department regulates stratum-crossing travel" },
    ],
    simulationHooks: ["economy","physics","politics","history"],
    version: "0.1.0",
  },
  {
    id: "resource.thinning",
    kind: "custom",
    name: "The Thinning",
    tags: ["scarcity","qi_decline","master_scarcity","slow_death"],
    description: "The Acquired Stratum's slow qi-density decline (per doc 39 §6) — the cosmic economy's master scarcity and the cosmos's slow death: spirit veins produce ~0.1% less qi per century (Records Department measurements); a 100-year ginseng now takes 110 years; a peak beast's core was ~10% larger a millennium ago. Trajectory if unbroken: qi-density below the Foundation Establishment threshold in 3,000-5,000 years; below Tribulation Crossing sustenance in 8,000-10,000; substrate failure and cascading laws in 12,000-15,000. Imperceptible below Nascent Soul; unmistakable at Spirit Severance and above.",
    source: "doc 47 §1.7, doc 37 §1.2, doc 39 §6",
    relations: [
      { type: "DECLINES", target: "resource.qi_authority" },
      { type: "AFFECTS", target: "economy.grotto_heaven_economy" },
    ],
    simulationHooks: ["economy","ecology","cultivation","history"],
    version: "0.1.0",
  },
  {
    id: "resource.cosmic_herb_10000",
    kind: "custom",
    name: "10,000-Year Herbs",
    tags: ["herb","cosmic_tier","grotto_heaven","mahayana_treasure"],
    description: "Cosmic-tier spirit herbs that grow only in peak grotto-heavens or the Spirit Wilds: 10,000-year herbs maturing in 1,000-3,000 Acquired-stratum years at grotto time-rates (the Jade Void's grotto 1:10, the Garden Grotto 1:5, the Crimson Vow City's former grotto 1:3) — e.g., the Garden Grotto's 10,000-year wood-phase spirit peach and the Jade Void's 10,000-year metal-phase spirit lotus. The alchemical equivalent of a Mahayana-tier treasure: they can sustain a Tribulation Crossing breakthrough, repair Spirit Severance anchor-damage, or rarely extend a Mahayana's span by a century. Not sold (no mortal currency can price them); gifted, traded for law-fragments or veneration-pulses, or hoarded. The Jade Void patriarch has authorized the spirit lotus's use twice in 2,100 years.",
    source: "doc 47 §1.2",
    relations: [
      { type: "PRODUCED_IN", target: "place.jade_void_grotto", note: "the Jade Void's 10,000-year metal-phase spirit lotus" },
    ],
    simulationHooks: ["economy","ecology","cultivation","trade"],
    version: "0.1.0",
  },
  {
    id: "resource.precelestial_herb",
    kind: "custom",
    name: "Precelestial Wild Herbs",
    tags: ["herb","spirit_wilds","no_phase","unpredictable"],
    description: "Precelestial herbs from the Spirit Wilds: alien plants with no phase-affinity whose effects on an Acquired cultivator's body are unpredictable — a forced qi-state re-tuning (a Qi Condensation cultivator forcibly re-tuned to a different phase-affinity), an accelerated cultivation (a Foundation Establishment meridian-integration compressed from years to hours), or a forced dispersion (undifferentiated qi overwhelms the anchor). Traded in the underworld market (doc 26 §9.2) at prices denominated in law-fragments, veneration-pulses, or rarely a Spirit Severance cultivator's qi-authority; the protagonist's companion Liang Zhu knows the herb-trade.",
    source: "doc 47 §1.2, doc 26 §9.2",
    relations: [
      { type: "TRADED_IN", target: "market.underworld_market" },
    ],
    simulationHooks: ["economy","ecology","cultivation","deviation"],
    version: "0.1.0",
  },
  {
    id: "resource.wild_beast_parts",
    kind: "custom",
    name: "Spirit Wilds Beast Parts",
    tags: ["beast","spirit_wilds","no_phase","armor","formation_substrate"],
    description: "Cosmic-tier beasts existing only in the Spirit Wilds or the deep Precelestial, outside the five-phase model: metabolisms on undifferentiated qi directly; cores (when present — some wild beasts lack anchors and therefore cores) are knots of undifferentiated qi refinable, with great difficulty, into Precelestial-tier pills; hides serve as Spirit Severance armor, bones as Tribulation Crossing formation-substrate. Hunted by Spirit Severance cultivators (the minimum realm at which the hunt is not suicide), organized in three small Wild Hunter lineages on the eastern continent's wild-edge, and traded through the underworld market.",
    source: "doc 47 §1.3",
    relations: [
      { type: "TRADED_IN", target: "market.underworld_market" },
    ],
    simulationHooks: ["economy","ecology","combat","trade"],
    version: "0.1.0",
  },
  {
    id: "economy.precelestial_acquired_trade",
    kind: "institution",
    name: "Precelestial-Acquired Trade",
    tags: ["trade","stratum_crossing","licensed_carriers","roads_department"],
    description: "The restricted trade across strata, managed by the Roads department (per doc 38 §2.4): every stratum-crossing transit requires a Roads permit; commercial transit is restricted to a small number of licensed carriers (twelve on the current roster — the Yan clan operates two, the Builder's Lineage three, the Garden Lineage one, the remaining six independent under the Rogue Outreach Bloc's incorporation program). Downward flow (Precelestial to Acquired): cosmic-tier herbs, law-inscribed treasures, rare ancestor-interventions, rarer Mahayana counsel — volume approximately a moderate holy land's annual revenue. Upward flow: veneration-pulses, Acquired-stratum goods, raw herbs and beast parts — larger in volume, lower in value-per-unit.",
    source: "doc 47 §2.1, doc 38 §2.4, doc 38 §3.4",
    relations: [
      { type: "GOVERNED_BY", target: "institution.courts_of_heaven", note: "the Roads department issues permits and licenses the twelve carriers" },
    ],
    simulationHooks: ["trade","economy","politics"],
    version: "0.1.0",
  },
  {
    id: "economy.grotto_heaven_economy",
    kind: "custom",
    name: "The Grotto-Heaven Economy",
    tags: ["grotto_heaven","production_zone","leases","wasting_asset"],
    description: "Grotto-heavens — Precelestial-affixed cultivation zones sustained by an Acquired spirit vein's main current — are the cosmic economy's primary production zones (where cosmic-tier herbs grow, cosmic-tier beasts are raised, cosmic-tier alchemy is performed): approximately one hundred and forty by Tu Nan's map (52 on the eastern continent, 41 central, 39 southern, 8 northern), a count down by ~10 over the last 3,000 years. Holy lands lease access: the Jade Void Holy Land's standard lease charges 1,000 spirit stones per day for a Core Formation cultivator, 100 per day for a Nascent Soul cultivator (subsidized), and free access for Tribulation Crossing cultivators who perform a 1-day maintenance service per 30 days of access. The grotto-heavens are, in the long run, a wasting asset — the Thinning's trajectory will fail them in 8,000-10,000 years.",
    source: "doc 47 §2.3, doc 39 §2.6",
    relations: [
      { type: "CONTROLLED_BY", target: "sect.jade_void", note: "the Jade Void Holy Land holds the Jade Void Grotto, the eastern continent's largest peak grotto-heaven" },
    ],
    simulationHooks: ["economy","cultivation","ecology","trade"],
    version: "0.1.0",
  },
  {
    id: "economy.ancestral_court_economy",
    kind: "custom",
    name: "The Ancestral Court Economy",
    tags: ["ancestral_court","vertical_sector","pension_fund"],
    description: "The ancestral court's qi-economy (per doc 46 §5): veneration flows up (from living to dead — the Yan clan's Acquired-stratum remnant generates a daily veneration-pulse ≈ 5,000,000 spirit stones equivalent), and the court's persistence-budget flows down in counsel, interventions (rare, denominated in persistence-budget), blessings (the most common down-flow), and curses. The cosmic economy's most vertical sector: the flows up are unidirectional, the flows down are constrained by the persistence-budget's finitude. The court is, in economic terms, the lineage's pension fund — filled in productive years, drawn in crisis years; the Wang lineage, courtless, has no reserve at all.",
    source: "doc 47 §2.4, doc 46 §5",
    relations: [
      { type: "SUSTAINED_BY", target: "resource.veneration" },
    ],
    simulationHooks: ["economy","ritual","social","politics"],
    version: "0.1.0",
  },
  {
    id: "market.underworld_market",
    kind: "institution",
    name: "The Underworld Market",
    tags: ["market","black_market","brokers","unregulated"],
    description: "The cosmic economy's unregulated sector (per doc 26 §9.2, doc 38 §9): a network of brokers, carriers, and fences (Liang Zhu, the protagonist's companion, is one) operating across the eastern and central continents' wild paths. Trades wild herbs the yao-court trade does not acquire, wild beast parts the Wild Hunters do not sell through licensed carriers, law-fragments the pantheon has not hoarded, and veneration-pulses stolen from corrupted retrieval rites (Scribe Yan's bardo-harvest is the named theft). Prices denominated in spirit stones (lower tier), law-fragments (higher tier), and qi-authority (highest tier, a controlled burn). Functionally the economy's pressure valve: it absorbs demand the licensed-carrier system cannot supply.",
    source: "doc 47 §2.5, doc 26 §9.2, doc 38 §9",
    relations: [
      { type: "TRADES", target: "resource.law_fragment" },
      { type: "TRADES", target: "resource.precelestial_herb" },
    ],
    simulationHooks: ["trade","economy","politics","social"],
    version: "0.1.0",
  },
  {
    id: "resource.law_reaches",
    kind: "custom",
    name: "The Law Reaches",
    tags: ["precelestial","reach_authorship","sundering_scars","common_ground"],
    description: "The Precelestial's regions where the substrate-law thinned (the Sundering's scars, per doc 15 §5) — the only venue for Reach-authorship. Approximately nine major Reaches (the Reach of the Sundered Stratum, Mo Shen's Reach, Lie Fa's Reach, the Reach of the Caged Sky, the Reach of the Western Mirror, of the Northern Wind, of the Eastern Tide, of the Southern Stem, of the Central Quiet) and a tail of thirty-seven minor ones, by Tu Nan's map. Explicitly outside the courts' jurisdiction; any Mahayana may enter and attempt authorship — the pantheon has not authored a new Reach-law in eight hundred years.",
    source: "doc 47 §3.1, doc 15 §5",
    relations: [
      { type: "PART_OF", target: "cosmological.precelestial_stratum" },
      { type: "CAUSED_BY", target: "event.the_sundering", note: "the Sundering's law-paradox propagation created the Reaches" },
    ],
    simulationHooks: ["economy","cultivation","politics","history"],
    version: "0.1.0",
  },
  {
    id: "law.authorship_property",
    kind: "custom",
    name: "Predecessors' Laws (Authorship-Property)",
    tags: ["law","authorship_property","ratification","council_vote"],
    description: "The procedural law governing predecessors' laws (per doc 24 §1.1): Acquired-authorship can amend existing Acquired law within a scope, but the amendment requires either the original law's author's ratification or the author's dispersal. A dispersed predecessor's law is ownerless — amendable by a simple-majority Council vote, the easiest procedure and the rarest case. Unlawful attempts are heard by the courts' Adjudication department. In cosmic-economic terms this is the cosmos's authorship-property and contract law — a Mahayana's law is the Mahayana's property, transferring only by the owner's consent or death; the protagonist's Transcend-path amendment of Gu Wu's bardo-window law is its central case.",
    source: "doc 47 §3.3, doc 24 §1.1",
    relations: [
      { type: "GOVERNED_BY", target: "institution.courts_of_heaven", note: "unlawful amendments are heard by the Adjudication department" },
    ],
    simulationHooks: ["politics","economy","history","cultivation"],
    version: "0.1.0",
  },

  // ============================ DOC 37 — COSMIC HISTORY ============================

  {
    id: "event.cosmic_creation",
    kind: "event",
    name: "The Age of the Cosmos",
    nameHanzi: "宇宙紀年之算",
    tags: ["cosmology","48,000_years","cosmic_age_calculation","finite"],
    description: "The cosmos is 48,000 years old, by the Courts of Heaven's Records Department's Cosmic Age Calculation (宇宙紀年之算) — a measured, not round, number derived from three reconciled lines of evidence: substrate-depth measurement (~10,000 years of Mahayana inscription on ~38,000 years of pre-authorship substrate), ancestor-memory correlation (Courts founded ~8,000 years ago; Gu Wu preceded them by ~2,000), and qi-density decline projection. Error bar ±5,000 years. The cosmos is finite, generated, and non-regenerating (doc 00 §1); at the current Thinning rate it has perhaps another two hundred thousand years before qi-density drops below the cultivation threshold.",
    source: "doc 37 §1.1, doc 37 §1.2, doc 00 §1",
    relations: [
      { type: "CAUSED_BY", target: "cosmological.nameless_origin" },
    ],
    simulationHooks: ["history","physics","cultivation"],
    version: "0.1.0",
  },
  {
    id: "event.epochal_sequence",
    kind: "event",
    name: "The Six Epochs",
    nameHanzi: "紀元之序",
    tags: ["history","taxonomy","records_department","nascent_soul_tier"],
    description: "The Courts of Heaven Records Department's official epoch taxonomy (the Epochal Sequence, 紀元之序), dividing 48,000 years into six named epochs: the Generative Epoch (~20,000 years; the Nameless Origin generates the Precelestial substrate; ends as the first anchors self-inscribe), the Primordial Substrate Epoch (~18,000; the realm ladder develops to Void Amalgamation; ends as Gu Wu becomes the first Mahayana), the First Law Epoch (~2,000; Gu Wu invents law-authorship, the pantheon fills; ends with the Sundering), the Sundering Epoch (~500; the Law Reaches are created; ends as the Courts are founded), the Long Peace Epoch (~7,250, to Year 47,753; civilizations rise and fall; the Thinning becomes perceptible), and the Current Epoch (247 years so far, the Epoch of the Fading Law, 末法紀元). The epoch names are not known below the Nascent Soul tier.",
    source: "doc 37 §2",
    relations: [
      { type: "RESULTED_IN", target: "institution.great_yan", note: "the transition into the Current Epoch is the Great Yan Dynasty's founding (Year 47,753)" },
    ],
    simulationHooks: ["history","politics","cultivation"],
    version: "0.1.0",
  },
  {
    id: "event.fourth_stratum_attempt",
    kind: "event",
    name: "The Fourth-Stratum Attempt",
    nameHanzi: "第四境之妄法",
    tags: ["primordial_authors","forbidden_law","law_paradox","co_authored"],
    description: "The co-authored law of Ming Kongsang (明空桑) and Wei Duchuan (魏渡川) — a Mahayana and his student, both of the original nine — inscribed in a Reach of the deep Precelestial, which would have generated a fourth stratum between the Precelestial and the Origin if it had held. The law-paradox (the cosmos's lawful resistance to the forbidden act) fired and dispersed both authors. The only co-authored law in cosmic history to produce a law-paradox severe enough to disperse its authors; its residue persists, sealed, in the Reach of the Sundered Stratum.",
    source: "doc 37 §3.4",
    relations: [
      { type: "CAUSED", target: "event.the_sundering" },
    ],
    simulationHooks: ["history","physics"],
    version: "0.1.0",
  },
  {
    id: "event.the_sundering",
    kind: "event",
    name: "The Sundering",
    nameHanzi: "斷層",
    tags: ["catastrophe","law_paradox","bardo_overwhelm","law_reaches"],
    description: "Year ~40,000: the Sundering (斷層, the Broken Boundary), the cosmic history's single most catastrophic event — Ming Kongsang and Wei Duchuan's Fourth-Stratum Attempt's law-paradox destroyed both authors, destabilized the Precelestial's substrate-law for several centuries, created the Law Reaches (regions where the substrate-law thinned and has not recovered), and killed billions of anchors in the bardo-overwhelm (natural bardo-processing crashed; the backlog took three centuries to clear). The Sundering directly motivated the Courts of Heaven's founding.",
    source: "doc 37 §5",
    relations: [
      { type: "CAUSED_BY", target: "event.fourth_stratum_attempt" },
      { type: "RESULTED_IN", target: "event.courts_founding" },
    ],
    simulationHooks: ["history","physics","politics","ritual"],
    version: "0.1.0",
  },
  {
    id: "event.courts_founding",
    kind: "event",
    name: "The Courts' Founding",
    tags: ["founding","seven_founders","founding_compact","expansions"],
    description: "Year ~40,000, the Sundering's immediate aftermath: the Courts of Heaven were founded ~8,000 years ago by seven founders — Gu Wu/Qiu Wuhen (the only Mahayana among them) and six Tribulation Crossing cultivators — convened on the site of the Garth of Roads (lawfully inhabited ~12,000 years before the founding), formalizing the founding compact's six jurisdictions (the Dead, Tribulation, the Maintained Roads, the Spirit Wilds' borders, the Lineages (excluded), Authored Law (excluded)). Three (or four) Expansions follow: the First (~8,000 years ago) establishes the Underworld as a courts sub-jurisdiction; the Second (~4,000 years ago) formalizes the bardo-window law; the Third (~2,000 years ago) claims advisory jurisdiction over the Spirit Wilds; the Fourth (disputed) is Yan Qingshi's records-integrity law, converted into cosmic law without a Council vote.",
    source: "doc 37 §4, doc 38 §5",
    relations: [
      { type: "RESULTED_IN", target: "institution.courts_of_heaven" },
      { type: "CONTAINS", target: "institution.underworld", note: "the First Expansion established the Underworld as a courts sub-jurisdiction" },
      { type: "PRECEDED_BY", target: "event.the_sundering" },
    ],
    simulationHooks: ["history","politics","ritual","economy"],
    version: "0.1.0",
  },
  {
    id: "institution.pillar_dynasty",
    kind: "institution",
    name: "The Pillar Dynasty",
    nameHanzi: "柱朝",
    tags: ["fallen_civilization","yao","wood_phase","vein_exhaustion"],
    description: "A non-human civilization of wood-phase yao (yao with anchors, descended from the Spirit Wilds' native wood-phase entities): fused-stone cities, a bark-strip written script, yao-cultivation based on wood-phase primary with earth-phase secondary, ~8 million yao at its height. Flourished Year ~22,000-30,000 in the southern continent's central highlands (the oldest of the three named fallen civilizations; it rose before the first Mahayana and fell before the Sundering). Fell Year ~30,000 when the Pillar Root Vein (柱根脈) — seven major wood-phase veins tributary to a single deep primary — was exhausted; the last yao-Mahayana, the Pillar Lord of the Last Sap (末汁柱), dispersed himself. Ruins: the Pillar Cities (柱城群) with bark-strip libraries; the Pillar Dynasty Annals (柱朝紀) in 12 volumes, of which the Jade Void Holy Land holds 7 and the Verdant Pillar holds 5.",
    source: "doc 37 §6.1",
    relations: [
      { type: "LOCATED_IN", target: "region.nan" },
      { type: "RESULTED_IN", target: "vein.pillar_root_remnant", note: "the Pillar Root Vein collapsed with the dynasty's fall; its remnant still flows at a fraction of its ancient capacity" },
      { type: "ASSOCIATED_WITH", target: "sect.verdant_pillar", note: "holds 5 of the 12 Annals volumes; its grotto contains the seven surviving Pillar Cities' ruins" },
    ],
    simulationHooks: ["history","economy","ecology","politics"],
    version: "0.1.0",
  },
  {
    id: "institution.crimson_vow_alliance",
    kind: "institution",
    name: "The Crimson Vow Alliance",
    nameHanzi: "赤誓盟",
    tags: ["fallen_civilization","fire_phase","guarantor_bound","collapse"],
    description: "An alliance of Core Formation+ sects and lineages, predominantly fire-phase, in the eastern continent's central lowlands: 14 great sects, 7 holy lands, ~120 lesser sects and lineages, bound by the Crimson Vow Law (赤誓法) to the founding Mahayana guarantor Daojun Chiri (赤日道君, the Lord of the Red Sun), with the shared legal code (the Crimson Vow Code, 赤誓律) and capital the Crimson Vow City (a major grotto-heaven at 1:3 time-rate). Flourished Year ~41,000-43,000. Fell Year ~43,000 when Chiri's failed law-amendment tribulation dispersed her anchor, the oath-bound alliance unraveled, and war over the city cracked three spirit veins and sealed the grotto (8,000 cultivators trapped inside, presumed dispersed). The Crimson Vow Code survives ~60% in the Jade Void Holy Land's library; the Crimson Vow Remnant (赤誓餘孽) persists as a hidden demonic network.",
    source: "doc 37 §6.2",
    relations: [
      { type: "LOCATED_IN", target: "region.dong" },
      { type: "ASSOCIATED_WITH", target: "sect.jade_void", note: "the holy land's library holds approximately 60% of the Crimson Vow Code" },
    ],
    simulationHooks: ["history","economy","politics","combat"],
    version: "0.1.0",
  },
  {
    id: "institution.silent_hexagram_school",
    kind: "institution",
    name: "The Silent Hexagram School",
    nameHanzi: "默卦宗",
    tags: ["fallen_civilization","divination","corrupted_ancestor","sealed"],
    description: "A small divination lineage — never more than thirty living cultivators — founded by Daoist Silent Hexagram (默卦真人), a Nascent Soul diviner who developed the Silent Hexagram Method (默卦之法) of unprecedented accuracy and persisted as an ancestor after his bodily death; the cosmos's preeminent divination tradition for 2,500 years (Year ~43,000-45,500), in the central continent's northern hills. Fell Year ~45,500 when the founder-ancestor corrupted; the school's last Core Formation cultivator, Jing Wuyin (靜無音), petitioned the Courts (declined, lineage-jurisdiction), then disbanded the school, destroyed the grotto-heaven's anchor (sealing the library inside), severed the lineage rite, and sealed the corrupted ancestor within its own court before dispersing herself fifty years later. A fragment of the method reached the Cangli Riverlands and became Wang Lun's hexagram tradition.",
    source: "doc 37 §6.3, doc 37 §9.2",
    relations: [
      { type: "LOCATED_IN", target: "region.zhong" },
      { type: "ASSOCIATED_WITH", target: "region.cangli_riverlands", note: "a fragment of its method reached the riverlands and became Wang Lun's hexagram tradition" },
    ],
    simulationHooks: ["history","ritual","perception","politics"],
    version: "0.1.0",
  },
  {
    id: "event.sky_devouring_beast_sealing",
    kind: "event",
    name: "The Sky-Devouring Beast's Sealing",
    nameHanzi: "吞天獸",
    tags: ["sealed_evil","substrate_predator","law_consumption","coalition_seal"],
    description: "Year ~45,000 (3,000 years ago): the Sky-Devouring Beast (吞天獸), a substrate-predator from the Spirit Wilds whose nature is to consume law-inscriptions, breached the Acquired Stratum through a Law Reach's edge, consumed three grotto-heavens, and was cornered and sealed by a coalition of three Mahayana cultivators — one dispersed in the sealing (the Beast consumed his law-authorship). Sealed in the Reach of the Caged Sky (籠天法域, ~500 li across, in the Precelestial's southern interior), a lineage-seal maintained in rotation by the two surviving lineages' Tribulation Crossing cultivators. If the seal breaks, the Defense Department estimates the Beast would consume six to ten grotto-heavens before a coalition could re-seal it.",
    source: "doc 37 §7.2, doc 47 §1.3",
    relations: [
      { type: "LOCATED_IN", target: "cosmological.precelestial_stratum", note: "sealed in the Reach of the Caged Sky" },
    ],
    simulationHooks: ["history","combat","politics","ecology"],
    version: "0.1.0",
  },
  {
    id: "event.zhou_wugui_incursion",
    kind: "event",
    name: "The Zhou Wugui Incursion",
    tags: ["demonic_cultivator","cangwu","41_deaths","karmic_tribulation"],
    description: "The Cangli Riverlands' most recent demonic-cultivator event, 95 years ago (Year 47,905): Zhou Wugui, a Cangwu Sect washout who had spent fifteen years without progress at Qi Condensation, disappeared and, over eighteen months, harvested the anchors of 41 mortals in three Cangwu foothills villages (White Stone Village, Mill Ford, and the original Black Creek settlement), advancing to late Foundation Establishment. Pursued for three months by the previous Azure Sword sect master, he was confronted at the Demon's Cut and destroyed not by the sect master's technique but by his own karmic tribulation, which fired during the fight; the sect master perceived the anchor disperse. Doc 37 establishes Zhou Wugui was recruited — by the Crimson Vow Remnant, a hidden demonic network claiming descent from the Crimson Vow Alliance's dissolved membership.",
    source: "doc 37 §9.4, doc 25 §5.4",
    relations: [
      { type: "LOCATED_IN", target: "place.cangwu_mountains" },
      { type: "ASSOCIATED_WITH", target: "institution.crimson_vow_alliance", note: "Zhou Wugui was recruited by the alliance's remnant, the Crimson Vow Remnant" },
    ],
    simulationHooks: ["history","combat","social","ritual"],
    version: "0.1.0",
  },

  // ============================ DOC 25 — NAMED FOLK RELIGION BEINGS ============================

  {
    id: "spirit.earth_god_wang_tugeng",
    kind: "custom",
    name: "Wang Tugeng",
    tags: ["place_spirit","earth_god","wang_family_bend","quasi_anchor"],
    description: "The earth god of Wang Family Bend (土地公), named Wang Tugeng by the village three generations ago: a place-spirit — the consciousness of a spirit vein's surface trace, a sui generis qi-pattern with attention, memory, and will — that cohered above a minor wood-phase vein's surface trace in the centuries before the Wangs arrived, and has been venerated at the same shrine for nine generations. Cautious and conservative, it nudges the village's luck in small ways (a fever breaking early, a fox turning from the henhouse) but does not intervene in larger patterns. Its anchor-object is a ~30cm carved soapstone figure in the shrine at the village's west entrance; its destruction would severely damage the spirit.",
    source: "doc 25 §2.7",
    relations: [
      { type: "LOCATED_IN", target: "location.wang_family_bend" },
      { type: "CO_AUTHORED_BY", target: "resource.veneration", note: "a place-spirit forms from a dense surface trace plus generations of mortal veneration (minimum ~90 years, three generations)" },
    ],
    simulationHooks: ["ritual","social","ecology","perception"],
    version: "0.1.0",
  },
  {
    id: "spirit.river_god_lord_cangli",
    kind: "custom",
    name: "Lord Cangli",
    tags: ["place_spirit","river_god","oath_bound","cangli_river"],
    description: "The river god of the Cangli (河神), named Lord Cangli in the riverlands' tradition — a name the spirit accepts but did not choose: a place-spirit that cohered above the Cangli's main water-phase vein's surface trace ~400 years ago, sustained by the veneration of the riverlands' fishing and ferrying communities along a sixty-li stretch of the middle river. Temperamental and oath-bound: an oath sworn at its shrine is registered in its quasi-anchor, and it withholds its minor nudges from an oath-broken household. Its anchor-object is a black wooden plaque at the south-bank temple, replaced every thirty years by the Zhengyi priest from the market town.",
    source: "doc 25 §2.8",
    relations: [
      { type: "LOCATED_IN", target: "region.cangli_riverlands", note: "jurisdiction is the river itself — water, banks, fords, fish, boats — within a sixty-li stretch" },
    ],
    simulationHooks: ["ritual","weather","social"],
    version: "0.1.0",
  },
  {
    id: "spirit.city_god_magistrate_cang",
    kind: "custom",
    name: "Magistrate Cang",
    tags: ["place_spirit","city_god","deputized","recorder_of_the_dead"],
    description: "The city god of Cangli County Seat (城隍), named Magistrate Cang: a place-spirit that cohered above an earth-phase vein's surface trace beneath the county seat's old wall ~200 years ago. Bureaucratic and deputized — the only one of the three named place-spirits with a formal deputyship from a courts magistrate (a Tribulation Crossing cultivator in the Records department): it registers every death within its jurisdiction (name, date, cause) as the local recorder of the dead, its register duplicated in the courts' register (生死簿). A city god caught falsifying its register is destroyed — its anchor-object shattered, its pattern unwound — which has happened twice in the county seat's history, in both cases for bribery by lineages seeking to conceal a murder.",
    source: "doc 25 §2.9",
    relations: [
      { type: "LOCATED_IN", target: "region.cangli_riverlands" },
      { type: "DEPUTIZED_BY", target: "institution.courts_of_heaven", note: "formal deputyship from a courts magistrate; local recorder of the dead for the Records department" },
    ],
    simulationHooks: ["ritual","politics","social","history"],
    version: "0.1.0",
  },
  {
    id: "spirit.fox_lady_bai",
    kind: "custom",
    name: "Lady Bai",
    tags: ["yao","fox_spirit","foundation_establishment","cangwu_foothills"],
    description: "The fox-spirit of the Cangwu foothills (狐仙), called Lady Bai in the market town's tradition — a name she did not give and does not use: a red fox that achieved peak-tier spirit beast status ~400 years ago, completed the anchor-transition ~250 years ago (surviving a heart-demon tribulation whose central attachment was her first mate, killed by a hunter), and took stable human form — a young woman of about twenty — ~200 years ago. Late Foundation Establishment, preparing for the Core Formation form-tribulation for thirty years. A good-faith resident: she has never harmed a mortal unprovoked, has twice taken mortal lovers (young scholars), and pays for market-town fruit with coins earned by healing a farmer's child.",
    source: "doc 25 §4.5",
    relations: [
      { type: "LOCATED_IN", target: "place.cangwu_mountains" },
    ],
    simulationHooks: ["social","ecology","cultivation","reproduction"],
    version: "0.1.0",
  },
  {
    id: "spirit.black_creek_serpent",
    kind: "custom",
    name: "The Black Creek Serpent",
    tags: ["yao","snake_demon","peak_tier_cognition","unresolved"],
    description: "The snake-demon of the western Cangwu (蛇妖), called the Black Creek Serpent in the local tradition — a name the yao itself does not use, since it does not speak: a king cobra that achieved peak-tier spirit beast status ~600 years ago and barely survived its anchor-transition ~300 years ago (a heart-demon tribulation whose central attachment was its first mate). The transition completed the anchor but not the cognition: a yao with a true anchor and the cognition of a peak-tier beast. It does not take human form, does not negotiate, and has killed eleven humans in the last century in its five-li black-creek valley territory; no sect has resolved the situation.",
    source: "doc 25 §4.6",
    relations: [
      { type: "LOCATED_IN", target: "place.cangwu_mountains" },
    ],
    simulationHooks: ["ecology","combat","social"],
    version: "0.1.0",
  },
  {
    id: "spirit.tree_old_cypress",
    kind: "custom",
    name: "Old Cypress",
    tags: ["yao","tree_spirit","sessile","grove_protector"],
    description: "The thousand-year tree-spirit of the eastern Cangwu (樹精), called Old Cypress — a name the yao accepts: a cypress that achieved peak-tier status ~800 years ago, completed its anchor-transition ~500 years ago (a heart-demon tribulation whose central attachment is the grove it grew in, logged four hundred years before the transition), and is both a yao and the place-spirit of its grove, venerated by three Cangwu-village lineages. Late Foundation Establishment; sessile, with tree-time cognition (a thought takes days). It has killed thirty-two mortals (all cypress-cutters) and zero cultivators in five centuries; its karmic trace is a record of five centuries of grove-life.",
    source: "doc 25 §4.7",
    relations: [
      { type: "LOCATED_IN", target: "place.cangwu_mountains" },
    ],
    simulationHooks: ["ecology","ritual","perception","social"],
    version: "0.1.0",
  },
  {
    id: "institution.underworld",
    kind: "institution",
    name: "The Underworld",
    nameHanzi: "地府",
    tags: ["courts_sub_jurisdiction","bardo_processing","archive","records_department"],
    description: "The Underworld (地府): a sub-jurisdiction of the Courts of Heaven — the Records department's enforcement arm that processes anchors in bardo for rebirth. A vast, dim, orderly archive in the Precelestial, staffed by courts-appointed officials (Tribulation Crossing cultivators in the Records department); anchors are registered, karmically read, assigned a rebirth-path, and escorted to rebirth. There is no Yama, no ten kings, no eighteen hells, no bridges of gold and silver — those are mortal projections onto a bureaucratic process; the Underworld does not punish, it processes.",
    source: "doc 25 §6, doc 37 §4.3",
    relations: [
      { type: "PART_OF", target: "institution.courts_of_heaven", note: "a sub-jurisdiction; the Records department's enforcement arm" },
    ],
    simulationHooks: ["ritual","history","politics","social"],
    version: "0.1.0",
  },
  {
    id: "custom.demonic_cultivation",
    kind: "custom",
    name: "Demonic Cultivation",
    nameHanzi: "魔修",
    tags: ["one_true_evil","anchor_harvesting","irreversible","criminal"],
    description: "Demonic cultivation (魔修): the practice of using other beings' anchors as fuel — harvesting an anchor from bardo, refining (unwinding) it into raw law-substrate, and burning it to accelerate cultivation. The cosmology's one true evil: the deliberate dispersion of another being's anchor for the cultivator's own power, producing irreversible metaphysical destruction (no rebirth, no ancestral court, no recovery). Criminal under every jurisdiction — the courts (record-tampering), the immortal alliance (one of the three threats it exists to suppress), sect law (the highest crime, punishable by death), lineage law, and karma (the karmic tribulation is the cosmos's ultimate enforcement; a demonic cultivator who reaches Core Formation is rare, one who reaches Nascent Soul rarer still).",
    source: "doc 25 §5",
    relations: [
      { type: "SUPPRESSED_BY", target: "institution.immortal_alliance", note: "named one of the three threats the alliance exists to suppress" },
      { type: "ENFORCED_BY", target: "event.tribulation", note: "the karmic tribulation is the cosmos's ultimate enforcement against it" },
    ],
    simulationHooks: ["combat","social","cultivation","deviation","politics","ritual","history"],
    version: "0.1.0",
  },
];
