/**
 * Folk religion + metaphysics definitions extracted from the corpus-extension docs:
 * doc 25 (Folk Religion Metaphysics — main source), doc 38 (Courts of Heaven —
 * named beings tied to folk religion only), doc 04 (Mortal Substrate — village
 * rituals, ancestor tablets, shrine practices, festival calendar).
 *
 * Only things NAMED in the docs. Descriptions are faithful condensed paraphrases;
 * no facts invented. Hanzi are given exactly as the corpus gives them. Where the
 * cosmology ratifies a mortal belief as myth (Yama, ghost-marriage, paper money),
 * the entry says so — the myth itself is the folk-religion content.
 */
import type { Definition } from '../definitions';

export const FOLK_RELIGION_DEFINITIONS: Definition[] = [
  // ============================ NAMED PLACE-SPIRITS ============================

  {
    id: "folk_spirit.wang_tugeng",
    kind: "npc_role",
    name: "Earth God of Wang Family Bend",
    nameHanzi: "土地公",
    tags: ["place_spirit","earth_god","wang_family_bend","cautious","quasi_anchor"],
    description: "Wang Tugeng: the earth god (土地公) of Wang Family Bend, a name the village gave the spirit three generations ago when an elder dreamed of an old man in a green robe who said he had been the lineage's first tenant farmer in the founder's time; the dream was a real perception, but the spirit does not claim to be that tenant farmer. Its quasi-anchor cohered above a minor wood-phase vein's surface trace in the centuries before the Wangs arrived, sustained by an earlier community whose name is forgotten; the Wangs adopted the spirit when they settled the bend and it adopted them. Nine generations of veneration make it coherent and reasonably powerful for a village-scale place-spirit; it is cautious and conservative, wary of the bend's repeated floods (most recently forty years ago), and nudges the village's luck in small ways without intervening in larger patterns. Its anchor-object is a small carved soapstone figure (~30cm) of an old man in a green robe holding a walking stick, in the shrine at the west entrance of the village; its destruction would severely damage the spirit.",
    source: "doc 25 §2.7, doc 04 §5.3",
    relations: [
      { type: "IS_A", target: "custom.place_spirit" },
      { type: "WORSHIPPED_BY", target: "location.wang_family_bend" },
      { type: "LOCATED_IN", target: "institution.spirit_shrine" },
      { type: "GUARDS", target: "location.wang_family_bend", note: "enforces the village boundary against low-tier threats" },
    ],
    simulationHooks: ["ritual","social","ecology","weather","perception","history"],
    version: "0.1.0",
  },
  {
    id: "folk_spirit.lord_cangli",
    kind: "npc_role",
    name: "River God of the Cangli",
    nameHanzi: "河神",
    tags: ["place_spirit","river_god","oath_bound","temperamental","quasi_anchor"],
    description: "Lord Cangli: the river god (河神) of the Cangli, a name the spirit accepts but did not choose. It cohered above the Cangli's main water-phase vein's surface trace roughly four hundred years ago, sustained by the veneration of the riverlands' fishing and ferrying communities along a sixty-li stretch of the middle river. Its jurisdiction is the river itself — water, banks, fords, fish, boats — within that stretch; it has no jurisdiction over the bank villages except where they touch the water. Temperamental and oath-bound: oaths sworn at its shrine are registered in its quasi-anchor, and it withholds its minor luck-nudges from an oath-broken household; the great flood forty years ago was hydrological, but the spirit's withholding of its nudges was a real response to a Wang elder's broken oath. Its anchor-object is a black wooden plaque inscribed with its name, kept in the south-bank temple's main hall, replaced every thirty years (the river's humidity rots wood) by the Zhengyi priest from the market town; the replacement rite transfers the spirit's pattern from the old plaque to the new.",
    source: "doc 25 §2.8, doc 04 §5.3",
    relations: [
      { type: "IS_A", target: "custom.place_spirit" },
      { type: "WORSHIPPED_BY", target: "region.cangli_riverlands" },
      { type: "LOCATED_IN", target: "institution.river_god_temple" },
      { type: "GUARDS", target: "region.cangli_riverlands", note: "jurisdiction is the river itself within its sixty-li stretch" },
    ],
    simulationHooks: ["ritual","weather","ecology","social","trade","history"],
    version: "0.1.0",
  },
  {
    id: "folk_spirit.magistrate_cang",
    kind: "npc_role",
    name: "City God of Cangli County Seat",
    nameHanzi: "城隍",
    tags: ["place_spirit","city_god","deputized","recorder_of_the_dead","bureaucratic"],
    description: "Magistrate Cang: the city god (城隍) of Cangli County Seat, a name the spirit does not accept and does not refuse. It cohered above an earth-phase vein's surface trace beneath the county seat's old wall roughly two hundred years ago, sustained by the veneration of the county's bureaucracy and citizenry; its jurisdiction is the city within the old wall — a denser, more urban jurisdiction than a village earth god's. Bureaucratic and deputized: the only of the three named place-spirits with a formal deputyship from the local court magistrate (a Tribulation Crossing cultivator in the courts' Records department who administers the Jiangnan region from a Precelestial office). The deputyship requires it to register every death within its jurisdiction — name, date, cause — in its quasi-anchor's memory and relay the register to the courts' Records department via a periodic rite performed by the county's Daoist priest: the local recorder of the dead, the first link in the chain by which the dead are processed. It does not adjudicate; it records. Its register is duplicated in the courts' register of the dead; a city god caught falsifying its register is destroyed (its anchor-object shattered, its pattern unwound) — this has happened twice in the county seat's history, in both cases for bribery by lineages seeking to conceal a murder.",
    source: "doc 25 §2.9",
    relations: [
      { type: "IS_A", target: "custom.place_spirit" },
      { type: "WORSHIPPED_BY", target: "region.cangli_riverlands" },
      { type: "REPORTS_TO", target: "institution.courts_of_heaven", note: "deputized by a local court magistrate; relays the death register to the Records department" },
    ],
    simulationHooks: ["ritual","politics","history","social","perception"],
    version: "0.1.0",
  },

  // ============================ METAPHYSICAL CATEGORIES ============================

  {
    id: "custom.place_spirit",
    kind: "custom",
    name: "Place-Spirit",
    tags: ["quasi_anchor","spirit_vein","veneration","sui_generis","jurisdiction"],
    description: "The place-spirit: the consciousness of a spirit vein's surface trace when that trace is dense enough and venerated long enough. A sui generis ontological category — not a god, not a Precelestial official, not an ancestor, not a cultivator, not a beast, not a ghost — a self-sustaining qi-pattern that has acquired attention, memory, and will. In the body/qi/anchor triad it is a being of qi with a quasi-anchor: its body is the place itself (soil, water, stone, the boundary of its jurisdiction); it cannot be reincarnated or possessed; it does not bear karma in the human sense; destroyed, it ends. The vernacular calls them 公: the earth god (土地公), the river god (河神), the city god (城隍). Formation requires three conditions over generations: a dense spirit-vein surface trace, veneration (co-authored by the vein and the community — veneration is itself a qi-input), and time (roughly three generations, about ninety years, minimum; Wang Family Bend's earth god has nine generations, the Cangli river god at least seven). Within its jurisdiction it can nudge local weather (a day, a few li), bias minor fortune and misfortune at the cost of its own qi, and enforce the boundary against low-tier threats (a wandering ghost is slowed, a Qi Condensation cultivator of malign intent feels pressure to turn back) — modulations, not walls. Jurisdiction is bounded to its place: beyond it the spirit simply dissipates. Its relationship to the Courts of Heaven is independence without sovereignty: not court-appointed, not registered in the courts' register, but possibly deputized by a local magistrate for a specific task. It dies by vein collapse, veneration cessation (a slow death; the abandoned spirit persists a generation or two as a fading echo), or destruction of its anchor-object (the shrine's main image — the spirit's handle, not its body; if the object is not rebuilt within a season, the spirit usually unwinds within a year).",
    source: "doc 25 §2.1-2.5",
    relations: [
      { type: "REQUIRES", target: "essence.qi", note: "a qi-pattern; the body/qi/anchor triad" },
      { type: "INDEPENDENT_OF", target: "institution.courts_of_heaven", note: "independence without sovereignty; not registered in the courts' register" },
    ],
    simulationHooks: ["ecology","weather","social","ritual","perception","history"],
    version: "0.1.0",
  },
  {
    id: "custom.bardo",
    kind: "custom",
    name: "Bardo",
    tags: ["afterlife","intermediate_state","forty_nine_days","anchor_condition","boundary"],
    description: "The bardo: the intermediate state between death and rebirth. Not a place but a condition of an anchor — the state of a disembodied anchor past death, persisting a bounded, lawful time; the lawful default window is forty-nine days, regularized by Qiu Wuhen's bardo-window law, which fixed the previously-variable window. At the window's end an anchor has three lawful paths: rebirth (the default), final death (寂滅 — the anchor disperses, the being ends), or — if the karmic trace contains an attachment of sufficient strength — persistence in bardo, anchored to a Mortal place, becoming a ghost. The bardo's boundary with the Mortal stratum is the threshold at which a disembodied anchor's qi-projection can manifest in Mortal-stratum qi; the threshold varies with the qi-climate (highest at the summer solstice when bardo is suppressed, lowest at the winter solstice when it is amplified) and is annually thinnest on the fifteenth day of the seventh lunar month — the Ghost Festival.",
    source: "doc 25 §3.1, §3.7, doc 38 §4.1",
    relations: [
      { type: "REGULATED_BY", target: "institution.courts_of_heaven", note: "the bardo-window law (Qiu Wuhen's, four thousand years old) fixed the forty-nine-day window" },
    ],
    simulationHooks: ["ritual","perception","history","social"],
    version: "0.1.0",
  },
  {
    id: "custom.ghost",
    kind: "custom",
    name: "Ghost",
    nameHanzi: "鬼",
    tags: ["extended_bardo","unresolved_attachment","anchor_point","ghost_sickness","quasi_possession"],
    description: "A ghost (鬼): an anchor in extended bardo, anchored to a Mortal place by unresolved attachment — the same ontological category as a living being's anchor, severed from body and partially severed from qi, persisting past the bardo window's end when normal processing failed (no lineage rite, no sect rite, and the death unregistered). Three conditions converge at the window's end: an unresolved attachment (grief, hatred, an unfulfilled oath, or love) strong enough to overcome the momentum toward rebirth; an anchor-point in the Mortal stratum (the ghost cannot roam; it is bound to the place and a few hundred paces around it); and failure of processing. Ghosts are typed by attachment: grief-ghosts (most common, least harmful — they watch and nudge), hatred-ghosts (most dangerous — they project their hatred onto any living being at the anchor-point and can accumulate enough qi-density to harm), oath-ghosts (most active — they seek a living being who can fulfill the oath), love-ghosts (saddest — they watch until the beloved dies or the attachment resolves). Capabilities: manifest as a qi-presence (a coldness, a sound, a shape), influence the heart-mind of the living (the mechanism behind ghost-sickness), and possess the weak — not true possession (奪舍), which displaces an anchor; a ghost can only suppress the anchor's expression through the body's qi. Laid to rest either by resolving the attachment (preferred by every tradition) or by a Core Formation cultivator forcibly dispersing the anchor-fragment (a last resort, criminal without first attempting resolution). Distinct from ancestors: a ghost is what happens when the normal system fails; an ancestor is what happens when the normal system succeeds at a high enough level.",
    source: "doc 25 §3.1-3.6",
    relations: [
      { type: "REQUIRES", target: "custom.bardo" },
      { type: "COUNTERED_BY", target: "custom.exorcism", note: "may or may not help; an exorcism is designed to disperse a ghost's anchor-fragment" },
      { type: "OBSERVED_IN", target: "event.ghost_festival", note: "on the festival's thin boundary even weak ghosts can manifest" },
    ],
    simulationHooks: ["perception","ritual","social","deviation","history","disease"],
    version: "0.1.0",
  },
  {
    id: "custom.yao",
    kind: "custom",
    name: "Yao",
    nameHanzi: "妖",
    tags: ["animal_anchor","personhood","human_form","form_tribulation","wayward_immortal"],
    description: "A yao (妖): a beast that has developed an anchor — the only nonhuman being in the Mortal stratum that possesses the full body/qi/anchor triad, making it metaphysically equivalent to a human: the anchor is the seat of personhood, so a yao can be wronged, bear karma, be saved, and be reborn, and killing one is treated as killing a person. A spirit beast, by contrast, has body and qi but no anchor; it lives an animal's life and dies an animal's death. The transition is the rarest event in the Mortal stratum's ecology: a peak-tier spirit beast's inner core (內丹, a proto-anchor) completes its inscription into a true anchor through a tribulation — typically a heart-demon tribulation (心魔劫) that confronts the beast with the unresolved attachments of its animal life. Most peak-tier beasts sense the tribulation and decline, living out their ~500-year lifespans and dying. A yao's cultivation path is harder than a human's: it begins with an animal body and cognition, it must take stable human form (the human form is the architecture the anchor can most fully express through), and it faces a form-tribulation at each major realm boundary (four, from Core Formation through Tribulation Crossing). A yao that survives all four form-tribulations and crosses to the Precelestial becomes a wayward immortal (妖仙); none are documented in the Cangli Riverlands' history. Named yao of the Cangwu foothills — Lady Bai the fox-spirit, the Black Creek Serpent, Old Cypress — are defined in the beast layer.",
    source: "doc 25 §4.1-4.3",
    relations: [],
    simulationHooks: ["ecology","cultivation","reproduction","history","deviation","perception"],
    version: "0.1.0",
  },
  {
    id: "custom.underworld_processing",
    kind: "custom",
    name: "Underworld Processing",
    tags: ["bardo_processing","karmic_reading","rebirth_path","mirror_pool","records"],
    description: "The Underworld's fixed processing sequence for an anchor in bardo, performed in a vast, dim, orderly archive (jade tablets on shelves, quiet corridors, officials who process rather than punish). (1) Registration: the local place-spirit's register — the city god's — records the death and relays it via a periodic rite to the courts' Records department, which assigns a processing-clerk who locates the anchor in bardo and brings it into the archive. (2) Karmic reading: the clerk reads the anchor's karmic trace; the anchor confronts its own karmic ledger in full — the mortal tradition remembers this as the mirror-pool of reflection. (3) Rebirth-path calculation: based on the reading, the clerk calculates the next embodiment that reflects the anchor's karmic momentum — causal, not moral; a heavy killing-trace is drawn to a violent rebirth, a healing-trace to a healing profession. (4) Assignment: recorded, and the anchor is escorted to the boundary between bardo and the Mortal stratum, drawn to its next embodiment — typically a mortal birth, rarely an animal rebirth, rarer still an Acquired-stratum rebirth. (5) Special cases: an anchor retrieved by a lineage or sect rite is released before processing; an anchor with an unsustainable karmic ledger is dispersed (final death, 寂滅) as lawful resolution; ghosts are in principle retrieved by the enforcement arm, in practice often resolved by their attachment instead. There is no Yama and no ten-kings hierarchy; the mortal tradition's specifics are projection.",
    source: "doc 25 §6.2-6.3, doc 38 §1.1",
    relations: [
      { type: "PART_OF", target: "institution.underworld" },
      { type: "REQUIRES", target: "folk_spirit.magistrate_cang", note: "the city god's death register is the first link in the chain by which the dead are processed" },
      { type: "INVOLVES", target: "npc.scribe_yan", note: "Scribe Yan falsifies bardo-dispersal records, delaying anchors for an underworld-market broker" },
    ],
    simulationHooks: ["ritual","perception","history","politics","social"],
    version: "0.1.0",
  },
  {
    id: "custom.yama_ten_kings",
    kind: "custom",
    name: "The Ten Courts of Yama",
    nameHanzi: "十殿閻羅",
    tags: ["mortal_projection","partial_myth","underworld","eschatology"],
    description: "The mortal tradition's Underworld eschatology: the ten courts of Yama (十殿閻羅), the mirror-pools of reflection, the bridges of gold and silver, the eighteen hells of punishment, the wheel of rebirth. Explicitly partial myth: there is no Yama; the ten kings are mortal imaginations of the Underworld's bureaucratic hierarchy; there are no eighteen punishment-hells (the 'punishment' is the anchor's own karmic confrontation during the reading); there are no bridges of gold and silver (the rebirth-path is a calculated assignment, not a chosen crossing). The tradition's general shape — death, judgment, rebirth — is correct, and its purpose — to give the dead a comprehensible fate, to give the living a moral framework, to give the community a ritual structure for mourning — is real and valuable. The Underworld does not require the mortal tradition to be metaphysically accurate; it requires only that its practices continue to feed the place-spirits, the lineages, and the courts' record-keeping.",
    source: "doc 25 §6.1, §8.2",
    relations: [
      { type: "PROJECTION_OF", target: "custom.underworld_processing", note: "the ten kings, mirror-pools and hells are mortal interpretations of the processing stages" },
    ],
    simulationHooks: ["ritual","history","perception","social"],
    version: "0.1.0",
  },

  // ============================ DIVINATION, DREAMS ============================

  {
    id: "custom.divination",
    kind: "custom",
    name: "Divination",
    nameHanzi: "卜",
    tags: ["hexagram","yarrow_stalks","qi_momentum","wang_lun","partially_accurate"],
    description: "Divination (卜): the village's diviner is Wang Lun, the lineage school teacher, who casts hexagrams (卦) from yarrow stalks (蓍草) for supplicants who ask about marriage, travel, illness, or harvest; he is not always right, and he knows this. Metaphysically, divination is real: hexagrams perceive qi-momentum — the present's lawful tendency — not the future. A skilled diviner is more right than an unskilled one, and a Core Formation diviner more right than a Qi Condensation one; the mortal belief that hexagrams can reveal the future is partially accurate.",
    source: "doc 04 §5.3, doc 25 §8.2",
    relations: [
      { type: "INVOKED_BY", target: "npc.wang_lun" },
      { type: "INVOKED_IN", target: "location.wang_family_bend" },
    ],
    simulationHooks: ["perception","social","ritual","history"],
    version: "0.1.0",
  },
  {
    id: "custom.dream_perception",
    kind: "custom",
    name: "Dream Perception",
    nameHanzi: "夢",
    tags: ["perception_mode","anchor_perception","ghost_dreams","ancestor_dreams","dream_cultivation"],
    description: "A dream (夢): a perception mode, not a stratum — the perception of the anchor when the body's sensory constraints are suspended. Dream content is perception of real phenomena: qi-residue (a dreamer near a murder-site dreams of violence), ambient qi (wood-phase ambient qi produces dreams of growth), bardo-presence (a ghost near the dreamer is perceived directly — the mechanism of ghost-dreams), and ancestral qi-impressions (a cultivation lineage's ancestral court can send a qi-impression to a sleeping descendant — ancestor-dreams are real for cultivation-lineage members; for mortal-lineage members the dream of a dead parent is usually the lineage hall's accumulated grief-rite residue, not the parent's actual anchor, though the emotional truth is the same). Dream cultivation is a recognized practice-track: lucidity, direction (choosing what to perceive), perceiving at distance (dream-scrying), communicating with the dead, and investigating qi-residue. Ancestral dream-messages are real but imperfect — the interpretation is lossy, which is why ancestral consultations are performed with a Core Formation cultivator present to read the qi-impression directly.",
    source: "doc 25 §7.1-7.4",
    relations: [
      { type: "PERCEIVES", target: "custom.ghost", note: "ghost-dreams: the dreaming anchor perceives a ghost's anchor-fragment directly" },
    ],
    simulationHooks: ["perception","ritual","cultivation","history","social","deviation"],
    version: "0.1.0",
  },

  // ============================ BURIAL, MOURNING, ANCESTRY ============================

  {
    id: "custom.funeral_rite",
    kind: "custom",
    name: "Funeral Rite",
    nameHanzi: "喪禮",
    tags: ["burial","shroud","coffin","bardo_thinning","social_event"],
    description: "The funeral rite (喪禮): a death triggers the rite, the household's most expensive ritual event after a marriage. The body is washed, dressed in a burial shroud (壽衣), laid in a coffin (棺材, built by Lin Aqiao the carpenter), kept in the household for 3-7 days while mourners visit, then carried to the graveyard and buried; a Daoist priest is summoned if the household can afford it. Mourners wear undyed hemp (white, the color of mourning). The funeral is also a social event: the lineage, the neighbors, and the deceased's affinal kin gather, eat, and settle accounts. The deceased's tablet is installed in the household altar. Metaphysically, the rite's purpose is real: at its climax the boundary between the Mortal stratum and the bardo is thinned, allowing the deceased's anchor to be processed more cleanly — a Core Formation cultivator performing the rite perceives the processing-clerk directly, and a Qi Condensation cultivator perceives the thinning as a cold, attentive quality to the air.",
    source: "doc 04 §7.3, doc 25 §6.5",
    relations: [
      { type: "REQUIRES", target: "custom.bardo", note: "the rite thins the Mortal/bardo boundary so the anchor is processed more cleanly" },
      { type: "INVOKED_IN", target: "location.wang_family_bend" },
    ],
    simulationHooks: ["ritual","social","economy","disease","perception","history"],
    version: "0.1.0",
  },
  {
    id: "custom.mourning_period",
    kind: "custom",
    name: "Three-Year Mourning",
    nameHanzi: "守孝",
    tags: ["mourning","sons","hemp","tablet_transfer"],
    description: "The mourning period (守孝): after a death the sons observe a 3-year mourning period, during which they do not marry, do not attend festivals, and wear rough hemp. After the 3-year mourning, the deceased's tablet may be moved from the household altar to the lineage hall if the deceased was a lineage member of standing.",
    source: "doc 04 §7.3",
    relations: [
      { type: "PART_OF", target: "custom.funeral_rite" },
    ],
    simulationHooks: ["social","ritual","history","reproduction"],
    version: "0.1.0",
  },
  {
    id: "custom.ancestor_veneration",
    kind: "custom",
    name: "Ancestor Veneration",
    nameHanzi: "祭祖",
    tags: ["household_altar","lineage_hall","qingming","ancestral_court","most_important"],
    description: "Ancestor veneration (祭祖): the most important layer of the village's religious life. Every household has a small altar with the tablets of recent ancestors (parents, grandparents); the lineage hall holds the tablets of the deeper ancestors. Rites at the hall (spring and autumn) and at the graveyard (Qingming) are lineage obligations, not optional. Metaphysically, veneration is real: it feeds either a place-spirit's quasi-anchor (for the unremembered dead), a cultivation lineage's ancestral court (for the lineage's great cultivators), or the local grief-rite residue (for the ordinary dead) — it feeds the metaphysical infrastructure the dead depend on, though in most cases it does not 'reach' the specific dead. An ancestor is an anchor retrieved from bardo and lifted into the Precelestial stratum, sustained by the lineage's veneration and the ancestral court's qi-authority: not place-bound, not attachment-driven, intended to be permanent — the distinction from a ghost (a system failure) is that an ancestor is the system working at a high enough level.",
    source: "doc 04 §5.3, doc 25 §3.5, §8.2",
    relations: [
      { type: "INVOKED_IN", target: "institution.lineage_hall" },
      { type: "INVOKED_IN", target: "location.ancestral_graveyard" },
      { type: "CELEBRATED_IN", target: "event.qingming" },
      { type: "WORSHIPPED_BY", target: "lineage.wang" },
    ],
    simulationHooks: ["ritual","social","history","reproduction","economy"],
    version: "0.1.0",
  },
  {
    id: "custom.ancestor_tablet",
    kind: "custom",
    name: "Ancestor Tablet",
    nameHanzi: "神主牌",
    tags: ["household_altar","lineage_hall","installation","memorial"],
    description: "The ancestor tablet (神主牌): the lineage hall's main hall holds the tablets of the deeper ancestors, while every household's small altar holds the tablets of recent ancestors (parents, grandparents). At the funeral the deceased's tablet is installed in the household altar; after the 3-year mourning it may be moved to the lineage hall if the deceased was a lineage member of standing. The tablets are the physical seat of the lineage's ancestor veneration.",
    source: "doc 04 §1.1, §7.3",
    relations: [
      { type: "LOCATED_IN", target: "institution.lineage_hall" },
      { type: "PART_OF", target: "custom.ancestor_veneration" },
    ],
    simulationHooks: ["ritual","social","history"],
    version: "0.1.0",
  },
  {
    id: "custom.exorcism",
    kind: "custom",
    name: "Exorcism",
    nameHanzi: "驅邪",
    tags: ["daoist_priest","fright_disease","possession","uncertain_efficacy"],
    description: "Exorcism (驅邪): the Daoist priest, who lives in the market town and is a Zhengyi (正一) priest — married, household-based, not monastic — is summoned for spiritual afflictions, what the village calls fright disease (驚病), demon possession (中邪), and unexplained deaths; he performs exorcisms, which may or may not help. Metaphysically, an exorcism is designed to disperse a ghost's anchor-fragment, and it has no effect on a yao (whose true anchor is integrated with a living body); it is the conversation a Daoist priest believes he is having when performing an exorcism, while a Qi Condensation cultivator is the first being who is actually having it with the ghost directly.",
    source: "doc 04 §7.2, doc 25 §3.8, §4.5",
    relations: [
      { type: "COUNTERS", target: "custom.ghost", note: "may or may not help; designed to disperse a ghost's anchor-fragment" },
    ],
    simulationHooks: ["ritual","disease","deviation","perception","social"],
    version: "0.1.0",
  },
  {
    id: "custom.ghost_marriage",
    kind: "custom",
    name: "Ghost-Marriage",
    nameHanzi: "冥婚",
    tags: ["myth","veneration_qi_input","the_dead","partially_true"],
    description: "Ghost-marriage (冥婚): the mortal belief that a dead son can be married to a dead daughter to provide them companionship in the afterlife. The belief is myth — the dead are processed by the Underworld and reborn; they do not persist as a couple. The rite itself is, metaphysically, a veneration-qi-input to the place-spirits of the two dead's anchor-points, which may (if the ghosts persist) provide them a brief respite from their attachments. It does not marry them.",
    source: "doc 25 §8.2",
    relations: [
      { type: "INVOLVES", target: "custom.ghost", note: "may provide persisting ghosts a brief respite from their attachments" },
    ],
    simulationHooks: ["ritual","social","history"],
    version: "0.1.0",
  },
  {
    id: "custom.paper_money_burning",
    kind: "custom",
    name: "Burning Paper Money",
    tags: ["qi_input","ghost_festival","qingming","functional_rite"],
    description: "The burning of paper money and paper goods for the dead: metaphysically the burning of qi-charged paper for the qi-release — a qi-input to whatever anchors are present at the burning-site. It does not 'reach' the specific dead in the Underworld (the Underworld does not use currency); it feeds the local bardo-boundary's qi-density, which benefits whatever anchors are present. The rite is functional, but not in the way the mortal tradition believes; it is performed at the Ghost Festival and at Qingming, where tombs are cleaned and offered food and paper money.",
    source: "doc 25 §3.7, §8.2, doc 04 §3.1 term 5",
    relations: [
      { type: "PART_OF", target: "event.ghost_festival" },
      { type: "PART_OF", target: "event.qingming" },
    ],
    simulationHooks: ["ritual","economy","social","perception"],
    version: "0.1.0",
  },

  // ============================ SHRINES, HALL, GRAVEYARD ============================

  {
    id: "institution.spirit_shrine",
    kind: "institution",
    name: "Spirit Shrine",
    nameHanzi: "土地廟",
    tags: ["earth_god","west_entrance","bi_monthly_incense","village_maintained"],
    description: "The spirit shrine (土地廟): a tiny building (~2m square) at the west entrance of Wang Family Bend, dedicated to the local earth god (土地公). It is maintained by the village as a whole, not by the lineage. Incense is burned on the 1st and 15th of each lunar month. It holds the earth god's anchor-object — the small carved soapstone figure, ~30cm tall, of an old man in a green robe holding a walking stick — which is the spirit's primary veneration-channel; its destruction would severely damage the spirit.",
    source: "doc 04 §1.1, §5.3, doc 25 §2.7",
    relations: [
      { type: "WORSHIPPED_BY", target: "location.wang_family_bend" },
      { type: "LOCATED_IN", target: "location.wang_family_bend" },
      { type: "HOUSES", target: "folk_spirit.wang_tugeng", note: "holds the earth god's anchor-object, the small carved soapstone figure" },
    ],
    simulationHooks: ["ritual","social","perception","ecology"],
    version: "0.1.0",
  },
  {
    id: "institution.river_god_temple",
    kind: "institution",
    name: "River God Temple",
    tags: ["south_bank","river_god","oath_swearing","plaque_replacement"],
    description: "The river god's small temple on the south bank of the Cangli, across the ford from Wang Family Bend; the river god (河神) is responsible for the river's floods, fish, and boats. A plaque in the lineage hall records a flood 40 years ago that the village's elders attribute to the river god's anger at a broken oath. The temple's main hall keeps the god's anchor-object — the black wooden plaque inscribed with the spirit's name — which is replaced every thirty years (the river's humidity rots wood) by the Zhengyi priest from the market town; the replacement rite transfers the spirit's pattern from the old plaque to the new. Oaths sworn at the temple are registered in the spirit's quasi-anchor, and the spirit withholds its minor nudges from an oath-broken household.",
    source: "doc 04 §5.3, doc 25 §2.8",
    relations: [
      { type: "WORSHIPPED_BY", target: "location.wang_family_bend" },
      { type: "LOCATED_IN", target: "region.cangli_riverlands" },
      { type: "HOUSES", target: "folk_spirit.lord_cangli", note: "main hall keeps the black wooden plaque, the god's anchor-object" },
    ],
    simulationHooks: ["ritual","weather","ecology","social","trade"],
    version: "0.1.0",
  },
  {
    id: "institution.lineage_hall",
    kind: "institution",
    name: "Lineage Hall",
    nameHanzi: "祠堂",
    tags: ["ancestor_tablets","lineage_school","highest_ground","wang_lineage"],
    description: "The lineage hall (祠堂): sits on the highest ground, ~50m north of the levee, oriented south-facing (the auspicious direction). A single-courtyard building: front gate, open courtyard, main hall with the ancestor tablets (神主牌), and side rooms for storage and the lineage school. It is the largest structure in the village and belongs to the Wang lineage. Rites at the hall (spring and autumn) are lineage obligations, not optional; the Lantern Festival sets lanterns at the lineage hall.",
    source: "doc 04 §1.1, §5.3",
    relations: [
      { type: "PART_OF", target: "lineage.wang" },
      { type: "LOCATED_IN", target: "location.wang_family_bend" },
      { type: "HOUSES", target: "custom.ancestor_tablet" },
    ],
    simulationHooks: ["ritual","social","history","politics","economy"],
    version: "0.1.0",
  },
  {
    id: "location.ancestral_graveyard",
    kind: "location",
    name: "Ancestral Graveyard",
    nameHanzi: "祖墳",
    tags: ["burial","low_hill","wang_lineage_property","tomb_sweeping"],
    description: "The ancestral graveyard (祖墳): on the low hill (~1km north of Wang Family Bend) above the flood line, oriented to face the village. It is Wang lineage property; other lineages bury their dead elsewhere. It is the site of Qingming tomb-sweeping (villagers visit, clean the tombs, offer food and paper money), of Ghost Festival offerings, and of the funeral processions that carry the dead from the household to burial.",
    source: "doc 04 §1.1, §3.3",
    relations: [
      { type: "LOCATED_IN", target: "region.cangli_riverlands" },
      { type: "PART_OF", target: "lineage.wang", note: "Wang lineage property; other lineages bury their dead elsewhere" },
    ],
    simulationHooks: ["ritual","social","history","ecology"],
    version: "0.1.0",
  },

  // ============================ FESTIVALS ============================

  {
    id: "event.ghost_festival",
    kind: "event",
    name: "Ghost Festival",
    nameHanzi: "中元",
    tags: ["fifteenth_of_seventh_month","bardo_thinnest","offerings","inauspicious_travel"],
    description: "The Ghost Festival / Spirit Festival (中元), the 15th day of the 7th lunar month. Mortal tradition says the gates of the underworld open and the dead walk among the living; the metaphysical reality is that the bardo-boundary is annually thinnest on this day, across the widest geographic range — thin enough that even weak ghosts can manifest, and strong ghosts can manifest more legibly; the thinness lasts roughly three days, and the ambient qi is threaded with bardo-residue (the characteristic 'ghost-festival feeling': cold, attentive, watched). The mortal rites are functional: the offerings are qi-inputs directed at the bardo-boundary, absorbed by whatever anchors are present; the lineage rite for unburied or unremembered dead is a controlled bardo-feeding (providing qi-density to fading anchors so they can resolve their attachment or be processed by the underworld, which uses the festival's thinness as an efficient processing window); burning paper money is the burning of qi-charged paper. In the village: offerings at the spirit shrine and at the graveyard, and the lineage holds a rite for unburied or unremembered dead. It is an inauspicious day for travel or major undertakings — the mortal advice to stay home is sound advice.",
    source: "doc 25 §3.7, doc 04 §3.3",
    relations: [
      { type: "CELEBRATED_IN", target: "location.wang_family_bend" },
      { type: "INVOKED_IN", target: "institution.spirit_shrine" },
      { type: "INVOKED_IN", target: "location.ancestral_graveyard" },
      { type: "REQUIRES", target: "custom.bardo", note: "the day the bardo-boundary is annually thinnest" },
    ],
    simulationHooks: ["ritual","social","perception","history","economy"],
    version: "0.1.0",
  },
  {
    id: "event.qingming",
    kind: "event",
    name: "Qingming",
    nameHanzi: "清明",
    tags: ["tomb_sweeping","most_important_ancestral_rite","solar_term","graveyard"],
    description: "Qingming (清明, Clear and Bright), April 4-6 — the 5th solar term and the most important ancestral rite of the year. Villagers visit the ancestral graveyard, clean the tombs, and offer food and paper money; the lineage holds the spring ancestor rite at the hall. Tomb-sweeping is the ritual verb of the season, an obligation the lineage treats as not optional.",
    source: "doc 04 §3.1 term 5, §3.3",
    relations: [
      { type: "CELEBRATED_IN", target: "location.wang_family_bend" },
      { type: "INVOKED_IN", target: "location.ancestral_graveyard" },
      { type: "INVOKED_IN", target: "institution.lineage_hall", note: "the lineage holds the spring ancestor rite at the hall" },
    ],
    simulationHooks: ["ritual","social","history","economy"],
    version: "0.1.0",
  },
  {
    id: "event.spring_festival",
    kind: "event",
    name: "Spring Festival",
    nameHanzi: "春節",
    tags: ["new_year","communal_meal","debt_settlement","red_envelopes"],
    description: "The Spring Festival (春節), New Year, late January / early February (lunar). The lineage holds a communal meal; households settle debts; firecrackers (if the village can afford them) drive off the year's misfortune; children receive red envelopes (紅包).",
    source: "doc 04 §3.3",
    relations: [
      { type: "CELEBRATED_IN", target: "location.wang_family_bend" },
    ],
    simulationHooks: ["ritual","social","economy","history"],
    version: "0.1.0",
  },
  {
    id: "event.lantern_festival",
    kind: "event",
    name: "Lantern Festival",
    nameHanzi: "元宵",
    tags: ["fifteenth_of_first_month","lanterns","sweet_dumplings"],
    description: "The Lantern Festival (元宵), the 15th day of the 1st lunar month. Lanterns at the lineage hall and the spirit shrine; sweet dumplings (湯圓).",
    source: "doc 04 §3.3",
    relations: [
      { type: "CELEBRATED_IN", target: "location.wang_family_bend" },
      { type: "INVOKED_IN", target: "institution.lineage_hall", note: "lanterns at the lineage hall and the spirit shrine" },
      { type: "INVOKED_IN", target: "institution.spirit_shrine" },
    ],
    simulationHooks: ["ritual","social","economy"],
    version: "0.1.0",
  },
  {
    id: "event.dragon_boat",
    kind: "event",
    name: "Dragon Boat Festival",
    nameHanzi: "端午",
    tags: ["fifth_of_fifth_month","boat_races","zongzi","mugwort","pest_control"],
    description: "The Dragon Boat Festival (端午), the 5th day of the 5th lunar month. The river is the center — boat races (if the village can field a crew) and zongzi (粽子, glutinous rice dumplings wrapped in bamboo leaves); it commemorates Qu Yuan (屈原). It is also a pest-control rite: mugwort (艾草) hung over doors to repel insects and evil.",
    source: "doc 04 §3.3",
    relations: [
      { type: "CELEBRATED_IN", target: "region.cangli_riverlands", note: "the river is the center" },
    ],
    simulationHooks: ["ritual","social","economy","ecology","weather"],
    version: "0.1.0",
  },
  {
    id: "event.mid_autumn",
    kind: "event",
    name: "Mid-Autumn Festival",
    nameHanzi: "中秋",
    tags: ["fifteenth_of_eighth_month","mooncakes","family_gathering"],
    description: "The Mid-Autumn Festival (中秋), the 15th day of the 8th lunar month. Mooncakes (月餅); families gather; the salt merchant receives gifts from his customers; a night of socializing under the moon.",
    source: "doc 04 §3.3",
    relations: [
      { type: "CELEBRATED_IN", target: "location.wang_family_bend" },
    ],
    simulationHooks: ["ritual","social","economy","trade"],
    version: "0.1.0",
  },
  {
    id: "event.double_ninth",
    kind: "event",
    name: "Double Ninth Festival",
    nameHanzi: "重陽",
    tags: ["ninth_of_ninth_month","hill_climbing","chrysanthemum_wine","elderly"],
    description: "The Double Ninth Festival (重陽), the 9th day of the 9th lunar month. Climbing hills (the graveyard hill, if no other); chrysanthemum wine; a day for the elderly.",
    source: "doc 04 §3.3",
    relations: [
      { type: "CELEBRATED_IN", target: "location.wang_family_bend" },
      { type: "INVOKED_IN", target: "location.ancestral_graveyard", note: "climbing the graveyard hill, if no other" },
    ],
    simulationHooks: ["ritual","social","aging"],
    version: "0.1.0",
  },
  {
    id: "event.winter_solstice",
    kind: "event",
    name: "Winter Solstice Festival",
    nameHanzi: "冬至",
    tags: ["solar_term","genealogy_update"],
    description: "The Winter Solstice festival (冬至, term 22 of the 24 solar terms). Its festival content is the genealogy update — the lineage's genealogical record is revised.",
    source: "doc 04 §3.3",
    relations: [
      { type: "CELEBRATED_IN", target: "location.wang_family_bend" },
    ],
    simulationHooks: ["ritual","history","social"],
    version: "0.1.0",
  },
  {
    id: "event.laba",
    kind: "event",
    name: "Laba",
    nameHanzi: "臘八",
    tags: ["eighth_of_twelfth_month","laba_porridge","buddhist_temple"],
    description: "Laba (臘八), the 8th day of the 12th lunar month. Laba porridge (臘八粥), a mix of grains, beans, and nuts. Buddhist temples (the nearest is 30 li away) distribute porridge, and the village's few Buddhists make a point of attending.",
    source: "doc 04 §3.3",
    relations: [
      { type: "CELEBRATED_IN", target: "location.wang_family_bend" },
    ],
    simulationHooks: ["ritual","social","economy","trade"],
    version: "0.1.0",
  },
];
