/**
 * Named NPC definitions — extracted from the corpus' character documents.
 *
 * Primary sources:
 *  - doc 34 "Named NPCs and Companions" (households, companions, antagonist, death schedule)
 *  - doc 28 "The Village In Medias Res" (village residents with secrets/griefs/ambitions)
 *  - doc 04 "The Cangli Riverlands" (village roles and lineage)
 *  - doc 46 "Ancestral Courts and Lineages" (court founders and named Precelestial figures)
 *
 * Fidelity rules: only characters NAMED in the docs; descriptions paraphrase the
 * doc text without invented facts; nameHanzi only where the docs print it.
 */

import type { Definition } from '../definitions';

export const NPC_DEFINITIONS: Definition[] = [
  // === Wang Family Bend — the Senior Household (Household 1) ===
  { id: "npc.wang_shouzheng", kind: "npc_role", name: "Wang Shouzheng", nameHanzi: "王守正", tags: ["lineage_head","li_head","senior_household","protagonist_father","mortal"], description: "The Wang lineage head (58) and the village's de facto leader; the protagonist's father. He doctored his second son's birth record to spare him the autumn corvée levy, has not wept since holding his father Wang Tianlu's hand as it went cold, and hopes the lineage will produce a cultivator for protection against the Azure Sword Sect's creeping influence.", source: "doc 28 §3.1, doc 34 §1.1", relations: [{ type: "SPOUSE_OF", target: "npc.lady_chen" }, { type: "PARENT_OF", target: "npc.wang_zongxian" }, { type: "PARENT_OF", target: "npc.wang_zongwen" }, { type: "PARENT_OF", target: "npc.wang_sanniang" }, { type: "PARENT_OF", target: "npc.wang_xiaodi" }, { type: "CHILD_OF", target: "npc.wang_tianlu" }, { type: "SIBLING_OF", target: "npc.lady_wang_hu" }, { type: "SIBLING_OF", target: "npc.wang_shouli" }, { type: "HALF_SIBLING_OF", target: "npc.wang_tianfu" }, { type: "COUSIN_OF", target: "npc.wang_shouye" }, { type: "COUSIN_OF", target: "npc.wang_lun" }, { type: "MEMBER_OF", target: "location.wang_family_bend", note: "lineage head and li head" }], simulationHooks: ["social","politics","economy","aging","disease"], version: "0.1.0" },
  { id: "npc.lady_chen", kind: "npc_role", name: "Lady Chen", nameHanzi: "陳氏", tags: ["mother","senior_household","weaver","mortal"], description: "The protagonist's mother (54). She secretly weaves extra cloth at night and leaves it at Widow Xu's gate, considering it a debt not charity; she grieves her youngest son Wang Xiaodi's death without ever blaming the player, and wants the player to marry a good mortal spouse — she fears cultivation, having seen Old Chen alone on his hill.", source: "doc 28 §3.2", relations: [{ type: "SPOUSE_OF", target: "npc.wang_shouzheng" }, { type: "PARENT_OF", target: "npc.wang_zongxian" }, { type: "PARENT_OF", target: "npc.wang_zongwen" }, { type: "PARENT_OF", target: "npc.wang_sanniang" }, { type: "PARENT_OF", target: "npc.wang_xiaodi" }], simulationHooks: ["social","economy","aging","disease"], version: "0.1.0" },
  { id: "npc.wang_zongxian", kind: "npc_role", name: "Wang Zongxian", nameHanzi: "王宗顯", tags: ["son","senior_household","heir","mortal"], description: "Eldest son of the Senior Household (32, married, 2 children); he inherits the lineage headship when Wang Shouzheng dies.", source: "doc 34 §1.1, doc 34 §4.3", relations: [{ type: "CHILD_OF", target: "npc.wang_shouzheng" }, { type: "CHILD_OF", target: "npc.lady_chen" }, { type: "SIBLING_OF", target: "npc.wang_zongwen" }, { type: "SIBLING_OF", target: "npc.wang_sanniang" }], simulationHooks: ["social","aging"], version: "0.1.0" },
  { id: "npc.wang_zongwen", kind: "npc_role", name: "Wang Zongwen", nameHanzi: "王宗文", tags: ["son","assistant_teacher","herbalist","mortal"], description: "Second son of the Senior Household (27, married, 1 child), assistant teacher at the lineage school; he has some knowledge of herbs learned from his grandmother and can treat cuts, fevers, and digestive complaints, but not serious illness.", source: "doc 34 §1.1, doc 04 §7.2", relations: [{ type: "CHILD_OF", target: "npc.wang_shouzheng" }, { type: "CHILD_OF", target: "npc.lady_chen" }, { type: "SIBLING_OF", target: "npc.wang_zongxian" }, { type: "SIBLING_OF", target: "npc.wang_sanniang" }], simulationHooks: ["social","disease","economy","aging"], version: "0.1.0" },
  { id: "npc.wang_sanniang", kind: "npc_role", name: "Wang Sanniang", nameHanzi: "王三娘", tags: ["daughter","betrothed","mortal"], description: "Youngest daughter of the Senior Household (22), betrothed to Li Zongwen of Li Family Creek for a 40-tael bride-price the household has saved only 28 taels toward. She does not want the marriage but does not want to shame her father, and has spoken of her reluctance to no one.", source: "doc 28 §2.3, doc 34 §1.1", relations: [{ type: "CHILD_OF", target: "npc.wang_shouzheng" }, { type: "CHILD_OF", target: "npc.lady_chen" }, { type: "SIBLING_OF", target: "npc.wang_zongxian" }, { type: "SIBLING_OF", target: "npc.wang_zongwen" }], simulationHooks: ["social","economy","aging"], version: "0.1.0" },

  // === Tenant and Salt Merchant households (2, 3) ===
  { id: "npc.wang_shouye", kind: "npc_role", name: "Wang Shouye", nameHanzi: "王守業", tags: ["cousin","tenant_farmer","tenant_household","mortal"], description: "Wang Shouzheng's cousin (52), head of the Wang Tenant Household; a tenant farmer whose family has held the surface right to 8 mu heritably for three generations, with the subsoil owned by a market-town landlord.", source: "doc 34 §1.1, doc 04 §2.2", relations: [{ type: "COUSIN_OF", target: "npc.wang_shouzheng" }, { type: "PARENT_OF", target: "npc.wang_zongde" }], simulationHooks: ["economy","social","aging","disease"], version: "0.1.0" },
  { id: "npc.wang_zongde", kind: "npc_role", name: "Wang Zongde", nameHanzi: "王宗德", tags: ["bare_stick","rival","tenant_household","mortal"], description: "The 24-year-old 'bare stick' of the Tenant Household, unmarried and resentful, studying with a traveling hustler; the duel with the protagonist (Scene 3) sets a trajectory — respect, exile with a grudge, illness and humility, or friendship — that determines how he lives and dies.", source: "doc 34 §1.1, doc 34 §4.5", relations: [{ type: "CHILD_OF", target: "npc.wang_shouye" }], simulationHooks: ["social","aging","disease","combat"], version: "0.1.0" },
  { id: "npc.master_hu", kind: "npc_role", name: "Master Hu", nameHanzi: "胡老爺", tags: ["salt_merchant","dock","non_wang","mortal"], description: "The salt merchant at the dock (47), holder of the county salt license (鹽引); wealthier than any Wang, he has no voice in lineage affairs but is treated with care because he controls access to salt. He has been paying an autumn bribe to the county magistrate's secretary to renew the license — and this year the new secretary wants double.", source: "doc 28 §3.4, doc 04 §2.2", relations: [{ type: "SPOUSE_OF", target: "npc.lady_wang_hu" }, { type: "PARENT_OF", target: "npc.hu_bao" }, { type: "SUSPECTS", target: "npc.li_asheng", note: "wrongly suspects him of being the competing salt-license bidder" }], simulationHooks: ["economy","trade","politics","social","aging"], version: "0.1.0" },
  { id: "npc.lady_wang_hu", kind: "npc_role", name: "Lady Wang", nameHanzi: "王氏", tags: ["salt_household","shouzheng_sister","mortal"], description: "Master Hu's wife (43), born a Wang and Wang Shouzheng's younger sister; no Wang attended her wedding, and she has not spoken to her brother in 20 years, living 200 paces from his house without crossing his threshold.", source: "doc 34 §0, doc 28 §3.4", relations: [{ type: "SPOUSE_OF", target: "npc.master_hu" }, { type: "SIBLING_OF", target: "npc.wang_shouzheng" }, { type: "PARENT_OF", target: "npc.hu_bao" }], simulationHooks: ["social","aging"], version: "0.1.0" },
  { id: "npc.hu_bao", kind: "npc_role", name: "Hu Bao", nameHanzi: "胡寶", tags: ["son","apprentice","merchant","mortal"], description: "Master Hu's son (18), apprenticed to his father; Hu intends to hand the business over to him in ten years.", source: "doc 34 §1.1, doc 28 §3.4", relations: [{ type: "CHILD_OF", target: "npc.master_hu" }, { type: "CHILD_OF", target: "npc.lady_wang_hu" }], simulationHooks: ["economy","trade","aging"], version: "0.1.0" },

  // === Lin and Widow's households (4, 5) ===
  { id: "npc.lin_aqiao", kind: "npc_role", name: "Lin Aqiao", nameHanzi: "林阿巧", tags: ["carpenter","non_wang","baojia_head","mortal"], description: "The village carpenter (38), a non-Wang who builds and repairs houses, boats, mill machinery, and coffins, paid in grain, cash, or labor-exchange; he is also the bao head (保長), a deliberate balance to the Wang-dominated li head.", source: "doc 04 §2.2, doc 04 §5.2", relations: [{ type: "SPOUSE_OF", target: "npc.lady_wang_lin" }, { type: "MEMBER_OF", target: "location.wang_family_bend", note: "bao head" }], simulationHooks: ["economy","social","aging"], version: "0.1.0" },
  { id: "npc.lady_wang_lin", kind: "npc_role", name: "Lady Wang", nameHanzi: "王氏", tags: ["carpenter_household","shouzheng_niece","weaver","mortal"], description: "Lin Aqiao's wife (35), a Wang who married out — Wang Shouzheng's niece.", source: "doc 34 §1.1, doc 04 §2.2", relations: [{ type: "SPOUSE_OF", target: "npc.lin_aqiao" }, { type: "NIECE_OF", target: "npc.wang_shouzheng" }], simulationHooks: ["social","economy","aging"], version: "0.1.0" },
  { id: "npc.widow_xu", kind: "npc_role", name: "Widow Xu", nameHanzi: "許寡婦", tags: ["widow","non_wang","mortal","missing_son"], description: "A non-Wang widow (61) whose husband and two older sons are dead; she survives by weaving, her dryland garden, and the lineage's charity. Her only surviving son Xu Erniu has been missing for three days.", source: "doc 34 §1.1, doc 04 §2.2", relations: [{ type: "PARENT_OF", target: "npc.xu_erniu" }], simulationHooks: ["social","economy","aging","disease"], version: "0.1.0" },
  { id: "npc.xu_erniu", kind: "npc_role", name: "Xu Erniu", nameHanzi: "許二牛", tags: ["missing","day_laborer","mortal"], description: "Widow Xu's only surviving son (19), unseen for three days after leaving to cut firewood in the Cangwu foothills; he found a cave entrance sealed by a crumbled stone, entered a cultivator's cache, and is trapped inside, unconscious but alive, his qi slowly drained by the cache's maintenance system.", source: "doc 28 §2.2, doc 34 §1.1", relations: [{ type: "CHILD_OF", target: "npc.widow_xu" }], simulationHooks: ["social","perception"], version: "0.1.0" },

  // === Newly-named households (6-15) ===
  { id: "npc.zhou_wenshu", kind: "npc_role", name: "Zhou Wenshu", nameHanzi: "周文淑", tags: ["midwife","folk_healer","story_teller","non_wang","widow"], description: "Called Zhou Popo (周婆婆, 'Old Lady Zhou') by the village — a non-Wang widow of 66, the midwife, folk-healer, and story-teller who birthed the Senior Household's children and most of the village; sharp-tongued and warm-hearted, she keeps a silk bag of dried umbilical cords, one per child she has birthed, as her anchor of memory.", source: "doc 34 §1.2, doc 04 §7.1", relations: [{ type: "COMPANION_OF", target: "npc.widow_xu", note: "birthed Xu Erniu, grieves him as a grandson, visits Widow Xu nightly" }], simulationHooks: ["reproduction","ritual","social","disease","aging"], version: "0.1.0" },
  { id: "npc.he_laosan", kind: "npc_role", name: "He Laosan", nameHanzi: "何老三", tags: ["ferryman","boatman","non_wang","dock"], description: "The ferryman and boatman (45), born in Qinghe Market Town; garrulous, canny, quietly observant, he knows everyone's business because he ferries them. He ferried the yamen runner to the village and saw the silk-wrapped gift; he also ferried a stranger upriver the night Xu Erniu disappeared.", source: "doc 34 §1.2", relations: [{ type: "INDEBTED_TO", target: "npc.wang_shouzheng", note: "free passage for lineage business in exchange for winter firewood" }], simulationHooks: ["trade","economy","social","migration","aging"], version: "0.1.0" },
  { id: "npc.wu_daniu", kind: "npc_role", name: "Wu Daniu", nameHanzi: "吳大牛", tags: ["charcoal_burner","non_wang","foothills"], description: "The charcoal-burner (50), born in the Cangwu foothills; taciturn and superstitious, with permanently black-stained hands and a burn scar from the kiln collapse that killed his younger brother. He cut the trail past Black Creek where Erniu's axe was found, and has heard a low hum, like a bell struck underground, from beast territory.", source: "doc 34 §1.2", relations: [{ type: "ALLY_OF", target: "npc.wang_shouzheng", note: "keeps eyes on the foothills in exchange for the lineage's protection" }], simulationHooks: ["economy","trade","ecology","aging"], version: "0.1.0" },
  { id: "npc.zhao_tieniu", kind: "npc_role", name: "Zhao Tieniu", nameHanzi: "趙鐵牛", tags: ["returned_soldier","night_watchman","non_wang","veteran"], description: "A returned soldier (40) and the village night watchman, born in Wang Family Bend; he returned last year with a small pension, a permanent limp from a horse archer's arrow, and the village's only firsthand knowledge of the world beyond the Cangli Riverlands. His wife waited 15 years for him.", source: "doc 34 §1.2", relations: [], simulationHooks: ["social","aging","disease","combat"], version: "0.1.0" },
  { id: "npc.li_asheng", kind: "npc_role", name: "Li Asheng", nameHanzi: "李阿勝", tags: ["yeoman_farmer","non_wang","literate","landowner"], description: "A non-Wang yeoman farmer (55) whose family has held its land for four generations — predating the Wang settlement; the only householder in the village who owns printed books and can read, he is also the only villager who could plausibly bid for the salt license himself, though he has not.", source: "doc 34 §1.2", relations: [{ type: "ALLY_OF", target: "npc.wang_shouzheng", note: "the only non-Wang Shouzheng treats as a peer; they drink together at the New Year" }], simulationHooks: ["economy","trade","social","aging"], version: "0.1.0" },
  { id: "npc.wang_shoucheng", kind: "npc_role", name: "Wang Shoucheng", nameHanzi: "王守誠", tags: ["tenant_farmer","fisherman","cousin_branch"], description: "Head of the Wang Second Tenant Household (52), a cousin of Shouzheng and Shouye in the same generation; the village's best fisherman, secretive and river-superstitious, who fishes out of season when the household needs food and hides it. He was fishing at Black Creek the morning Erniu's axe was found.", source: "doc 34 §1.2", relations: [{ type: "COUSIN_OF", target: "npc.wang_shouzheng" }, { type: "COUSIN_OF", target: "npc.wang_shouye" }], simulationHooks: ["economy","ecology","social","aging","trade"], version: "0.1.0" },
  { id: "npc.wang_tianfu", kind: "npc_role", name: "Wang Tianfu", nameHanzi: "王天福", tags: ["bare_stick_household","widower","elder_cousin_branch"], description: "The oldest living male of the senior-generation cousin-branch (62), a widower; Shouzheng's older half-brother, whose household of bachelor sons survives on day labor, dryland produce, and the Senior Household's charity. The resentment of his lower-status mother's inheritance is a 40-year silence.", source: "doc 34 §1.2", relations: [{ type: "HALF_SIBLING_OF", target: "npc.wang_shouzheng" }, { type: "PARENT_OF", target: "npc.wang_zongbao" }], simulationHooks: ["social","economy","aging"], version: "0.1.0" },
  { id: "npc.wang_zongbao", kind: "npc_role", name: "Wang Zongbao", nameHanzi: "王宗寶", tags: ["gravedigger","day_laborer","bachelor"], description: "A bachelor day laborer (28) and the village gravedigger, who has dug every grave in the graveyard for ten years — including Wang Xiaodi's — and speaks little; he is the one who, unbidden, weeds Wang Xiaodi's unmarked mound when Lady Chen is not there.", source: "doc 34 §1.2", relations: [{ type: "CHILD_OF", target: "npc.wang_tianfu" }, { type: "MEMBER_OF", target: "location.wang_family_bend", note: "village gravedigger" }], simulationHooks: ["social","ritual","aging"], version: "0.1.0" },
  { id: "npc.wang_lun", kind: "npc_role", name: "Wang Lun", nameHanzi: "王倫", tags: ["school_teacher","diviner","failed_exam_candidate","historian"], description: "The lineage school teacher (41) and the village's diviner, a failed county exam candidate (three attempts, three failures) who holds the post as a lineage obligation; melancholic and precise, he writes a 200-page history of the Cangli Riverlands at night by candlelight, shown to no one, and he cast the hexagram that sends the protagonist to Old Chen.", source: "doc 28 §3.3, doc 34 §1.2", relations: [{ type: "COUSIN_OF", target: "npc.wang_shouzheng" }, { type: "CHILD_OF", target: "npc.lady_tang" }], simulationHooks: ["social","ritual","history","aging","disease"], version: "0.1.0" },
  { id: "npc.lady_tang", kind: "npc_role", name: "Lady Tang", nameHanzi: "唐氏", tags: ["mother","elderly","school_household"], description: "Wang Lun's aging mother (72), who lives with him in the lineage school's side room; she has read his hidden history manuscript and tells no one.", source: "doc 34 §1.2", relations: [{ type: "PARENT_OF", target: "npc.wang_lun" }], simulationHooks: ["social","aging","disease"], version: "0.1.0" },
  { id: "npc.wang_shouli", kind: "npc_role", name: "Wang Shouli", nameHanzi: "王守禮", tags: ["lineage_elder","second_branch","farmer"], description: "Wang Shouzheng's younger brother (56), a middling farmer and the fourth seat on the elder council; stubborn, proud, quick to judge, he formally disowned his daughter Wang Meili when she went to the Cangwu Sect without his blessing, and he distrusts Old Chen over a false rumor about his failed Foundation Establishment.", source: "doc 34 §1.2", relations: [{ type: "SIBLING_OF", target: "npc.wang_shouzheng" }, { type: "PARENT_OF", target: "npc.wang_meili" }], simulationHooks: ["social","politics","economy","aging"], version: "0.1.0" },
  { id: "npc.pan_siniang", kind: "npc_role", name: "Pan Siniang", nameHanzi: "潘四娘", tags: ["tofu_maker","widow","pan_wang_household"], description: "The village's only tofu-maker (48), a non-Wang widow who returned to her natal Pan surname after her husband's death and won recognition of her household as neither Wang nor non-Wang — the only woman in the village to have publicly defied the lineage council and won. She buys salt from Master Hu on credit, and leaves tofu at Widow Xu's gate every morning in the Pan-family practice of mourning-with-the-widow.", source: "doc 34 §1.2", relations: [], simulationHooks: ["economy","trade","social","aging"], version: "0.1.0" },
  { id: "npc.yang_erhu", kind: "npc_role", name: "Yang Erhu", nameHanzi: "楊二虎", tags: ["butcher","village_edge","seed_parameters"], description: "The butcher at the village edge (38), named in the generator's seed-parameters but not appearing in the dramatic present of doc 28; he provides the funeral-pig and cattle-slaughter licenses. His daughter Yang Sanniu (7) is the same age Wang Xiaodi was when he died.", source: "doc 34 §1.3", relations: [], simulationHooks: ["economy","trade","social","aging"], version: "0.1.0" },

  // === Deceased and adjacent Wang family ===
  { id: "npc.wang_tianlu", kind: "npc_role", name: "Wang Tianlu", nameHanzi: "王天祿", tags: ["deceased","grandfather","former_head"], description: "The protagonist's grandfather and Wang Shouzheng's father, who died six years before game start of schistosomiasis; his tablet is in the lineage hall, and Shouzheng held his hand as it went cold.", source: "doc 28 §1, doc 04 §2.2", relations: [{ type: "PARENT_OF", target: "npc.wang_shouzheng" }], simulationHooks: ["history","disease","aging"], version: "0.1.0" },
  { id: "npc.wang_xiaodi", kind: "npc_role", name: "Wang Xiaodi", tags: ["deceased","sibling","unmarked_grave"], description: "The protagonist's younger brother, who died at 7 of a fever that took him in three days, two years before game start; buried in an unmarked grave — children's tablets are not installed — and his anchor was later harvested by Pei Liang.", source: "doc 28 §1, doc 46 §3", relations: [{ type: "CHILD_OF", target: "npc.wang_shouzheng" }, { type: "CHILD_OF", target: "npc.lady_chen" }], simulationHooks: ["history","social"], version: "0.1.0" },
  { id: "npc.wang_tianming", kind: "npc_role", name: "Wang Tianming", nameHanzi: "王天明", tags: ["elder","oldest_resident","frail"], description: "The village's oldest resident (73), Shouzheng's uncle, frail but lucid; on the elder council he argues for waiting rather than sending men into beast territory in spring.", source: "doc 04 §7.1, doc 28 §4.4", relations: [{ type: "UNCLE_OF", target: "npc.wang_shouzheng" }], simulationHooks: ["social","aging","disease"], version: "0.1.0" },

  // === The hermitage ===
  { id: "npc.old_chen", kind: "npc_role", name: "Old Chen", nameHanzi: "陳老", tags: ["hermit","teacher","qi_condensation_peak","failed_foundation_establishment"], description: "The hermit above Li Family Creek (82), the protagonist's teacher; he sealed the cultivator's cache that Xu Erniu stumbled into, 40 years ago, when he was still a roaming cultivator. His failed Foundation Establishment left him at Qi Condensation peak with meridian damage that will never carry qi again; he wants the player to succeed for the path's sake.", source: "doc 28 §3.5, doc 34 §4.2", relations: [{ type: "SPOUSE_OF", target: "npc.lady_chen_hermitage" }], simulationHooks: ["cultivation","perception","aging","ritual","deviation"], version: "0.1.0" },
  { id: "npc.lady_chen_hermitage", kind: "npc_role", name: "Lady Chen of the Hermitage", tags: ["deceased","hermitage","old_chen_wife"], description: "Old Chen's wife, a different Lady Chen from the protagonist's mother — a coincidence of surname; the two women are not related. She died years before at ~105, and her death was the second great grief of Old Chen's long life, after his failed Foundation Establishment.", source: "doc 34 §0, doc 34 §4.2", relations: [{ type: "SPOUSE_OF", target: "npc.old_chen" }], simulationHooks: ["aging","disease","social"], version: "0.1.0" },

  // === The three companions ===
  { id: "npc.wang_meili", kind: "npc_role", name: "Wang Meili", nameHanzi: "王美麗", tags: ["companion","healer","cangwu_sect","second_branch","cultivator"], description: "Wang Shouli's disowned daughter (22 at introduction), the lineage bridge and the protagonist's first disciple: she perceived qi at 14 — a year before the protagonist — taught herself from stolen manuals, walked 100 li to the Cangwu Sect at 19, and joins the protagonist's circle in Act 2 as a Qi Condensation healer-track cultivator. She wants to be the Wang lineage's first cultivator-healer, present at the bedside of the dying.", source: "doc 34 §2.1", relations: [{ type: "CHILD_OF", target: "npc.wang_shouli" }, { type: "COMPANION_OF", target: "npc.liang_zhu", note: "bond over shared fondness for woodwinds; she plays the qin" }, { type: "COMPANION_OF", target: "npc.leng_qingxue", note: "intimidated at first, then allies" }, { type: "MEMBER_OF", target: "location.cangwu_sect", note: "healer-track disciple" }, { type: "AT_REALM", target: "realm.qi_induction", note: "at introduction" }, { type: "AT_REALM", target: "realm.foundation_establishment", note: "by Act 3, if she survives" }], simulationHooks: ["cultivation","combat","social","history","aging","disease"], version: "0.1.0" },
  { id: "npc.liang_zhu", kind: "npc_role", name: "Liang Zhu", nameHanzi: "梁柱", tags: ["companion","rogue_cultivator","foundation_establishment","xiao_player"], description: "A Foundation Establishment (peak) rogue cultivator (~80 at introduction, appears ~40), the protagonist's first peer and friend outside the sect and village: exiled by the Azure Sword Sect for complicity by silence — he knew of his sect master's anchor-harvesting for five years before reporting it. Irreverent, kind, weary, he plays the xiao beautifully; he dies at session ~800 delaying Pei Liang, his final note a qi-residue teaching.", source: "doc 34 §2.2", relations: [{ type: "COMPANION_OF", target: "npc.wang_meili" }, { type: "COMPANION_OF", target: "npc.leng_qingxue" }, { type: "AT_REALM", target: "realm.foundation_establishment", note: "peak; has not attempted Core Formation in 30 years" }], simulationHooks: ["cultivation","combat","audio","social","history","migration"], version: "0.1.0" },
  { id: "npc.leng_qingxue", kind: "npc_role", name: "Leng Qingxue", nameHanzi: "冷清雪", tags: ["companion","sword_cultivator","azure_sword_sect","core_formation","romance"], description: "The Azure Sword Sect master's only daughter (Core Formation, ~120 at introduction, appears ~30), the sect's heir apparent who publicly opposes her mother's expansion toward the Cangli Riverlands; precise and cold in manner, warm in private, she joins the protagonist as an observer and stays as an ally, the romance expressed through the Exchange of Cuts (交劍).", source: "doc 34 §2.3", relations: [{ type: "CHILD_OF", target: "npc.leng_wushuang" }, { type: "COMPANION_OF", target: "npc.wang_meili" }, { type: "COMPANION_OF", target: "npc.liang_zhu" }, { type: "ALLY_OF", target: "npc.xu_yunfeng", note: "30 years of political correspondence, not romantic" }, { type: "AT_REALM", target: "realm.core_formation", note: "mid-stage; broke through at 80" }], simulationHooks: ["cultivation","combat","social","politics","ritual","history"], version: "0.1.0" },
  { id: "npc.leng_wushuang", kind: "npc_role", name: "Leng Wushuang", nameHanzi: "冷無霜", tags: ["sect_master","azure_sword_sect","core_formation","expansionist"], description: "Master of the Azure Sword Sect (Core Formation, 340), Leng Qingxue's mother, whose quiet expansion toward the Cangli Riverlands to claim the latent spirit vein beneath the Cangwu Mountains her daughter publicly opposes; Leng Qingxue believes the expansion is, at root, an 80-year act of mourning for a husband who died on a vein survey mission.", source: "doc 34 §2.3", relations: [{ type: "PARENT_OF", target: "npc.leng_qingxue" }], simulationHooks: ["politics","cultivation","combat","history","social"], version: "0.1.0" },
  { id: "npc.xu_yunfeng", kind: "npc_role", name: "Xu Yunfeng", nameHanzi: "許雲峰", tags: ["jade_void_holy_land","core_formation","coalition"], description: "A Core Formation cultivator of the Jade Void Holy Land (200) with whom Leng Qingxue has corresponded for 30 years, quietly building a coalition to oppose both the Azure Sword expansion and the Jade Void counter-claim, proposing a regional compact leaving the Cangwu Mountains' spirit vein under the Cangwu Sect's stewardship.", source: "doc 34 §2.3", relations: [{ type: "ALLY_OF", target: "npc.leng_qingxue", note: "the only person outside the Cangli Riverlands who knows the full shape of her dissent" }], simulationHooks: ["politics","cultivation","social"], version: "0.1.0" },

  // === The antagonist ===
  { id: "npc.pei_liang", kind: "npc_role", name: "Pei Liang", nameHanzi: "裴良", tags: ["antagonist","anchor_harvest","nascent_soul","third_generation"], description: "The antagonist, born 180 years before game start; calm, courteous, and completely convinced that what he does is right, he has harvested ~200 anchors over 40 years — Qi Condensation at 25, Foundation Establishment at 50, Core Formation at 95, Nascent Soul at 150, attempting Spirit Severance at the final confrontation. He wants to author a domain where anchor-harvesting is lawful and his son's anchor can be restored; he is wrong that it is possible.", source: "doc 34 §3.1, §3.2", relations: [{ type: "PARENT_OF", target: "npc.pei_an" }, { type: "INHERITOR_OF", target: "npc.zhou_wugui", note: "third-generation inheritor of the anchor-harvesting technique" }, { type: "STUDENT_OF", target: "npc.daoist_iron_bamboo" }, { type: "AT_REALM", target: "realm.nascent_soul", note: "at game start; Spirit Severance attempted at the final confrontation" }], simulationHooks: ["cultivation","combat","deviation","history","politics"], version: "0.1.0" },
  { id: "npc.pei_an", kind: "npc_role", name: "Pei An", nameHanzi: "裴安", tags: ["deceased","son","foundation_establishment"], description: "Pei Liang's only child, a Foundation Establishment cultivator who died in a law tribulation 50 years before game start; his father harvested his anchor at the moment of death and has kept it in the harvest-store for 50 years, speaking to it every night — the anchor is not conscious, as Pei Liang believes.", source: "doc 34 §3.2", relations: [{ type: "CHILD_OF", target: "npc.pei_liang" }], simulationHooks: ["cultivation","deviation","history"], version: "0.1.0" },
  { id: "npc.daoist_iron_bamboo", kind: "npc_role", name: "Daoist Iron Bamboo", nameHanzi: "鐵竹道人", tags: ["sect_master","iron_bamboo_sect","foundation_establishment","deceased"], description: "Sect master of the Iron Bamboo Sect (鐵竹派), Foundation Establishment, who died at 110 when Pei Liang was 60; the sect had no political ambition and was dissolved 80 years ago after his death, its disciples scattered. Pei Liang discovered his anchor-harvesting at 45 and reported it at 50.", source: "doc 34 §3.1", relations: [{ type: "TEACHER_OF", target: "npc.pei_liang" }], simulationHooks: ["cultivation","history","deviation"], version: "0.1.0" },
  { id: "npc.zhou_wugui", kind: "npc_role", name: "Zhou Wugui", nameHanzi: "周無鬼", tags: ["demonic_cultivator","first_generation","deceased","harvest_technique"], description: "The first-generation demonic cultivator of the anchor-harvesting line, killed 95 years ago by the Azure Sword Sect's previous sect master after harvesting three Cangwu foothills villages to fuel a breakthrough attempt; a single page of his harvest-manual survived in a floorboard and became Pei Liang's technique.", source: "doc 34 §3.6", relations: [], simulationHooks: ["deviation","history","combat"], version: "0.1.0" },
  { id: "npc.a_qing", kind: "npc_role", name: "A-Qing", nameHanzi: "阿青", tags: ["deceased","child","mortal","grief"], description: "A mortal girl of 6, the daughter of the Iron Bamboo Sect's herb-gatherer, whose anchor was half-harvested by Liang Zhu's sect master; Liang Zhu had taught her to read, and he has played the xiao for her every year on the anniversary of her death for 30 years.", source: "doc 34 §2.2", relations: [], simulationHooks: ["history","deviation"], version: "0.1.0" },
  { id: "npc.scribe_yan", kind: "npc_role", name: "Scribe Yan", nameHanzi: "閻", tags: ["precelestial_official","corrupt","bardo_harvest"], description: "A corrupt Precelestial official who unlawfully delays the bardo dispersal of the recently dead and offers 'extended window' anchors to Pei Liang, making the anchor-harvest lawful-seeming; his falsified-dispersal signature registers as wrongness to the protagonist's Residual Error Sense.", source: "doc 34 §3.1, doc 46 §4.2", relations: [{ type: "MEMBER_OF", target: "npc.yan_wugui", note: "living cultivator of the Yan clan, one of three named alongside Yan Jue and Yan Qingshi" }], simulationHooks: ["politics","trade","ritual","history"], version: "0.1.0" },

  // === Regional cultivators ===
  { id: "npc.wu_changqing", kind: "npc_role", name: "Wu Changqing", tags: ["sect_master","cangwu_sect","qi_condensation"], description: "The Cangwu Sect's master, a Qi Condensation cultivator who has never been to the Precelestial; his lesson on sect history is how the protagonist first mishears 'consulted the ancestors' and receives a partial, partly-wrong account of ancestral courts.", source: "doc 46 §6, doc 24 §4.3", relations: [{ type: "MEMBER_OF", target: "location.cangwu_sect", note: "sect master" }, { type: "AT_REALM", target: "realm.qi_condensation", note: "peak" }], simulationHooks: ["cultivation","social","history"], version: "0.1.0" },

  // === The ten great ancestral courts: founders and figures (doc 46) ===
  { id: "npc.yan_wugui", kind: "npc_role", name: "Yan Wugui", nameHanzi: "閻無歸", tags: ["court_founder","persistent_ancestor","yan_court","diviner_anchor"], description: "Founding ancestor of the Yan Ancestral Court (閻氏宗祠), 'Yan the Uncalculated': Spirit Severance at death, 1,150, died Year ~38,800. A diviner-anchor cultivator who developed the lineage-retrieval rite's precursor, for which the Yan clan has been paid Records-department posts for nine millennia; over the last millennium his counsel has drifted — sovereignty-maximalizing, dismissive of the courts' jurisdiction — a corruption the lineage does not recognize.", source: "doc 46 §2.1, §4.2", relations: [{ type: "PROGENITOR_OF", target: "npc.yan_qingshi", note: "founding ancestor of the Yan clan" }], simulationHooks: ["history","politics","ritual","cultivation","deviation"], version: "0.1.0" },
  { id: "npc.pillar_lord_first_sap", kind: "npc_role", name: "Pillar Lord of the First Sap", nameHanzi: "初汁柱", tags: ["court_founder","yao_mahayana","pillar_dynasty","dormant"], description: "Founding ancestor of the Pillar Court (柱祠), 'First Sap of the Pillar': yao-Mahayana at death, ~6,000, died Year ~22,000. Founder of the Pillar Dynasty, the wood-phase yao civilization that flourished for eight thousand years before its vein system exhausted; he now persists only as a residue-trace in a dormant court with no living lineage.", source: "doc 46 §2.2", relations: [], simulationHooks: ["history","cultivation","ecology"], version: "0.1.0" },
  { id: "npc.daoist_silent_hexagram", kind: "npc_role", name: "Daoist Silent Hexagram", nameHanzi: "默卦真人", tags: ["court_founder","corrupted","sealed","diviner"], description: "Founding ancestor of the Silent Hexagram Court (默卦宗祠): Nascent Soul at bodily death, 612, died Year ~43,000. A diviner whose Silent Hexagram Method achieved unprecedented accuracy; after 2,500 years his divination-law inverted — he perceives all possible futures and seeks to collapse them into the one in which he persists — and he is sealed in his own law, inverted, with ~1,500 years of estimated integrity remaining.", source: "doc 46 §2.3, §4.1", relations: [], simulationHooks: ["history","ritual","deviation","perception"], version: "0.1.0" },
  { id: "npc.daojun_chiri", kind: "npc_role", name: "Daojun Chiri", nameHanzi: "赤日道君", tags: ["court_founder","mahayana","crimson_vow","deceased"], description: "Founding Mahayana of the Crimson Vow Alliance (赤誓宗祠's founder), 'the Lord of the Red Sun': age 4,200, died Year ~43,000. She died in a law-tribulation fired by her own law-amendment that touched the founding compact's lineage-jurisdiction clause; her anchor dispersed and the court persists without her, sustained by the Crimson Vow Remnant's residual veneration.", source: "doc 46 §2.4", relations: [], simulationHooks: ["history","politics","cultivation","deviation"], version: "0.1.0" },
  { id: "npc.daojun_yingzao", kind: "npc_role", name: "Daojun Yingzao", nameHanzi: "營造道君", tags: ["court_founder","tribulation_crossing","builder","deceased"], description: "Founding ancestor of the Builder's Court (營造之祠), 'the Lord of Construction': Tribulation Crossing at death, 3,800, died Year ~39,500. His architectural qi-inscription methods built the Garth of Roads, and his court is the largest of the ten great courts, structured as seven concentric halls; he was the teacher of Fan Xuan's teacher.", source: "doc 46 §2.6", relations: [{ type: "PROGENITOR_OF", target: "npc.fan_xuan", note: "founder of the Builder's Lineage; Fan Xuan is its third Mahayana" }], simulationHooks: ["history","ritual","cultivation"], version: "0.1.0" },
  { id: "npc.daoist_muyuan", kind: "npc_role", name: "Daoist Muyuan", nameHanzi: "木園真人", tags: ["court_founder","spirit_severance","garden_court","herb_cultivation"], description: "Founding ancestor of the Garden Court (園祠), 'Master of the Wood Garden': Spirit Severance at death, 2,100, died Year ~36,000. His qi-cultivation technique for spirit herbs sustains grotto-heaven herb gardens across millennia; the court is a single grove whose trees are the persistent ancestors' anchors, with his oldest tree at the center.", source: "doc 46 §2.7", relations: [{ type: "TEACHER_OF", target: "npc.yin_mu" }], simulationHooks: ["cultivation","ecology","history","ritual"], version: "0.1.0" },
  { id: "npc.tu_nan", kind: "npc_role", name: "Tu Nan", nameHanzi: "圖南", tags: ["mahayana","cartographer","living","map_grotto"], description: "Founder and senior cultivator of the Cartographer's Lineage (圖南氏), 'Map of the South': Mahayana, still living. He founded the court (圖南之祠) for his teacher — a Spirit Severance cultivator who died at his breakthrough's eve, whose name is written but not spoken aloud — and visits annually for the map-update pilgrimage; his posture is observe, record, do not intervene.", source: "doc 46 §2.8", relations: [], simulationHooks: ["history","cultivation","migration","trade"], version: "0.1.0" },
  { id: "npc.daoist_beiyin", kind: "npc_role", name: "Daoist Beiyin", nameHanzi: "北音真人", tags: ["court_founder","spirit_severance","mourner","deceased"], description: "Founding ancestor of the Mourner's Court (懷哀之祠), 'Master of the Northern Sound': Spirit Severance at death, 1,800, died Year ~38,500. His mourning-practice — attending the dying — was refined by his student into the painless dispersal law; his court is a plain hall whose walls bear the names of every being attended in dispersal.", source: "doc 46 §2.9", relations: [{ type: "TEACHER_OF", target: "npc.bei_huai" }], simulationHooks: ["history","ritual","aging"], version: "0.1.0" },
  { id: "npc.daojun_luocheng", kind: "npc_role", name: "Daojun Luocheng", nameHanzi: "洛城道君", tags: ["court_founder","tribulation_crossing","judge","deceased"], description: "Founding ancestor of the Judge's Court (律深之祠), 'the Lord of the Falling City': Tribulation Crossing at death, 4,100, died Year ~39,000. His jurisprudential technique let a Tribulation Crossing cultivator hear a dispute without being moved by either party's qi-pressure; his court is a single hexagonal chamber in the central Precelestial.", source: "doc 46 §2.10", relations: [{ type: "TEACHER_OF", target: "npc.lu_shen" }], simulationHooks: ["history","politics","ritual","cultivation"], version: "0.1.0" },
  { id: "npc.gu_wu", kind: "npc_role", name: "Gu Wu", tags: ["mahayana","first_court","law_author","bardo_window"], description: "A Mahayana cultivator, the sole living resident of the First Court (元祠, the Primordial Court) — the smallest of the ten great courts — which he sustains by his law-authority alone while maintaining the bardo-window law; the court was founded for his teacher, who deliberately erased his own name as a final practice of finitude, and Gu Wu's lineage is extinct.", source: "doc 46 §2.5", relations: [], simulationHooks: ["cultivation","history","ritual","politics"], version: "0.1.0" },
  { id: "npc.jing_wuyin", kind: "npc_role", name: "Jing Wuyin", tags: ["silent_hexagram_school","core_formation","sealer","deceased"], description: "The Silent Hexagram School's last Core Formation cultivator, who concluded the founder had corrupted and sealed him with the court's own law — the only known case of a single Core Formation cultivator sealing a corrupted Mahayana-tier ancestor; the sealing cost her life, draining her within fifty years, and the method is presumed lost.", source: "doc 46 §2.3, §4.1", relations: [{ type: "STUDENT_OF", target: "npc.daoist_silent_hexagram", note: "last cultivator of the Silent Hexagram School, which she dispersed in Year ~45,500" }], simulationHooks: ["cultivation","history","ritual","deviation"], version: "0.1.0" },
  { id: "npc.yan_qingshi", kind: "npc_role", name: "Yan Qingshi", tags: ["mahayana","councilor","yan_clan","conservative_bloc"], description: "The Yan clan's most recent Mahayana and a Council-seated councilor who votes the Lineage Bloc's program — one of the four Council-seated Mahayana (with Qiu Wuhen / Gu Wu, Shang Zhenkong, and Duan Mutian). As the Conservative Bloc's senior Mahayana, contesting the founding ancestor's drift would cost the bloc its senior seat and destabilize her records-integrity law.", source: "doc 46 §2.1, §4.2", relations: [{ type: "FAMILY_OF", target: "npc.yan_wugui", note: "clan descendant of the founding ancestor" }], simulationHooks: ["politics","cultivation","history","social"], version: "0.1.0" },
  { id: "npc.yin_mu", kind: "npc_role", name: "Yin Mu", tags: ["mahayana","gardener","garden_holy_land","grotto_heaven"], description: "The Garden Lineage's second Mahayana, 'the Gardener': her grotto-heaven in the Cangwu Mountains' deep Precelestial is a wood-phase grotto with a 1:5 time-rate sustaining 10,000-year herbs, and she tends the Garden Court's grove as part of her daily practice.", source: "doc 46 §2.7", relations: [{ type: "STUDENT_OF", target: "npc.daoist_muyuan" }], simulationHooks: ["cultivation","ecology","history","economy"], version: "0.1.0" },
  { id: "npc.bei_huai", kind: "npc_role", name: "Bei Huai", tags: ["mahayana","mourner","painless_dispersal","wanderer"], description: "The Mourner's Lineage's only Mahayana, 'the Mourner', who attends the dying — on average one death per Acquired day across three thousand years, the walls of his teacher's court dense with a million names. He refined Beiyin's mourning-practice into the painless dispersal law, wanders the Mortal Stratum, and cannot bring himself to enter his teacher's court.", source: "doc 46 §2.9", relations: [{ type: "STUDENT_OF", target: "npc.daoist_beiyin" }], simulationHooks: ["ritual","aging","social","history"], version: "0.1.0" },
  { id: "npc.lu_shen", kind: "npc_role", name: "Lu Shen", tags: ["mahayana","judge","tribulation_trigger_law"], description: "The Judge's Lineage's only Mahayana, 'the Judge', who refined Luocheng's jurisprudential technique into the tribulation-trigger law; he visits his teacher's anchor twice per year between Adjudication hearings, maintaining the inscription of the law on the court's walls.", source: "doc 46 §2.10", relations: [{ type: "STUDENT_OF", target: "npc.daojun_luocheng" }], simulationHooks: ["politics","cultivation","history","ritual"], version: "0.1.0" },
  { id: "npc.fan_xuan", kind: "npc_role", name: "Fan Xuan", tags: ["mahayana","builder","council_seat"], description: "The Builder's Lineage's third Mahayana, 'the Builder', who sits in the Council and visits the Builder's Court once per Precelestial year; the Azure Sword Sect's scripture hall was designed after a Builder's Court consultation three hundred years ago.", source: "doc 46 §2.6", relations: [], simulationHooks: ["politics","cultivation","history","economy"], version: "0.1.0" },
];
