/**
 * Place / sect / location definitions extracted from the corpus-extension docs:
 * doc 04 (Mortal Substrate), doc 12 (Sect Institutions), doc 31 (Named Institutions),
 * doc 42 (Mortal World's Continents), doc 43 (Holy Lands and Great Sects), doc 36 (Cosmic Geography).
 *
 * Only places, sects, regions, and features NAMED in the docs. Descriptions are faithful
 * condensed paraphrases; no numbers are invented. Hanzi are given exactly as in the corpus.
 * Where the corpus itself names the same institution differently across docs (e.g. the
 * Azure Sword Sect's three veins in doc 31 vs doc 43), the divergence is recorded in the
 * description rather than resolved by invention.
 */
import type { Definition } from '../definitions';

export const PLACE_DEFINITIONS: Definition[] = [
  // ============================ REGIONS ============================

  {
    id: "region.cangli_riverlands",
    kind: "location",
    name: "Cangli Riverlands",
    nameHanzi: "沧篱江乡",
    tags: ["mortal","starting","backwater","wet_rice","coastal_plain"],
    description: "The protagonist's home region and the player's starting ground: a wet-rice lowland basin roughly 120 km north-south by 60 km east-west on the lower reaches of the Cangli River (沧篱江), flowing east to the sea through a coastal plain backed by the Cangwu Mountains (1-3 km relief), in Qingzhou Prefecture (青州府), Jiangnan Province (江南省), on the Central Continent's eastern coast. Subtropical monsoon climate with a plum-rain season. The seven villages of the lower watershed form the Bend Township (彎鄉, ~1200 souls); Wang Family Bend (~180) is one. A backwater: low qi-density, one small sect (the Cangwu Sect, 100 li west), one great sect in reach (the Azure Sword Sect, 500 li north). Named places: Wang Family Bend, Li Family Creek, Qinghe Market Town, Cangli County Seat, Qingzhou Prefectural Seat. The Jade Void Holy Land's founder was born here 2,100 years ago.",
    source: "doc 04 §0-1, doc 42 §1.2, doc 36 §9.1",
    relations: [
      { type: "PART_OF", target: "region.zhong" },
      { type: "CONTAINS", target: "location.wang_family_bend" },
      { type: "CONTAINS", target: "place.li_family_creek" },
      { type: "CONTAINS", target: "place.qinghe_market_town" },
      { type: "CONTAINS", target: "location.cangwu_sect" },
    ],
    simulationHooks: ["economy","social","ecology","weather","disease","trade","history","migration"],
    version: "0.1.0",
  },
  {
    id: "region.zhong",
    kind: "location",
    name: "Central Continent",
    nameHanzi: "中洲",
    tags: ["continent","central","qi_dense","starting"],
    description: "The largest continent and the most qi-dense; the cosmic center of the Mortal Stratum's horizontal extent lies beneath it. Home of the Great Yan Dynasty (大燕朝); the Cangli Riverlands is on its eastern coast where the Cangli River empties into the Eastern Sea. Western interior dry, mountainous, sparsely populated (the oasis city Yumen at the Western Ocean's coast); eastern and southern coasts wet-rice lowland. East-west extent ~12,000 li. One holy land (the Yellow Court, the only one on Zhong); great sects include the Heavenly Pivot, Sand-Veiled, Pearl-Tide, Iron-Horse, and Azure Sword.",
    source: "doc 42 §1, doc 36 §2.5, doc 36 §6.2",
    relations: [
      { type: "CONTAINS", target: "region.cangli_riverlands" },
      { type: "CONTAINS", target: "institution.great_yan" },
      { type: "CONTAINS", target: "sect.yellow_court" },
      { type: "CONTAINS", target: "sect.azure_sword" },
      { type: "CONTAINS", target: "sect.heavenly_pivot" },
      { type: "CONTAINS", target: "sect.sand_veiled" },
      { type: "CONTAINS", target: "sect.pearl_tide" },
      { type: "CONTAINS", target: "sect.iron_horse" },
      { type: "PART_OF", target: "cosmological.mortal_world" },
    ],
    simulationHooks: ["ecology","economy","politics","history","trade","migration"],
    version: "0.1.0",
  },
  {
    id: "region.dong",
    kind: "location",
    name: "Eastern Continent",
    nameHanzi: "東洲",
    tags: ["continent","wood_phase","alchemical_center"],
    description: "The eastern continent, across the Eastern Sea ~30,000 li east of Zhong's coast (two months by mortal sail, a day by Core Formation flight). Smaller than Zhong but with higher Acquired-stratum qi-density; wood-phase qi dominant; wetter and lusher, with shallow wood-phase spirit veins surfacing frequently, producing the dense spirit-herb ecology that makes Dong the cultivation world's alchemical center. Mortal population smaller than Zhong's; cultivator-to-mortal ratio the highest of the five continents. The Yueling Dynasty (月菱朝) rules the central lowlands; the Jade Void Holy Land is Dong's — and the cultivation world's — most influential holy land. Great sects: the Emerald Pagoda, Whale-Rider, and Azuremist.",
    source: "doc 42 §2.1-2.3, doc 36 §2.5",
    relations: [
      { type: "CONTAINS", target: "institution.yueling_dynasty" },
      { type: "CONTAINS", target: "sect.jade_void" },
      { type: "CONTAINS", target: "sect.emerald_pagoda" },
      { type: "CONTAINS", target: "sect.whale_rider" },
      { type: "CONTAINS", target: "sect.azuremist" },
      { type: "PART_OF", target: "cosmological.mortal_world" },
    ],
    simulationHooks: ["ecology","economy","politics","trade","cultivation","migration"],
    version: "0.1.0",
  },
  {
    id: "region.xi",
    kind: "location",
    name: "Western Continent",
    nameHanzi: "西洲",
    tags: ["continent","metal_phase","high_plateau"],
    description: "The western continent, across the Western Ocean beyond Zhong's western deserts (~25,000 li of open water, no mid-route archipelago; only Core Formation cultivators and the rare mortal fleet make the crossing). Dry, mountainous, metal-dominant; interior a high plateau of granite and iron-veined ranges; coast a narrow strip of Mediterranean-climate city-states. Spirit veins run deep and metal-dominant; qi sharp, cold, 'brittle' — powerful in bursts, hard to sustain. Few Zhong mortals have heard of it. The Ironbone Confederacy (鐵骨盟) is its political structure; the Skyfire Holy Land is its leading holy land; great sects the Ironbone and the Stone Lantern. The Western Spirit Wilds above Xi are where the most Law Reaches are found; the Law Reaches' resonance bleeds down into the continent's metal-phase qi.",
    source: "doc 42 §3.1, doc 36 §2.5, doc 36 §9.2",
    relations: [
      { type: "CONTAINS", target: "institution.ironbone_confederacy" },
      { type: "CONTAINS", target: "sect.skyfire" },
      { type: "CONTAINS", target: "sect.ironbone" },
      { type: "CONTAINS", target: "sect.stone_lantern" },
      { type: "PART_OF", target: "cosmological.mortal_world" },
    ],
    simulationHooks: ["ecology","economy","politics","trade","cultivation"],
    version: "0.1.0",
  },
  {
    id: "region.nan",
    kind: "location",
    name: "Southern Continent",
    nameHanzi: "南洲",
    tags: ["continent","tropical","archipelagic","yao_dense"],
    description: "The southern continent: tropical, archipelagic, monsoon-rotated; qi wood-dominant and water-dominant. Coast dense with mortal settlement; interior dense primary jungle broken by the central highlands' dry grasslands (where ruins preserve well). Spirit veins shallow and wood-dominant along the coasts; the central highlands' deep veins earth-wood dual-phase. The Mortal Stratum's most yao-dense continent — the Pillar Dynasty's yao-civilization flourished here and its dispersed descendants (the Pillar Descendants, 柱裔) still live in the jungle interior. No single empire: the Monsoon Cities (季風諸城) on the coast, the Verdant Pillar Holy Land (the only yao-co-founded holy land) on the central highlands; great sects the Sea-Fan and the Redwood Canopy.",
    source: "doc 42 §4.1, doc 36 §2.5",
    relations: [
      { type: "CONTAINS", target: "institution.monsoon_cities" },
      { type: "CONTAINS", target: "sect.verdant_pillar" },
      { type: "CONTAINS", target: "sect.sea_fan" },
      { type: "CONTAINS", target: "sect.redwood_canopy" },
      { type: "PART_OF", target: "cosmological.mortal_world" },
    ],
    simulationHooks: ["ecology","economy","politics","trade","migration","social"],
    version: "0.1.0",
  },
  {
    id: "region.bei",
    kind: "location",
    name: "Northern Continent",
    nameHanzi: "北洲",
    tags: ["continent","subarctic","water_yin","nomadic"],
    description: "The northern continent: cold, subarctic, mostly uninhabitable by wet-rice agriculture; qi water-dominant and yin-dominant. Coast taiga; interior tundra and steppe broken by glacial mountain ranges. Spirit veins run cold and deep; qi dense but slow. Mortal population nomadic and pastoral (reindeer-herders, horse-riders, mammoth-bone-dwellers), culturally distinct from the wet-rice civilizations. The northern ancestral courts are the Precelestial's oldest; their resonance is felt in the continent's deep cold. The Black-Ice Khanate (黑冰汗國) unifies the central steppe; the NorthSea Holy Land is the oldest-patriarch holy land; great sects the Snowstrider and the Mammoth-Bone; the Frostfang Yao (霜牙妖) govern the deep tundra.",
    source: "doc 42 §5.1, doc 36 §2.5",
    relations: [
      { type: "CONTAINS", target: "institution.black_ice_khanate" },
      { type: "CONTAINS", target: "sect.northsea" },
      { type: "CONTAINS", target: "sect.snowstrider" },
      { type: "CONTAINS", target: "sect.mammoth_bone" },
      { type: "PART_OF", target: "cosmological.mortal_world" },
    ],
    simulationHooks: ["ecology","economy","politics","migration","social"],
    version: "0.1.0",
  },
  {
    id: "region.pearl_archipelago",
    kind: "location",
    name: "Pearl Archipelago",
    nameHanzi: "珠島群",
    tags: ["archipelago","neutral_ground","trade","route_midway"],
    description: "A chain of 340 cultivator-inhabited islands breaking the Eastern Sea at its midpoint between Zhong and Dong. The largest, Great Pearl Island (大珠島), is 80 li across; its harbor town Zhubu (珠埠) is the Vermilion Pearl Route's mid-way port and the cultivation world's largest neutral market — the only place where cultivators from all five continents regularly meet. Governed by the 1,400-year-old Pearl Archipelago Compact between the Pearl-Tide, Whale-Rider, and Crystal-Tide sects, which jointly maintain the spirit-beacon lighthouses marking the Route's channels. The Archipelago Crossing section of the Route runs Zhubu to Little Pearl Island (小珠島), the Route's safest stretch.",
    source: "doc 42 §6.1, §7.2",
    relations: [
      { type: "PART_OF", target: "cosmological.mortal_world" },
      { type: "CONTAINS", target: "sect.crystal_tide", note: "maintains the Archipelago's undersea defenses" },
    ],
    simulationHooks: ["trade","economy","politics","migration"],
    version: "0.1.0",
  },

  // ============================ PLACES ============================

  {
    id: "place.cangwu_mountains",
    kind: "location",
    name: "Cangwu Mountains",
    nameHanzi: "蒼梧山脈",
    tags: ["mountain_range","granitic","sect_home","qinzhou"],
    description: "A long granitic arc running roughly southwest to northeast through southern Qingzhou Prefecture, backing the Cangli Riverlands plain to the south and west; 1-3 km relief. The Cangwu Sect sits in the central spine (Cangwu Valley, ~1,400 m, 100 li west of Wang Family Bend); the Azure Sword Sect sits on Biluo Peak in the northern extension, 500 li north of the bend. Water-dominant in the range proper, wood-dominant in the foothills. The range's Acquired-stratum extension projects onto the Mortal night sky as the Cangwu Bow (蒼梧弓) constellation.",
    source: "doc 31 §1.1, doc 42 §1.2, doc 36 §2.3",
    relations: [
      { type: "CONTAINS", target: "place.cangwu_valley" },
      { type: "CONTAINS", target: "location.cangwu_sect" },
      { type: "CONTAINS", target: "sect.azure_sword", note: "Biluo Peak in the northern extension" },
      { type: "LOCATED_IN", target: "region.cangli_riverlands" },
    ],
    simulationHooks: ["ecology","cultivation","migration","perception"],
    version: "0.1.0",
  },
  {
    id: "place.cangwu_valley",
    kind: "location",
    name: "Cangwu Valley",
    nameHanzi: "蒼梧谷",
    tags: ["hanging_valley","sect_compound","elevation_1400"],
    description: "The hanging valley of the Cangwu Sect, in the Cangwu Mountains' central spine at ~1,400 m: roughly two li long and half a li wide, oriented east-west, walled on three sides by granite ridges and open on the east to a steep descent. Access is a single paved mule-track through the Stone Gate (石門), a natural cleft between two house-sized boulders. Stone Gate Creek (石門溪), fed by the Green Mirror Spring, crosses the valley floor. On the north wall, Holding Sun Cliff (抱陽崖) carries the scripture hall, the sect master's house, and the inner disciples' dormitories, with the Founder's Hall (祖師堂) at the top of a 211-step wooden stair.",
    source: "doc 31 §1.1",
    relations: [
      { type: "CONTAINS", target: "location.cangwu_sect" },
      { type: "CONTAINS", target: "vein.green_mirror", note: "surface trace in a cave on the western wall" },
      { type: "LOCATED_IN", target: "place.cangwu_mountains" },
    ],
    simulationHooks: ["cultivation","ecology","social","ritual"],
    version: "0.1.0",
  },
  {
    id: "place.li_family_creek",
    kind: "location",
    name: "Li Family Creek",
    nameHanzi: "李家溪",
    tags: ["village","mortal","neighbor_settlement"],
    description: "The next village east of Wang Family Bend, 4 li (~2 km) along the main path, in the lower Cangli watershed. Old Chen's hermitage stands on the hill above it — the destination Wang Lun's hexagram readings direct the protagonist to ('the hermit on the hill above Li Family Creek, four li east').",
    source: "doc 04 §1.1, doc 31 §3.2-3.9",
    relations: [{ type: "PART_OF", target: "region.cangli_riverlands" }],
    simulationHooks: ["social","economy","aging"],
    version: "0.1.0",
  },
  {
    id: "place.qinghe_market_town",
    kind: "location",
    name: "Qinghe Market Town",
    tags: ["market_town","trade","salt_depot","route"],
    description: "The market town at the river crossing 15 li (~8 km) east of Wang Family Bend, reachable by a ~1.7-hour walk at mortal pace or by ferry (5 cash). Holds a '1-6' market on the 1st, 5th, 10th, 15th, 20th and 25th of each lunar month; it is where villagers sell grain, cloth and pigs and buy salt, iron tools and paper, and it is the news network for the county. The county salt depot is here (Master Hu buys his licensed salt from it); the Daoist priest lives here. The route of Wu Changqing's and Old Chen's twice-yearly correspondence; Peng Li was a carpenter here before joining the Cangwu Sect.",
    source: "doc 04 §6.2, §5.3, doc 31 §1.2, §1.3",
    relations: [{ type: "PART_OF", target: "region.cangli_riverlands" }],
    simulationHooks: ["trade","economy","social","politics"],
    version: "0.1.0",
  },
  {
    id: "place.yanjing",
    kind: "location",
    name: "Yanjing",
    nameHanzi: "燕京",
    tags: ["capital","great_yan","mortal_city"],
    description: "The imperial seat of the Great Yan Dynasty, 5,400 li northwest of Wang Family Bend, in the middle reaches of the Yan River (燕江): a mortal city of two million. The Heavenly Pivot Sect (天樞宗), the empire's favored great sect, maintains a compound inside the inner wall. In middle decline with an open succession crisis.",
    source: "doc 42 §1.1",
    relations: [
      { type: "CAPITAL_OF", target: "institution.great_yan" },
      { type: "CONTAINS", target: "sect.heavenly_pivot" },
      { type: "LOCATED_IN", target: "region.zhong" },
    ],
    simulationHooks: ["politics","economy","social","history"],
    version: "0.1.0",
  },
  {
    id: "place.voidjade_peak",
    kind: "location",
    name: "Voidjade Peak",
    nameHanzi: "虛玉峰",
    tags: ["holy_land_seat","mountain","yunwu"],
    description: "The wood-phase peak in the Yunwu Mountains (雲霧山), the coastal range of Dong's western coast, 400 li inland from the port of Qingyang (青陽) and 4,800 li above sea level. The Jade Void Holy Land's compound — the Three-Courtyard Seat (三院): Outer Courtyard for outer disciples and visitors, Inner Courtyard for inner disciples and elders, Founder's Courtyard at the summit where Daoist Jade Void resides — occupies the peak's upper third; the lower slopes hold the holy land's outer-disciple villages and spirit-herb terraces. The Jade Void Grotto-Heaven is anchored at the Founder's Courtyard's central shrine. Reachable by mortal trail (6-day climb), Foundation Establishment flight (2 hours), or the weekly ceremonial Voidjade Ferry (虛玉渡).",
    source: "doc 42 §8.1, §8.3, doc 43 §1.1",
    relations: [
      { type: "CONTAINS", target: "sect.jade_void" },
      { type: "CONTAINS", target: "place.jade_void_grotto" },
      { type: "LOCATED_IN", target: "region.dong" },
    ],
    simulationHooks: ["cultivation","ritual","perception","politics"],
    version: "0.1.0",
  },

  // ============================ GROTTO-HEAVENS ============================

  {
    id: "place.jade_void_grotto",
    kind: "location",
    name: "Jade Void Grotto-Heaven",
    nameHanzi: "玉虛洞天",
    tags: ["grotto_heaven","pocket_world","wood_phase","time_rate_1_5"],
    description: "The Jade Void Holy Land's peak grotto-heaven, anchored at the Founder's Courtyard shrine on Voidjade Peak: ~50 li, wood-phase, dense and mild, qi-scent of cedar; time-rate 1:5 (one day inside = five outside). Interior a wood-phase mountain-garden where inner disciples cultivate and Daoist Jade Void spends most of his time; holds the holy land's library, the cultivation world's most comprehensive non-Courts repository. Spirit herbs include Silent-Heart Vine and Voidjade Moss; one songbird-yao (Qingyuan, 600 years old) lives there.",
    source: "doc 43 §3, doc 42 §8.3",
    relations: [
      { type: "CONTAINS", target: "vein.voidjade_wood", note: "grotto sustained by the vein" },
      { type: "LOCATED_IN", target: "place.voidjade_peak" },
    ],
    simulationHooks: ["cultivation","ecology","perception","save"],
    version: "0.1.0",
  },
  {
    id: "place.jade_edge_grotto",
    kind: "location",
    name: "Jade Edge Grotto-Heaven",
    nameHanzi: "玉涯洞天",
    tags: ["grotto_heaven","pocket_world","metal_phase","time_rate_1_3"],
    description: "The Azure Sword Sect's grotto-heaven, also called the Jade Edge Grotto (碧玉緣洞天, doc 31 §2.3): ~30 li, metal-phase, sharp and cold, qi-scent of iron and snow; time-rate 1:3. Anchor is a jade gate behind the Sword-Washing Waterfall (洗劍瀑) on Biluo Peak's north face — its surface cave lies 300 li west of the sect compound in the western Cangwu range's deep extension. Ecology: sword-grass (劍草), blue-flame lotus (青焰蓮), iron-root pine (鐵根松); silver-furred foxes, metal-phase hawks, and the ancient jade-scaled serpent (玉鱗蛇, Foundation Establishment equivalent) that guards the interior. Metal-phase cultivation ~30% faster inside; wood ~20% slower. Both of Leng Wushuang's failed Nascent Soul attempts were conducted here; the central forge-lake is the sect's weapon-refinement site. 370 of the sect's 400 disciples cycle through on six-month rotations.",
    source: "doc 43 §3, doc 31 §2.3, §2.8",
    relations: [
      { type: "CONTAINS", target: "vein.biluo", note: "the grotto encloses the vein's main current" },
      { type: "LOCATED_IN", target: "sect.azure_sword" },
    ],
    simulationHooks: ["cultivation","ecology","combat","perception","save"],
    version: "0.1.0",
  },
  {
    id: "place.yellow_court_grotto",
    kind: "location",
    name: "Yellow Court Grotto-Heaven",
    nameHanzi: "黃庭洞天",
    tags: ["grotto_heaven","pocket_world","earth_phase","time_rate_1_8"],
    description: "The Yellow Court Holy Land's grotto-heaven, anchored at the patriarch's seat on Yellow Court Peak: ~80 li, earth-phase, dense and warm, qi-scent of clay and harvest; time-rate 1:8. Seven alchemical garden-caves; Earth-Marrow Mushroom and Desert-Bloom Lotus grow within. The patriarch's alchemical retreat.",
    source: "doc 43 §3",
    relations: [
      { type: "CONTAINS", target: "vein.yellow_court_earth", note: "grotto sustained by the great earth-phase vein" },
      { type: "LOCATED_IN", target: "sect.yellow_court" },
    ],
    simulationHooks: ["cultivation","ecology","economy","save"],
    version: "0.1.0",
  },
  {
    id: "place.verdant_pillar_grotto",
    kind: "location",
    name: "Verdant Pillar Grotto-Heaven",
    nameHanzi: "青柱洞天",
    tags: ["grotto_heaven","pocket_world","wood_phase","time_rate_1_12","pillar_ruins"],
    description: "The Verdant Pillar Holy Land's grotto-heaven, anchored at the central tree-shrine on the central highlands' great earth-wood vein: ~120 li, wood-phase, dense and ancient, with a 30,000-year-old forest; time-rate 1:12. Contains the seven surviving Pillar Cities' ruins and bark-strip libraries (access requires the patriarch's permission). Spirit herbs Pillar Sap and Bark-Strip Moss. Under the Thinning, the forest is dying.",
    source: "doc 43 §3, doc 43 §1.4",
    relations: [
      { type: "CONTAINS", target: "vein.pillar_root_remnant", note: "grotto sustained by the deepest surviving Pillar Root Vein trace" },
      { type: "LOCATED_IN", target: "sect.verdant_pillar" },
    ],
    simulationHooks: ["cultivation","ecology","history","save"],
    version: "0.1.0",
  },
  {
    id: "place.skyfire_crucible_grotto",
    kind: "location",
    name: "Skyfire Crucible Grotto-Heaven",
    nameHanzi: "天火爐洞天",
    tags: ["grotto_heaven","pocket_world","metal_fire","time_rate_1_4"],
    description: "The Skyfire Holy Land's grotto-heaven, anchored at the central forge of the Skyfire Crucible (天火爐) at the Ironbone Range's central spire: ~40 li, metal-fire phase, sharp and searing, qi-scent of hot iron and ash; time-rate 1:4. Ecology: Forge-Bell Flower, Iron-Sage's-Mint; forge-salamanders and iron-hawks. All Core-Formation-grade weapon refinement happens here; the patriarch has not left it in nine centuries.",
    source: "doc 43 §3",
    relations: [
      { type: "CONTAINS", target: "vein.skyfire_metal", note: "fire-phase secondary vein feeds the forges" },
      { type: "LOCATED_IN", target: "sect.skyfire" },
    ],
    simulationHooks: ["cultivation","ecology","economy","combat","save"],
    version: "0.1.0",
  },
  {
    id: "place.northsea_grotto",
    kind: "location",
    name: "NorthSea Grotto-Heaven",
    nameHanzi: "北海洞天",
    tags: ["grotto_heaven","pocket_world","water_yin","time_rate_1_20","ice"],
    description: "The NorthSea Holy Land's grotto-heaven, anchored at the Ice-Record Hall shrine at Bei's central glacial peak: ~60 li, water-yin phase, cold and still — an absolute-zero ice-field sustained by the Matriarch's NorthSea Stillness technique; time-rate 1:20, the slowest in the catalogue. Ice-Record Moss, the inscription-medium for the ancestral-court records, grows here; two frost-serpent-yao (Foundation Establishment) serve as record-keepers. The Hall requires the Matriarch's permission.",
    source: "doc 43 §3",
    relations: [
      { type: "CONTAINS", target: "vein.northsea_cold", note: "grotto sustained by Bei's largest water-yin vein" },
      { type: "LOCATED_IN", target: "sect.northsea" },
    ],
    simulationHooks: ["cultivation","ecology","history","save","perception"],
    version: "0.1.0",
  },
  {
    id: "place.pearl_tide_grotto",
    kind: "location",
    name: "Pearl-Tide Grotto-Heaven",
    nameHanzi: "珠潮洞天",
    tags: ["grotto_heaven","pocket_world","water_phase","time_rate_1_2"],
    description: "The Pearl-Tide Sect's grotto-heaven, anchored at the sect's waterfront compound at Haimen harbor's mouth: ~20 li, water-phase, mild and briny, qi-scent of salt and kelp; time-rate 1:2, the fastest in the catalogue (the sect's mercantile mission benefits from near-real-time rate). Ecology: sea-silk kelp (shallow-water variant) and pearl-oysters cultivated for Tide-Pearl. Contains the Matriarch's audience chamber and outer-disciple training grounds.",
    source: "doc 43 §3",
    relations: [{ type: "LOCATED_IN", target: "sect.pearl_tide" }],
    simulationHooks: ["cultivation","ecology","economy","trade","save"],
    version: "0.1.0",
  },
  {
    id: "place.emerald_pagoda_grotto",
    kind: "location",
    name: "Emerald Pagoda Grotto-Heaven",
    nameHanzi: "翠塔洞天",
    tags: ["grotto_heaven","pocket_world","wood_phase","time_rate_1_6","alchemy"],
    description: "The Emerald Pagoda Sect's grotto-heaven, anchored at the top floor of the nine-tier alchemy pagoda at Cuiping (翠屏), 300 li south of Qingyuan: ~25 li, wood-phase, dense and fragrant, qi-scent of blossom and resin; time-rate 1:6. Nine terraced gardens growing Wood-Marrow Mushroom, Root-Developing Root, and Body-Tempering Bark. The patriarch's alchemical retreat and the Jade Void's de facto alchemical annex.",
    source: "doc 43 §3",
    relations: [{ type: "LOCATED_IN", target: "sect.emerald_pagoda" }],
    simulationHooks: ["cultivation","ecology","economy","save"],
    version: "0.1.0",
  },

  // ============================ SPIRIT VEINS ============================

  {
    id: "vein.green_mirror",
    kind: "cosmological_feature",
    name: "Green Mirror Vein",
    nameHanzi: "青鏡脈",
    tags: ["spirit_vein","water_phase_primary","wood_phase_secondary","yin_dominant","minor"],
    description: "The Cangwu Sect's minor spirit vein: yin-dominant, water-phase primary with a wood-phase secondary, running northeast-southwest through the granite of the central Cangwu range. Surface trace the Green Mirror Spring (青鏡泉), a spring in a small cave behind a curtain of moss on the valley's western wall; main current ~240 m below the valley floor, flowing slowly northeast, measured (15 years ago) to sustain 35-40 Qi Condensation cultivators at full practice. Discovered 240 years ago by the wandering Qi Condensation cultivator Daoist Cangwu; output today roughly half its level when the sect was constituted 180 years ago. Wu Changqing believes the Azure Sword Sect's deep-tap upstream draws more than tribute records show; the Azure Sword maintains the decline is geological. Its deep extension, running northeast at depth toward Biluo Peak, is the object of the Cangli spirit vein dispute — dense enough at one point (~60 li southwest of Biluo Peak) to support a second grotto-heaven. Per doc 37 §9.2, the Cangli vein connects cosmically to the Pillar Root Vein.",
    source: "doc 31 §1.4, §2.4, doc 42 §1.4, doc 43 §2.15",
    relations: [
      { type: "LOCATED_IN", target: "place.cangwu_valley" },
      { type: "CONTAINS", target: "location.cangwu_sect", note: "the sect is built around it" },
    ],
    simulationHooks: ["cultivation","ecology","economy","deviation"],
    version: "0.1.0",
  },
  {
    id: "vein.biluo",
    kind: "cosmological_feature",
    name: "Biluo Vein",
    nameHanzi: "碧螺脈",
    tags: ["spirit_vein","metal_phase_primary","primary","stable"],
    description: "The Azure Sword Sect's primary spirit vein, breaking the surface inside the compound walls beneath the Sword-Ancestor Hall on Biluo Peak: current runs deep (~400 m below the summit), output sufficient to sustain two hundred cultivators at full Qi Condensation practice, or thirty at Foundation Establishment. Surface trace the Founder's Spring (祖師泉) in the Founder's Garden, faintly metallic to the taste. Tapped for 180 years with no sign of thinning; feeds the compound's main cultivation hall and the Jade Edge Grotto-Heaven's anchor.",
    source: "doc 31 §2.7",
    relations: [{ type: "CONTAINS", target: "sect.azure_sword" }],
    simulationHooks: ["cultivation","ecology","economy"],
    version: "0.1.0",
  },
  {
    id: "vein.north_cloud",
    kind: "cosmological_feature",
    name: "North Cloud Vein",
    nameHanzi: "北雲脈",
    tags: ["spirit_vein","metal_phase_primary","secondary"],
    description: "The Azure Sword Sect's secondary vein, breaking the surface two li north of the compound on Biluo Peak's far side: shallower current (~150 m), output roughly half the Biluo Vein's. Surface trace a cold, mineral-heavy spring in a small hanging valley developed into the North Cloud Garden (北雲苑), a terraced herb garden growing metal- and water-phase spirit herbs for the Pill Hall; managed by a Foundation Establishment elder and six inner disciples on rotation. Its output is not directly tapped for cultivation — it feeds the sect's pharmaceutical chain.",
    source: "doc 31 §2.7",
    relations: [{ type: "CONTAINS", target: "sect.azure_sword" }],
    simulationHooks: ["cultivation","ecology","economy"],
    version: "0.1.0",
  },
  {
    id: "vein.iron_root",
    kind: "cosmological_feature",
    name: "Iron Root Vein",
    nameHanzi: "鐵根脈",
    tags: ["spirit_vein","metal_phase_primary","tertiary","sword_craft"],
    description: "The Azure Sword Sect's tertiary vein, breaking the surface four li southwest of the compound in a wild region of the peak's lower slopes: shallowest current (~60 m) and smallest output (sufficient for thirty Qi Condensation cultivators). Surface trace a stand of iron-root pine (鐵根松), the same species as in the Jade Edge Grotto-Heaven. The vein saturates the pines' wood with metal-phase qi, making it forgeable into practice swords — the sect's sword-craft resource, managed by the Sword-Craft Hall.",
    source: "doc 31 §2.7",
    relations: [{ type: "CONTAINS", target: "sect.azure_sword" }],
    simulationHooks: ["cultivation","ecology","economy"],
    version: "0.1.0",
  },
  {
    id: "vein.voidjade_wood",
    kind: "cosmological_feature",
    name: "Voidjade Wood Vein",
    nameHanzi: "虛玉木脈",
    tags: ["spirit_vein","wood_phase","holy_land","largest_on_dong"],
    description: "Dong's largest wood-phase vein; the Jade Void Holy Land's spirit vein, sustaining the Jade Void Grotto-Heaven's 1:5 time-rate at Voidjade Peak.",
    source: "doc 43 §1.1",
    relations: [{ type: "CONTAINS", target: "sect.jade_void" }],
    simulationHooks: ["cultivation","ecology","economy"],
    version: "0.1.0",
  },
  {
    id: "vein.yellow_court_earth",
    kind: "cosmological_feature",
    name: "Yellow Court Earth Vein",
    nameHanzi: "黃庭土脈",
    tags: ["spirit_vein","earth_phase","holy_land","largest_on_zhong"],
    description: "Zhong's largest earth-phase vein, underlying the western interior desert; sustains the Yellow Court Grotto-Heaven's 1:8 time-rate and the Yellow Court Holy Land's earth-phase alchemy.",
    source: "doc 43 §1.2, doc 42 §1.5",
    relations: [{ type: "CONTAINS", target: "sect.yellow_court" }],
    simulationHooks: ["cultivation","ecology","economy"],
    version: "0.1.0",
  },
  {
    id: "vein.skyfire_metal",
    kind: "cosmological_feature",
    name: "Skyfire Metal Vein",
    nameHanzi: "天火金脈",
    tags: ["spirit_vein","metal_phase","holy_land","largest_on_xi","fire_secondary"],
    description: "Xi's largest metal-phase vein, with a fire-phase secondary vein feeding the Skyfire Crucible's forges; sustains the Skyfire Crucible Grotto-Heaven.",
    source: "doc 43 §1.3",
    relations: [{ type: "CONTAINS", target: "sect.skyfire" }],
    simulationHooks: ["cultivation","ecology","economy"],
    version: "0.1.0",
  },
  {
    id: "vein.pillar_root_remnant",
    kind: "cosmological_feature",
    name: "Pillar Root Vein Remnant",
    nameHanzi: "柱根脈餘",
    tags: ["spirit_vein","earth_wood_dual","holy_land","dying","cosmic_scale"],
    description: "The deepest surviving trace of the cosmic-scale Pillar Root Vein (doc 37 §9.2); the Verdant Pillar Holy Land's vein on Nan's central highlands, earth-wood dual-phase, sustaining the Verdant Pillar Grotto-Heaven's 1:12 time-rate. Dying under the Thinning; the holy land's grief is that of ecologists watching the remnant thin.",
    source: "doc 43 §1.4",
    relations: [{ type: "CONTAINS", target: "sect.verdant_pillar" }],
    simulationHooks: ["cultivation","ecology","economy","deviation"],
    version: "0.1.0",
  },
  {
    id: "vein.northsea_cold",
    kind: "cosmological_feature",
    name: "NorthSea Cold Vein",
    nameHanzi: "北海寒脈",
    tags: ["spirit_vein","water_yin","holy_land","largest_on_bei"],
    description: "Bei's largest water-yin vein, so cold that the NorthSea Grotto-Heaven's interior is a permanent ice-field; sustains the 1:20 time-rate and the Matriarch's ancestral-court record-keeping.",
    source: "doc 43 §1.5",
    relations: [{ type: "CONTAINS", target: "sect.northsea" }],
    simulationHooks: ["cultivation","ecology","history"],
    version: "0.1.0",
  },

  // ============================ SECTS ============================

  {
    id: "sect.jade_void",
    kind: "sect",
    name: "Jade Void Holy Land",
    nameHanzi: "玉虛聖地",
    tags: ["holy_land","nascent_soul","dong","divination","ancestral_veneration","library"],
    description: "Dong's — and the cultivation world's — most influential holy land, on Voidjade Peak in the Yunwu Mountains, 400 li inland from Qingyang. Patriarch Daoist Jade Void (玉虛真人), Nascent Soul, age 2,100, founder and retired patriarch (declined Tribulation Crossing three times); acting head Elder Mu Yunfeng (穆雲峰), Nascent Soul early-stage, age 800, 17th-generation successor. 3,000 disciples (1,800 outer, 1,200 inner, 47 Foundation Establishment elders, 3 Nascent Soul elders). Peak grotto-heaven (the Jade Void Grotto-Heaven, wood-phase, 1:5) and Dong's largest wood-phase vein (the Voidjade Wood Vein). Specialty: divination (derived from the Silent Hexagram Method fragment), ancestral veneration (the rotating-shrine rite in the Cangli Riverlands, where the founder was born 2,100 years ago), and the cultivation world's most comprehensive non-Courts library. Suzerain of the Azure Sword Sect, the Pearl-Tide Sect, the Emerald Pagoda Sect, and (partially) the Whale-Rider Sect; protector of the Yueling Dynasty; 2,000-year polite rivalry with the Yellow Court; warm scholarly collaboration with the Verdant Pillar; independent but deferential to the Courts of Heaven.",
    source: "doc 42 §2.3, §8, doc 43 §1.1",
    relations: [
      { type: "CONTAINS", target: "vein.voidjade_wood" },
      { type: "CONTAINS", target: "place.jade_void_grotto" },
      { type: "RIVAL_OF", target: "sect.yellow_court", note: "influence over Zhong's middle reaches" },
      { type: "ALLIED_WITH", target: "sect.verdant_pillar", note: "divided custody of the Pillar Dynasty Annals" },
      { type: "LOCATED_IN", target: "region.dong" },
    ],
    simulationHooks: ["cultivation","politics","ritual","history","economy","social"],
    renderProfile: "location_holy_land",
    version: "0.1.0",
  },
  {
    id: "sect.yellow_court",
    kind: "sect",
    name: "Yellow Court Holy Land",
    nameHanzi: "黃庭聖地",
    tags: ["holy_land","nascent_soul","zhong","alchemy","earth_phase"],
    description: "Zhong Continent's only holy land, holding the western interior's central range. Patriarch Daoist Yellow Court (黃庭真人), Nascent Soul late-stage, age 3,400; acting head Elder Tan Yueshan (譚岳山), Nascent Soul early-stage, age 540. 4,200 disciples (2,500 outer, 1,700 inner, 62 Foundation Establishment elders, 4 Nascent Soul elders). Compound the Five-Hall Seat (五堂) on Yellow Court Peak, 8,000 li west of Yanjing. Grotto-heaven the Yellow Court Grotto-Heaven (earth-phase, 1:8) above the Yellow Court Earth Vein, Zhong's largest earth-phase vein, underlying the western desert. Specialty: earth-phase alchemy (Foundation-Solid Pill, Core-Stabilizing Pill, rare Earth-Marrow Pill) — the Great Yan Dynasty's traditional alchemical supplier, and the Courts of Heaven's largest external supply (allied with the Courts). Vassals: Sand-Veiled Sect, Heavenly Pivot (partial), Iron-Horse (partial). Polite 2,000-year rivalry with the Jade Void over Zhong's middle reaches.",
    source: "doc 42 §9.1, doc 43 §1.2",
    relations: [
      { type: "CONTAINS", target: "vein.yellow_court_earth" },
      { type: "CONTAINS", target: "place.yellow_court_grotto" },
      { type: "RIVAL_OF", target: "sect.jade_void", note: "influence over Zhong's middle reaches" },
      { type: "ALLIED_WITH", target: "institution.courts_of_heaven", note: "alchemical tithes are the Courts' largest external supply" },
      { type: "LOCATED_IN", target: "region.zhong" },
    ],
    simulationHooks: ["cultivation","economy","politics","ritual","history"],
    renderProfile: "location_holy_land",
    version: "0.1.0",
  },
  {
    id: "sect.skyfire",
    kind: "sect",
    name: "Skyfire Holy Land",
    nameHanzi: "天火聖地",
    tags: ["holy_land","nascent_soul","xi","smithing","weapon_craft"],
    description: "Xi's — and the metal-phase world's — leading holy land. Patriarch Patriarch Iron Sage (鐵聖上人), Nascent Soul, age 2,800, a taciturn smith-cultivator who has not spoken in council for three centuries; acting head Elder Lian Tie (煉鐵), Nascent Soul early-stage, age 620. 2,800 disciples (1,600 outer, 1,200 inner, 38 Foundation Establishment elders, 2 Nascent Soul elders). Compound the Skyfire Crucible (天火爐) at the Ironbone Range's central spire; grotto-heaven the Skyfire Crucible Grotto-Heaven (metal-fire, 1:4) above the Skyfire Metal Vein, Xi's largest metal-phase vein with a fire-phase secondary feeding the forges. Specialty: metal-phase smithing, weapon-craft, formation arrays — the Courts of Heaven's traditional weapon-supplier (the closest of the five holy lands to the Courts; its patriarch is the only one who visits the Courts' Roads department in person). Signature technique the Iron Sage's Nine-Fold Fold (鐵聖九折). Vassals: Ironbone Sect; Stone Lantern Sect (independent, Courts-delegated mission).",
    source: "doc 42 §3.3, doc 43 §1.3",
    relations: [
      { type: "CONTAINS", target: "vein.skyfire_metal" },
      { type: "CONTAINS", target: "place.skyfire_crucible_grotto" },
      { type: "ALLIED_WITH", target: "institution.courts_of_heaven", note: "traditional weapon-supplier" },
      { type: "LOCATED_IN", target: "region.xi" },
    ],
    simulationHooks: ["cultivation","economy","combat","politics","history"],
    renderProfile: "location_holy_land",
    version: "0.1.0",
  },
  {
    id: "sect.verdant_pillar",
    kind: "sect",
    name: "Verdant Pillar Holy Land",
    nameHanzi: "青柱聖地",
    tags: ["holy_land","nascent_soul","nan","yao_cofounded","pillar_lore"],
    description: "Nan's holy land, the cultivation world's only yao-co-founded holy land. Patriarch Daoist Pillar Canopy (柱冠真人), Nascent Soul, age 1,700, human co-founder; co-founder the tree-yao Old Pillar (老柱), Foundation Establishment yao, ~3,200 years old, the oldest non-Mahayana yao; acting head Elder Sang Qingyu (桑青羽), Nascent Soul early-stage, age 380, the first half-yao acting head. 1,800 disciples (1,000 outer, 800 inner — 240 of the inner are yao, the only holy land with a yao-disciple contingent). Compound the Verdant Pillar Seat (青柱院) on the central highlands' earth-wood vein; grotto-heaven the Verdant Pillar Grotto-Heaven (wood-phase, 1:12) containing the seven surviving Pillar Cities' ruins and bark-strip libraries; vein the Pillar Root Vein Remnant, dying under the Thinning. Specialty: yao cultivation, wood-phase beast-taming, Pillar Dynasty lore (holds 5 of the 12 volumes of the Pillar Dynasty Annals). Independent of the Courts (yao-foundation outside their lineage-jurisdiction). Vassals: Redwood Canopy Sect; Sea-Fan Sect (partial). Warm scholarly collaboration with the Jade Void (1,500-year correspondence on the Annals); warm with the NorthSea.",
    source: "doc 42 §4.3, doc 43 §1.4",
    relations: [
      { type: "CONTAINS", target: "vein.pillar_root_remnant" },
      { type: "CONTAINS", target: "place.verdant_pillar_grotto" },
      { type: "ALLIED_WITH", target: "sect.jade_void", note: "divided custody of the Pillar Dynasty Annals" },
      { type: "LOCATED_IN", target: "region.nan" },
    ],
    simulationHooks: ["cultivation","ecology","politics","ritual","history","social"],
    renderProfile: "location_holy_land",
    version: "0.1.0",
  },
  {
    id: "sect.northsea",
    kind: "sect",
    name: "NorthSea Holy Land",
    nameHanzi: "北海聖地",
    tags: ["holy_land","nascent_soul","bei","ice_cultivation","record_keeping"],
    description: "Bei's holy land, the cultivation world's oldest-patriarch. Matriarch Matriarch NorthSea (北海道君), Nascent Soul, age 3,000, the oldest non-Mahayana being; acting head Elder Bing Zhen (冰臻), Nascent Soul early-stage, age 720. 2,200 disciples (1,300 outer, 900 inner — 180 of the inner are yao drawn from the Frostfang Yao). Compound the Ice-Record Hall (冰錄堂) at Bei's central glacial peak; grotto-heaven the NorthSea Grotto-Heaven (water-yin, 1:20, the slowest in the catalogue, a permanent ice-field) above the NorthSea Cold Vein, Bei's largest water-yin vein. Specialty: water-phase ice-cultivation (signature NorthSea Stillness, 北海寂, which brings qi-circulation to absolute zero) and ancestral-court preservation — the Ice-Record Hall holds the Mortal Stratum's oldest accessible ancestral-court records, predating the Courts' founding by ~8,000 years. Independent peer of the Courts. Trains the Black-Ice Khanate's Foundation Establishment Khans; vassals Snowstrider Sect, Mammoth-Bone Sect (independent, yao-alliance); deepest alliance with the Frostfang Yao.",
    source: "doc 42 §5.3, doc 43 §1.5",
    relations: [
      { type: "CONTAINS", target: "vein.northsea_cold" },
      { type: "CONTAINS", target: "place.northsea_grotto" },
      { type: "ALLIED_WITH", target: "institution.black_ice_khanate", note: "traditional protector; trains the Khans" },
      { type: "LOCATED_IN", target: "region.bei" },
    ],
    simulationHooks: ["cultivation","history","ritual","politics","ecology"],
    renderProfile: "location_holy_land",
    version: "0.1.0",
  },
  {
    id: "sect.azure_sword",
    kind: "sect",
    name: "Azure Sword Sect",
    nameHanzi: "碧劍宗",
    tags: ["great_sect","core_formation","zhong","sword_cultivation","metal_phase"],
    description: "The great sect of the central and northern Cangwu range, on Biluo Peak (碧螺峰), 500 li north of Wang Family Bend. Sect master Leng Wushuang (冷無霜), Core Formation, age 340, appears 50; 400 disciples (300 outer, 100 inner), 38 elders. Three metal-phase-primary spirit veins — the Biluo, North Cloud, and Iron Root Veins (doc 43 §2.1 gives the alternative names Azure Sword Vein, Jade-Edge Vein, Northern Cangwu Vein); one grotto-heaven, the Jade Edge Grotto-Heaven (玉涯洞天, metal-phase, 1:3). Compound walls enclose the Sword-Ancestor Hall (劍祖堂, holding the founder's sword-token), the Three Sword Peaks (三劍峰), the Eight Halls, the inner courtyard city (300 inner disciples) and outer camp (100 outer). Specialty: sword cultivation (碧劍, the jade-green sword). Formal vassal of the Jade Void Holy Land (one mid-grade spirit stone per decade in exchange for implicit protection); mid-tier Immortal Alliance seat (one of thirty in the eastern region). Expansion toward the Cangli Riverlands' latent vein (the Cangli spirit vein dispute) is driven by Leng Wushuang's need to fund a third Nascent Soul attempt; internal factions: Expansionist (Elder Rong Zhaoyuan, 容昭遠) versus Isolationist (Elder Jing You, 靜幽), with Punishment Hall head Leng Qingxue (冷清雪), the youngest Core Formation elder in sect history, leading the dissent. Cold with the Cangwu Sect; warm with the Iron-Horse Sect (shared sword-cultivation root); sword-cousins with the Azuremist Sect (outer-disciples exchanged every 60 years).",
    source: "doc 31 §2, doc 42 §1.3, doc 43 §2.1",
    relations: [
      { type: "VASSAL_OF", target: "sect.jade_void" },
      { type: "RIVAL_OF", target: "location.cangwu_sect", note: "the Cangli spirit vein dispute" },
      { type: "ALLIED_WITH", target: "sect.iron_horse", note: "shared sword-cultivation root" },
      { type: "ALLIED_WITH", target: "sect.azuremist", note: "sword-cousins; outer disciples exchanged every 60 years" },
      { type: "CONTAINS", target: "vein.biluo" },
      { type: "CONTAINS", target: "vein.north_cloud" },
      { type: "CONTAINS", target: "vein.iron_root" },
      { type: "CONTAINS", target: "place.jade_edge_grotto" },
      { type: "LOCATED_IN", target: "region.zhong" },
    ],
    simulationHooks: ["cultivation","politics","combat","economy","social","history"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.heavenly_pivot",
    kind: "sect",
    name: "Heavenly Pivot Sect",
    nameHanzi: "天樞宗",
    tags: ["great_sect","core_formation","zhong","formation_arrays","imperial"],
    description: "The Great Yan Dynasty's favored great sect, with a compound inside Yanjing's inner wall. Sect master Patriarch Heavenly-Pivot (天樞上人), Core Formation late-stage, age 880. 800 disciples (500 outer, 300 inner). Two spirit veins (the Imperial Pivot Vein beneath Yanjing, the Yan River Vein); the Heavenly Pivot Grotto-Heaven (天樞洞天, metal-earth, 1:4, anchored beneath the imperial palace). Specialty: formation arrays and imperial spiritual-geomancy — in practice the emperor's cultivation-advisor and the court's Core Formation enforcement arm. Partial vassal of the Yellow Court (alchemical reagents for imperial-court intelligence); has backed the literati faction; cold with the Azure Sword Sect (contest for the empire's sword-cultivation patronage); cordial with the Iron-Horse; formal with the Pearl-Tide.",
    source: "doc 42 §1.1, doc 43 §2.2",
    relations: [
      { type: "VASSAL_OF", target: "sect.yellow_court", note: "partial — alchemical reagents" },
      { type: "RIVAL_OF", target: "sect.azure_sword", note: "the empire's sword-cultivation patronage" },
      { type: "LOCATED_IN", target: "place.yanjing" },
    ],
    simulationHooks: ["politics","cultivation","combat","economy","history"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.sand_veiled",
    kind: "sect",
    name: "Sand-Veiled Sect",
    nameHanzi: "沙幕宗",
    tags: ["great_sect","core_formation","zhong","trade_route","neutral_ground"],
    description: "The western interior's leading great sect of Zhong, headquartered at the oasis city Yumen (玉門), 7,000 li west of Yanjing. Sect master Patriarch Dune (沙丘老人), Core Formation, age 600. 350 disciples. Two spirit veins (the Yumen Oasis Vein, the Sand-Veiled Desert Vein); the Sand-Veiled Grotto-Heaven (沙幕洞天, earth-fire, 1:3, beneath the Sand-Veiled Caravansary). Specialty: desert trade-route protection, the Sand-Veiled Caravansary's (沙幕驛) neutral-ground enforcement — the cultivation world's largest neutral trade-post at Yumen, where no combat is permitted — and earth-fire alchemy. Vassal of the Yellow Court (its primary western-interior proxy). Cold with the Azure Sword Sect (the Yellow Court–Jade Void rivalry's downstream); cordial with the Stone Lantern Sect (the Western Ocean Crossing's two anchors).",
    source: "doc 42 §1.5, doc 43 §2.3",
    relations: [
      { type: "VASSAL_OF", target: "sect.yellow_court" },
      { type: "RIVAL_OF", target: "sect.azure_sword", note: "Yellow Court–Jade Void rivalry downstream" },
      { type: "ALLIED_WITH", target: "sect.stone_lantern", note: "Western Ocean Crossing's two anchors" },
      { type: "LOCATED_IN", target: "region.zhong" },
    ],
    simulationHooks: ["trade","economy","politics","combat","cultivation"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.pearl_tide",
    kind: "sect",
    name: "Pearl-Tide Sect",
    nameHanzi: "珠潮宗",
    tags: ["great_sect","core_formation","zhong","maritime","route_anchor"],
    description: "The eastern coast's leading great sect of Zhong, headquartered at the great port of Haimen (海門), 1,200 li north of Wang Family Bend. Sect master Matriarch Tide Pearl (潮珠道君), Core Formation, age 480, commanding a fleet of twelve qi-sailed junks. 500 disciples. Two spirit veins (the Pearl-Tide Harbor Vein, the Eastern Coast Vein); the Pearl-Tide Grotto-Heaven (珠潮洞天, water-phase, 1:2, anchored at the harbor's mouth). Specialty: maritime cultivation; maintains the Vermilion Pearl Route's Zhong-side anchor and is a Pearl Archipelago Compact signatory. Vassal of the Jade Void (its preferred Zhong-side intermediary); outer disciples often train at the Jade Void on Dong. Cordial with the Azure Sword; tense with the Crystal-Tide Sect (the Eastern Sea spirit-herb beds); cooperative with the Whale-Rider (the Route's two surface anchors); cold with the Sea-Fan (the Southern Monsoon Run's territorial contest).",
    source: "doc 42 §1.6, §6.1, doc 43 §2.4",
    relations: [
      { type: "VASSAL_OF", target: "sect.jade_void" },
      { type: "RIVAL_OF", target: "sect.crystal_tide", note: "Eastern Sea spirit-herb beds" },
      { type: "ALLIED_WITH", target: "sect.whale_rider", note: "Vermilion Pearl Route's two surface anchors" },
      { type: "LOCATED_IN", target: "region.zhong" },
    ],
    simulationHooks: ["trade","economy","politics","combat","cultivation"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.iron_horse",
    kind: "sect",
    name: "Iron-Horse Sect",
    nameHanzi: "鐵馬宗",
    tags: ["great_sect","core_formation","zhong","cavalry","frontier"],
    description: "The empire's northern frontier great sect of Zhong, headquartered at the garrison city of Beiguan (北關), 4,000 li north of Yanjing. Sect master Patriarch Iron-Horse (鐵馬上人), Core Formation late-stage, age 720, commanding the empire's northern cavalry reserve and spirit-beast mounted scouts. 600 disciples, the empire's largest great-sect cavalry reserve. Two spirit veins (the Beiguan Steppe Vein, the Northern Cangwu Vein's northern extension); the Iron-Horse Grotto-Heaven (鐵馬洞天, metal-water, 1:3, at the Beiguan garrison's central keep). Specialty: beast-mounted cavalry cultivation (metal-water dual-phase) and the Northern Slash (北斬) saber-art; the founder was an Azure Sword outer disciple four centuries ago. Partial vassal of the Yellow Court (alchemical supply). Warm with the Azure Sword; cold with the Snowstrider Sect (the long border war with the Black-Ice Khanate — eleven wars in 247 years, none decisive).",
    source: "doc 42 §1.7, doc 43 §2.5",
    relations: [
      { type: "VASSAL_OF", target: "sect.yellow_court", note: "partial — alchemical supply" },
      { type: "ALLIED_WITH", target: "sect.azure_sword", note: "shared sword-cultivation root" },
      { type: "RIVAL_OF", target: "sect.snowstrider", note: "the northern border war" },
      { type: "LOCATED_IN", target: "region.zhong" },
    ],
    simulationHooks: ["combat","politics","economy","cultivation","migration"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.emerald_pagoda",
    kind: "sect",
    name: "Emerald Pagoda Sect",
    nameHanzi: "翠塔宗",
    tags: ["great_sect","core_formation","dong","alchemy","wood_phase"],
    description: "Dong's leading alchemy sect, at Cuiping (翠屏), 300 li south of Qingyuan. Sect master Patriarch Emerald Furnace (翠爐上人), Core Formation late-stage, age 590. 450 disciples. Three spirit veins (the Cuiping Wood Vein, the Central Lowlands Vein, the Southern Marsh Vein); the Emerald Pagoda Grotto-Heaven (翠塔洞天, wood-phase, 1:6, at the nine-tier alchemy pagoda's top floor). Specialty: wood-phase alchemy (Root-Developing Pill, Body-Tempering Pill, the rare Wood-Marrow Pill). Near-vassal of the Jade Void — the Jade Void's primary pill-supplier; the two are mutually dependent (the Jade Void supplies the manuals, the Pagoda supplies the pills). Distant professional respect with Patriarch Mu of the Azure Sword Sect (correspondence across the Eastern Sea); cordial with the Azuremist; cooperative with the Whale-Rider.",
    source: "doc 42 §2.5, doc 43 §2.6",
    relations: [
      { type: "VASSAL_OF", target: "sect.jade_void", note: "near-vassalage; manuals for pills" },
      { type: "LOCATED_IN", target: "region.dong" },
    ],
    simulationHooks: ["cultivation","economy","ecology","trade"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.whale_rider",
    kind: "sect",
    name: "Whale-Rider Sect",
    nameHanzi: "鯨馭宗",
    tags: ["great_sect","core_formation","dong","beast_taming","maritime"],
    description: "Dong's coastal beast-taming great sect, headquartered at the port of Haiqing (海青) on Dong's eastern coast. Sect master Matriarch Whale-Song (鯨吟道君), Core Formation, age 410, commanding a pod of seventeen cultivated qi-whales bred for nine centuries. 380 disciples (40 inner are beast-tamers bonded to the qi-whales). Two spirit veins (the Haiqing Coast Vein, the Eastern Sea Deep Vein); the Whale-Rider Grotto-Heaven (鯨馭洞天, water-phase, 1:4, at the Haiqing harbor's deep-water shrine). Specialty: sea-beast taming, oceanic spirit-herb gathering, deep-water exploration; maintains the Vermilion Pearl Route's Dong-side anchor and operates its deep-water patrol. Partial vassal of the Jade Void. Maritime alliance with the Pearl-Tide (patrol routes meet at the Pearl Archipelago's mid-route shrine); tense with the Crystal-Tide (deep-water herb beds); cordial with the Emerald Pagoda.",
    source: "doc 42 §2.5, doc 43 §2.7",
    relations: [
      { type: "VASSAL_OF", target: "sect.jade_void", note: "partial — maintains the Route's Dong-side" },
      { type: "ALLIED_WITH", target: "sect.pearl_tide", note: "maritime alliance" },
      { type: "RIVAL_OF", target: "sect.crystal_tide", note: "deep-water spirit-herb beds" },
      { type: "LOCATED_IN", target: "region.dong" },
    ],
    simulationHooks: ["ecology","trade","combat","cultivation","economy"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.azuremist",
    kind: "sect",
    name: "Azuremist Sect",
    nameHanzi: "青嵐宗",
    tags: ["great_sect","core_formation","dong","sword_cultivation","cloud_forest"],
    description: "Dong's mountain-interior great sect in the central range's cloud forests. Sect master Patriarch Azure-Mist (青嵐上人), Core Formation, age 380. 320 disciples. Two spirit veins (the Cloud Forest Vein, the Central Range Vein); the Azuremist Grotto-Heaven (青嵐洞天, wood-phase, 1:5, at the sect's cloud-forest peak, 1,200 li east of Qingyuan). Specialty: wood-phase sword cultivation — Dong's counterpart to the Azure Sword Sect's tradition, derived from the same pre-Crimson-Vow root, practiced in the canopy where wood-phase qi is densest and visibility lowest. Sword-cousins with the Azure Sword Sect (the cultivation world's longest-running cross-continental friendship; outer disciples exchanged every 60 years). Cool independent of the Jade Void (the Azuremist considers its divination a distraction; the Jade Void considers the Azuremist's sword-asceticism useful but limited).",
    source: "doc 42 §2.5, doc 43 §2.8",
    relations: [
      { type: "ALLIED_WITH", target: "sect.azure_sword", note: "sword-cousins; disciples exchanged every 60 years" },
      { type: "LOCATED_IN", target: "region.dong" },
    ],
    simulationHooks: ["cultivation","combat","ecology","politics"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.ironbone",
    kind: "sect",
    name: "Ironbone Sect",
    nameHanzi: "鐵骨宗",
    tags: ["great_sect","core_formation","xi","body_tempering","confederacy"],
    description: "The Ironbone Confederacy's leading great sect, headquartered at Tiegufeng (鐵骨峰) itself. Sect master Patriarch Iron-Fang (鐵牙上人), Core Formation, age 610, Matriarch Ironbone's son and the Confederacy's hereditary War-Chair. 400 disciples. Two spirit veins (the Ironbone Vein, the Central Spire Vein); the Ironbone Grotto-Heaven (鐵骨洞天, metal-phase, 1:3, at the Tiegufeng citadel's central forge). Specialty: metal-phase body-tempering and the Ironbone Clan's ancestral saber technique. Near-vassal of the Skyfire (its forge-elders refine the Ironbone's saber-blanks; the Ironbone's outer disciples serve the Skyfire's forges). Cold with the Stone Lantern (the Confederacy's military primacy); cordial with the Sand-Veiled (the Western Ocean Crossing's two anchors).",
    source: "doc 42 §3.4, doc 43 §2.9",
    relations: [
      { type: "VASSAL_OF", target: "sect.skyfire", note: "near-vassalage" },
      { type: "RIVAL_OF", target: "sect.stone_lantern", note: "Confederacy military primacy" },
      { type: "LOCATED_IN", target: "region.xi" },
    ],
    simulationHooks: ["combat","cultivation","politics","economy"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.stone_lantern",
    kind: "sect",
    name: "Stone Lantern Sect",
    nameHanzi: "石燈宗",
    tags: ["great_sect","core_formation","xi","formation_arrays","frontier","reach_monitoring"],
    description: "Xi's frontier great sect on the continent's eastern coast, guarding the approaches to the Western Spirit Wilds' Law Reaches. Sect master Patriarch Stone-Lantern (石燈上人), Core Formation, age 540. 280 disciples — the smallest of the 13 great sects but the most strategically positioned. One spirit vein (the Eastern Coast Vein); no grotto-heaven, the only great sect without one (its frontier mission consumes all available qi-resources). Specialty: formation arrays — the spirit-stone lanterns marking the Western Ocean's coast, warning of qi-storms, and monitoring the Law Reaches' resonance (eleven mapped Reach-locations, reported to the Skyfire's forge-elders and the Courts). Independent of the Skyfire (its mission is Courts-delegated; it does not tithe). Cordial with the Sand-Veiled (the Western Ocean Crossing's anchors); cold with the Ironbone; formal with the Courts of Heaven's Roads department.",
    source: "doc 42 §3.4-3.5, doc 43 §2.10",
    relations: [
      { type: "ALLIED_WITH", target: "sect.sand_veiled", note: "Western Ocean Crossing's two anchors" },
      { type: "RIVAL_OF", target: "sect.ironbone", note: "Confederacy military primacy" },
      { type: "LOCATED_IN", target: "region.xi" },
    ],
    simulationHooks: ["perception","combat","politics","history","cultivation"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.sea_fan",
    kind: "sect",
    name: "Sea-Fan Sect",
    nameHanzi: "海扇宗",
    tags: ["great_sect","core_formation","nan","maritime","monsoon"],
    description: "The Monsoon Cities' leading great sect, headquartered at Nanhai (南海), the largest port. Sect master Matriarch Sea-Fan (海扇道君), Core Formation, age 470. 420 disciples. Two spirit veins (the Nanhai Coast Vein, the Monsoon Current Vein); the Sea-Fan Grotto-Heaven (海扇洞天, water-phase, 1:2, at the Nanhai harbor's mouth). Specialty: water-phase maritime cultivation and the Monsoon Council's enforcement arm; maintains the Southern Monsoon Run's Nan-side anchor. Partial vassal of the Verdant Pillar (its inner disciples train at the Verdant Pillar's grotto-heaven). Cooperative with the Pearl-Tide (the Run's two anchors, though the two contest the southern maritime trade); cooperative with the Redwood Canopy (joint enforcement of the Linwang trade-fair's neutrality); cordial with the Whale-Rider.",
    source: "doc 42 §4.5, doc 43 §2.11",
    relations: [
      { type: "VASSAL_OF", target: "sect.verdant_pillar", note: "partial — disciples train at its grotto-heaven" },
      { type: "ALLIED_WITH", target: "sect.redwood_canopy", note: "joint Linwang trade-fair neutrality" },
      { type: "LOCATED_IN", target: "region.nan" },
    ],
    simulationHooks: ["trade","combat","politics","cultivation","economy"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.redwood_canopy",
    kind: "sect",
    name: "Redwood Canopy Sect",
    nameHanzi: "紅冠宗",
    tags: ["great_sect","core_formation","nan","yao_human_diplomacy","jungle"],
    description: "Nan's jungle-interior great sect at the city of Linwang (林王), on the jungle's northern edge. Sect master Patriarch Redwood (紅冠上人), Core Formation, age 530, a half-yao cultivator. 300 disciples (40 inner are yao drawn from the Pillar Descendants). Two spirit veins (the Linwang Wood Vein, the Jungle Interior Vein); the Redwood Canopy Grotto-Heaven (紅冠洞天, wood-phase, 1:6, at the Linwang trade-fair's central grove). Specialty: wood-phase cultivation, yao-human diplomacy, and the Linwang trade-fair's neutral-ground enforcement. The Verdant Pillar's preferred successor-institution (its outer disciples train at the Verdant Pillar's grotto-heaven). Cooperative with the Sea-Fan (joint Linwang neutrality); warm with the Mammoth-Bone Sect (cross-continental yao-allied correspondence, disciples exchanged every 60 years).",
    source: "doc 42 §4.5, doc 43 §2.12",
    relations: [
      { type: "VASSAL_OF", target: "sect.verdant_pillar", note: "preferred successor-institution" },
      { type: "ALLIED_WITH", target: "sect.sea_fan", note: "joint Linwang trade-fair neutrality" },
      { type: "ALLIED_WITH", target: "sect.mammoth_bone", note: "cross-continental yao-allied correspondence" },
      { type: "LOCATED_IN", target: "region.nan" },
    ],
    simulationHooks: ["social","politics","cultivation","ecology","trade"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.snowstrider",
    kind: "sect",
    name: "Snowstrider Sect",
    nameHanzi: "雪行宗",
    tags: ["great_sect","core_formation","bei","cavalry","khanate"],
    description: "The Black-Ice Khanate's leading great sect, headquartered at Beicheng (北城), the Khanate's only permanent settlement. Sect master Patriarch Snowstrider (雪行上人), Core Formation, age 590, the Khan's cultivation-teacher. 350 disciples. Two spirit veins (the Beicheng Coast Vein, the Southern Steppe Vein); the Snowstrider Grotto-Heaven (雪行洞天, water-phase, 1:4, at the Beicheng garrison's central keep). Specialty: water-phase mounted cavalry cultivation and the Khanate's cavalry spirit-beast training (it breeds the war-horses from a spirit-beast lineage); maintains the Northern Ice Lane's Bei-side anchor. Near-vassal of the NorthSea (its sect master is always a NorthSea-trained cultivator). Cold with the Iron-Horse Sect (the long border war); cooperative with the Mammoth-Bone (joint deep-tundra patrol); cold with the Pearl-Tide (the Northern Ice Lane's anchors' territorial contest).",
    source: "doc 42 §5.5, doc 43 §2.13",
    relations: [
      { type: "VASSAL_OF", target: "sect.northsea", note: "near-vassalage; sect master always NorthSea-trained" },
      { type: "RIVAL_OF", target: "sect.iron_horse", note: "the long border war" },
      { type: "LOCATED_IN", target: "region.bei" },
    ],
    simulationHooks: ["combat","cultivation","politics","economy","migration"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.mammoth_bone",
    kind: "sect",
    name: "Mammoth-Bone Sect",
    nameHanzi: "巨骨宗",
    tags: ["great_sect","core_formation","bei","beast_mounted","yao_allied"],
    description: "Bei's yao-allied great sect at the deep tundra's edge. Sect master Patriarch Mammoth-Bone (巨骨上人), Core Formation, age 720, a human who married into the Frostfang Yao (his wife is a tiger-yao). 220 disciples (30 inner are yao from the Frostfang Yao). One spirit vein (the Deep Tundra Vein — its small size reflects its single-vein endowment and remote location); the Mammoth-Bone Grotto-Heaven (巨骨洞天, water-yin, 1:8, at the mammoth-bone central hall, 1,500 li north of Beicheng). Specialty: beast-mounted cultivation on mammoth-yao, yao-human diplomacy, the deep-tundra patrol. Independent of the NorthSea (its yao-alliance is independent of the NorthSea's human-focused tradition; the two consult on continental spirit-vein ecology). Cooperative with the Snowstrider; warm with the Redwood Canopy (cross-continental yao-allied correspondence, disciples exchanged every 60 years); formal with the Frostfang Yao elder-council, which approves its disciple roster.",
    source: "doc 42 §5.5, doc 43 §2.14",
    relations: [
      { type: "ALLIED_WITH", target: "sect.redwood_canopy", note: "cross-continental yao-allied correspondence" },
      { type: "LOCATED_IN", target: "region.bei" },
    ],
    simulationHooks: ["social","combat","cultivation","ecology","politics"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },
  {
    id: "sect.crystal_tide",
    kind: "sect",
    name: "Crystal-Tide Sect",
    nameHanzi: "晶潮宗",
    tags: ["great_sect","core_formation","undersea","deep_water","eastern_sea"],
    description: "The Eastern Sea's only undersea great sect, headquartered at the Crystal Palace (晶宮), a Foundation-Establishment-built compound at 600-li depth on the Eastern Sea's floor, anchored at the Crystal-Tide Grotto-Heaven (晶潮洞天, a water-phase pocket-world). Sect master Patriarch Crystal-Tide (晶潮上人), Core Formation late-stage, age 850, who has not surfaced in three centuries. Specialty: water-phase deep-cultivation, abyssal yao-diplomacy (its sect master is the only surface cultivator who meets the Abyssal Yao Council, 深妖議會), and deep-water spirit-herb gathering (harvesting the abyssal herb-beds under a 700-year quota-treaty). A Pearl Archipelago Compact signatory — it maintains the Archipelago's undersea defenses but may not surface-claim any island, the Compact's most fragile clause. Tense with the Pearl-Tide (the Eastern Sea's spirit-herb beds); cooperative with the Whale-Rider (shared deep-water ecology).",
    source: "doc 42 §6.3",
    relations: [
      { type: "RIVAL_OF", target: "sect.pearl_tide", note: "Eastern Sea spirit-herb beds" },
      { type: "ALLIED_WITH", target: "sect.whale_rider", note: "shared deep-water ecology" },
      { type: "LOCATED_IN", target: "cosmological.mortal_world", note: "Eastern Sea floor at 600-li depth" },
    ],
    simulationHooks: ["ecology","trade","politics","cultivation","combat"],
    renderProfile: "location_sect_mountain",
    version: "0.1.0",
  },

  // ============================ INSTITUTIONS ============================

  {
    id: "institution.great_yan",
    kind: "institution",
    name: "Great Yan Dynasty",
    nameHanzi: "大燕朝",
    tags: ["empire","mortal","zhong","declining"],
    description: "The largest continent's largest empire, founded 247 years ago. Reigning emperor Yan Sizong (燕嗣宗), 14th emperor, in the 14th year of the Jianhe reign (建和十四年); imperial seat Yanjing (燕京), 5,400 li northwest of Wang Family Bend, in the middle reaches of the Yan River. The Heavenly Pivot Sect is the empire's favored great sect. In middle decline: bloated bureaucracy, stretched military, the eunuch faction (Grand Eunuch Wei Zhongxian) versus the literati faction (Chief Grand Secretary Li Tingyun), and an aging emperor with no designated heir — the succession crisis is the empire's open secret. The Azure Sword Sect, 500 li north of the Cangli Riverlands, is too peripheral to matter at court.",
    source: "doc 42 §1.1, doc 36 §2.5",
    relations: [
      { type: "LOCATED_IN", target: "region.zhong" },
      { type: "CONTAINS", target: "sect.heavenly_pivot", note: "favored great sect" },
    ],
    simulationHooks: ["politics","history","economy","social"],
    version: "0.1.0",
  },
  {
    id: "institution.yueling_dynasty",
    kind: "institution",
    name: "Yueling Dynasty",
    nameHanzi: "月菱朝",
    tags: ["empire","mortal","dong","foundation_establishment_throne"],
    description: "Dong's largest mortal empire, founded 1,100 years ago on the central lowlands' alluvial plain. Reigning monarch Yueling Lingxi (月菱菱汐), 23rd monarch, in the 60th year of the Qingxiao reign (清嘯六十年) — a 130-year-old Foundation Establishment cultivator, one of the few mortals who ascends to a sect-supported throne. Structure is hybrid: the throne is mortal-hereditary but the monarch must be Foundation Establishment, and the imperial council includes the three leading great sects' sect masters as voting peers. Capital Qingyuan (青苑), on the central lowlands' great river. The Jade Void Holy Land is the Yueling's traditional protector; the throne's Foundation Establishment requirement is enforced in practice by Jade Void elders. Trades with the Great Yan through the Vermilion Pearl Route; the two have never been to war.",
    source: "doc 42 §2.2",
    relations: [
      { type: "LOCATED_IN", target: "region.dong" },
      { type: "VASSAL_OF", target: "sect.jade_void", note: "traditional protector; throne requirement enforced by Jade Void elders" },
    ],
    simulationHooks: ["politics","history","economy","trade"],
    version: "0.1.0",
  },
  {
    id: "institution.ironbone_confederacy",
    kind: "institution",
    name: "Ironbone Confederacy",
    nameHanzi: "鐵骨盟",
    tags: ["confederacy","xi","citadels","mutual_defense"],
    description: "Xi's political structure: a federation of forty-three mountain-clan citadels, each ruled by a Core Formation patriarch or matriarch, meeting in council every twelve years at the citadel of Tiegufeng (鐵骨峰), the nominal capital. Current Council Chair Matriarch Ironbone (鐵骨道君), Core Formation late-stage, age 890, the citadel's hereditary ruler. Law is the Ironbone Compact (鐵骨約), a 2,400-year-old mutual-defense oath — an attack on one citadel is an attack on all; the Council elects a War-Chair for the duration of a crisis. Suzerain-to-vassal relationship with the Skyfire Holy Land (citadels pay an annual tithe of refined metal; the Skyfire trains the Core Formation smiths). Relationship to the Great Yan nonexistent; to the Yueling, a single trade route.",
    source: "doc 42 §3.2",
    relations: [
      { type: "LOCATED_IN", target: "region.xi" },
      { type: "VASSAL_OF", target: "sect.skyfire", note: "annual tithe of refined metal; forge-elders train the smiths" },
      { type: "CONTAINS", target: "sect.ironbone" },
    ],
    simulationHooks: ["politics","combat","history","economy"],
    version: "0.1.0",
  },
  {
    id: "institution.monsoon_cities",
    kind: "institution",
    name: "Monsoon Cities",
    nameHanzi: "季風諸城",
    tags: ["city_states","nan","trade","monsoon"],
    description: "Nan's coastal civilization: a network of seventeen trading city-states linked by the monsoon-cycle sail routes, governed by the loose Monsoon Council (季風議會), which meets annually at the city of Nanhai (南海), the largest port; the Council's chair rotates among the Cities' merchant-princes. The Sea-Fan Sect is the Council's enforcement arm. Trade with the yao of the jungle interior (the Pillar Descendants) at the city of Linwang (林王), the only place on Nan where yao and humans meet regularly as peers.",
    source: "doc 42 §4.2",
    relations: [
      { type: "LOCATED_IN", target: "region.nan" },
      { type: "CONTAINS", target: "sect.sea_fan", note: "enforcement arm" },
    ],
    simulationHooks: ["trade","politics","economy","social"],
    version: "0.1.0",
  },
  {
    id: "institution.black_ice_khanate",
    kind: "institution",
    name: "Black-Ice Khanate",
    nameHanzi: "黑冰汗國",
    tags: ["khanate","bei","nomadic","pastoral"],
    description: "Bei's largest political structure: a nomadic-pastoral confederation that has unified the continent's central steppe for 600 years under the Black-Ice Borjigin clan. Reigning Khan Tengri-Iron (天鐵汗), age 90, a Foundation Establishment cultivator; the Khans' cultivation is water-phase and mounted, and the Khanate's elite cavalry are all Qi Condensation. Capital the Ordu (斡魯朵), a movable camp of 30,000 tents following the seasonal pastures; winters at Beicheng (北城), the Khanate's only permanent settlement, on the continent's southern coast. Foundation myth: the first Khan was a NorthSea Holy Land outer disciple who left to unite the steppe; the NorthSea trains the Foundation Establishment Khans and considers the Khanate's unity the continent's stabilizing force. Against the Great Yan, eleven border wars in 247 years, none decisive; 600-year cold peace with the Frostfang Yao.",
    source: "doc 42 §5.2",
    relations: [
      { type: "LOCATED_IN", target: "region.bei" },
      { type: "ALLIED_WITH", target: "sect.northsea", note: "the NorthSea trains the Khans" },
      { type: "RIVAL_OF", target: "institution.great_yan", note: "the long-running northern border war" },
      { type: "CONTAINS", target: "sect.snowstrider" },
    ],
    simulationHooks: ["politics","combat","economy","migration","history"],
    version: "0.1.0",
  },
  {
    id: "institution.courts_of_heaven",
    kind: "institution",
    name: "Courts of Heaven",
    nameHanzi: "天庭",
    tags: ["precelestial","apex_institution","records","oaths"],
    description: "The Precelestial institution with jurisdiction over records of the dead and heaven-sealed oaths — not a holy land and not a sect. Sits at the geographic center of the Precelestial, the densest-qi point of the densest stratum, the apex of the cosmic lens: a vast institutional landscape of palaces, archives, courtyards, and maintained roads (官道) radiating outward like spokes from a hub. Maintains a star-watch (司星) recording the stars' variation as intelligence on the Acquired Stratum's vein-economy. The Yellow Court and the Skyfire are its two allied holy lands (alchemical tithes; weapon-supply); the Jade Void is independent but deferential; the Verdant Pillar and the NorthSea are independent. The Mahayana law-authorship of the Transcend path requires the Courts' ratification.",
    source: "doc 36 §4.2, doc 43 §4.5, doc 12 §4.3",
    relations: [
      { type: "LOCATED_IN", target: "cosmological.precelestial_stratum" },
      { type: "ALLIED_WITH", target: "sect.yellow_court", note: "alchemical tithes" },
      { type: "ALLIED_WITH", target: "sect.skyfire", note: "traditional weapon-supplier" },
    ],
    simulationHooks: ["politics","ritual","history","perception","social"],
    version: "0.1.0",
  },
  {
    id: "institution.immortal_alliance",
    kind: "institution",
    name: "Immortal Alliance",
    nameHanzi: "仙盟",
    tags: ["treaty_organization","cultivation_world","dispute_resolution"],
    description: "The political structure of the cultivation world itself: a treaty organization, not a state — no territory, no citizens, no tax base. A set of oaths sworn by the great sects and holy lands to resolve disputes without open war, suppress demonic cultivation, enforce the taboo between cultivators and mortals, and allocate contested resources (grotto-heavens, newly discovered spirit veins, relics of fallen sects). Founded in the aftermath of the last great-sect war, which dispersed three spirit veins and produced a tribulation that leveled a mortal city. No capital: business is conducted at periodic assemblies (仙盟大會) at rotating neutral sites; a standing secretariat (盟府) of Foundation Establishment clerks handles correspondence and registers treaties but has no enforcement power. Weighted suffrage — the great powers' votes carry more weight. Dues from member sects are proportional to rank. The Azure Sword Sect holds a mid-tier seat (one of thirty in the eastern region).",
    source: "doc 12 §6, doc 43 §4.5",
    relations: [],
    simulationHooks: ["politics","history","social","economy"],
    version: "0.1.0",
  },

  // ============================ LINEAGES ============================

  {
    id: "lineage.wang",
    kind: "lineage",
    name: "Wang Lineage",
    nameHanzi: "王氏",
    tags: ["mortal_lineage","dominant","latent_cultivation_lineage"],
    description: "The dominant lineage of Wang Family Bend: 22 of the village's 31 households are Wang, tracing to a founder who settled the bend ~9 generations ago during a period of land reclamation; his tablet stands in the lineage hall (祠堂) as the founding ancestor. Lineage head Wang Shouzheng (王守正), 58, senior male of the senior branch, also the li head (tax collector) — the village's de facto leader; the elder council (5 men) meets in the hall on the 1st and 15th of each lunar month. Corporate body owning lineage fields (~8 mu), the lineage school (義學, taught by Wang Lun, 王倫, 41), the genealogy (族譜, updated annually at the winter solstice rite), and the lineage hall. After the protagonist's Foundation Establishment, a latent cultivation lineage — a mortal lineage that has produced its first cultivator of significant realm and is thereby on the path (across generations) to cultivation-lineage status (which formally requires a Nascent Soul cultivator whose anchor persists in bardo).",
    source: "doc 04 §2.1, doc 31 §1.10, doc 12 §2.1",
    relations: [
      { type: "LOCATED_IN", target: "location.wang_family_bend" },
      { type: "CONTAINS", target: "region.cangli_riverlands", note: "the lineage's branch-houses spread through the bend" },
    ],
    simulationHooks: ["social","politics","history","economy","ritual","reproduction"],
    version: "0.1.0",
  },

  // ============================ COSMOLOGICAL FEATURES ============================

  {
    id: "cosmological.mortal_world",
    kind: "cosmological_feature",
    name: "Mortal World",
    nameHanzi: "凡塵",
    tags: ["planet","mortal_stratum","single_world","earth_sized"],
    description: "The Mortal Stratum's single planet: a sphere with circumference ~36,000 li (~18,000 km) and diameter ~11,500 li — a finite, Earth-sized world, small enough to be circumnavigated by a Core Formation cultivator in a week of sustained flight. Sits at the center of the Mortal Stratum's horizontal extent; the densest material object in the cosmos. Five continents (Central, Eastern, Western, Southern, Northern) separated by oceans; no other planets, no other solar systems exist. Threaded by the surface traces of spirit veins descending from the Acquired Stratum above.",
    source: "doc 36 §2.1",
    relations: [
      { type: "CONTAINS", target: "region.zhong" },
      { type: "CONTAINS", target: "region.dong" },
      { type: "CONTAINS", target: "region.xi" },
      { type: "CONTAINS", target: "region.nan" },
      { type: "CONTAINS", target: "region.bei" },
      { type: "CONTAINS", target: "region.pearl_archipelago" },
      { type: "LOCATED_IN", target: "cosmological.mortal_stratum" },
    ],
    simulationHooks: ["physics","ecology","perception","migration"],
    version: "0.1.0",
  },
  {
    id: "cosmological.sun",
    kind: "cosmological_feature",
    name: "Sun",
    nameHanzi: "日",
    tags: ["qi_formation","fire_phase","yang","cloud_veil"],
    description: "A vast slow vortex of fire-phase and yang-dominant qi, condensed against the underside of the Cloud Veil and circling the Mortal World once per day — not a ball of gas but a ball of qi, the densest fire-phase qi in the Mortal Stratum. Its circuit is lawful: rises east, sets west, passes beneath the planet's horizon at night. Phase-peak at summer solstice, phase-trough at winter solstice. Not alive, not a god, not worshipped.",
    source: "doc 36 §2.2",
    relations: [{ type: "LOCATED_IN", target: "cosmological.mortal_stratum", note: "embedded in the Cloud Veil's underside" }],
    simulationHooks: ["weather","perception","ritual","ecology"],
    version: "0.1.0",
  },
  {
    id: "cosmological.moon",
    kind: "cosmological_feature",
    name: "Moon",
    nameHanzi: "月",
    tags: ["qi_formation","water_phase","yin","cloud_veil"],
    description: "A smaller, slower vortex of water-phase and yin-dominant qi, condensed against the Cloud Veil's underside, circling the Mortal World roughly once per month; its phases are the waxing and waning of its yin-density. The Moon's light is reflected yin-qi — cold, still, condensing. The Mid-Autumn full moon is the night when its yin-qi is densest at the Mortal surface; yin- and water-phase cultivators practice at midnight on the full moon for maximum effect. Not alive, not a god, not worshipped.",
    source: "doc 36 §2.2",
    relations: [{ type: "LOCATED_IN", target: "cosmological.mortal_stratum", note: "embedded in the Cloud Veil's underside" }],
    simulationHooks: ["weather","perception","ritual","cultivation"],
    version: "0.1.0",
  },
  {
    id: "cosmological.mortal_stratum",
    kind: "cosmological_feature",
    name: "Mortal Stratum",
    nameHanzi: "凡尘境",
    tags: ["stratum","lowest","diffuse_qi"],
    description: "The lowest of the three strata, occupying the lens's lower third — narrower than the Acquired but wider than the Precelestial, the diffuse-qi bottom of the cosmic lens. Contains the Mortal World (the one planet), the Sun and Moon (luminous qi-formations on the Cloud Veil's underside), the stars (pinhole-leaks of Acquired qi), the grotto-heaven anchors, and the Cloud Veil's underside as its sky. The court operates here but cannot reach into the Acquired Stratum to police a Core Formation cultivator — the engine of the tension between mortal law and cultivation power.",
    source: "doc 36 §1.1, doc 12 §0",
    relations: [
      { type: "CONTAINS", target: "cosmological.mortal_world" },
      { type: "CONTAINS", target: "cosmological.sun" },
      { type: "CONTAINS", target: "cosmological.moon" },
    ],
    simulationHooks: ["physics","perception","ecology","history"],
    version: "0.1.0",
  },
  {
    id: "cosmological.acquired_stratum",
    kind: "cosmological_feature",
    name: "Acquired Stratum",
    nameHanzi: "后天境",
    tags: ["stratum","middle","qi_medium","spirit_vein_rivers"],
    description: "The middle stratum, the lens's widest layer: a three-dimensional qi-medium — a vast luminous ocean of differentiated qi, denser than the Mortal ambient by a factor of one hundred to one thousand. The five phases differentiate fully; spirit veins are wide luminous rivers flowing through open space (wood green-gold, water deep blue, metal white-silver, fire red-orange, earth ochre-yellow). Contains the Broad Lands (廣地, full-sized Acquired regions too large to pocket), the grotto-heavens on the Lower Surface (下界, its boundary with the Cloud Veil), and the Acquired-condensations (後天凝光, its own drifting luminous bodies). Own weather: qi-storms, phase-fronts, yin-yang inversions.",
    source: "doc 36 §3",
    relations: [{ type: "CONTAINS", target: "place.jade_edge_grotto", note: "grotto-heavens sit on its Lower Surface" }],
    simulationHooks: ["physics","perception","cultivation","ecology"],
    version: "0.1.0",
  },
  {
    id: "cosmological.precelestial_stratum",
    kind: "cosmological_feature",
    name: "Precelestial Stratum",
    nameHanzi: "先天境",
    tags: ["stratum","uppermost","undifferentiated_qi","slow_time"],
    description: "The uppermost stratum, roughly one-tenth the Acquired's horizontal extent (~3 heaven-strides across) and the densest; qi undifferentiated, law not yet fixed, time running slow (1 Precelestial day ~ 1 Acquired year). Its sky is the inside of the cosmic lens's upper boundary — a slow luminous gray, no stars, no sun, no day-night cycle. Four geographic zones with relative positions: the Courts of Heaven at the geographic center (the densest-qi point of the cosmos), the Ancestral Courts (宗祠) scattered like islands, the Spirit Wilds (靈荒) filling the gaps between jurisdictions, and the Law Reaches (法域) at the edge where law is pending. Travel by maintained roads (官道), ancestral roads (宗道), or wild paths (荒徑).",
    source: "doc 36 §4",
    relations: [
      { type: "CONTAINS", target: "institution.courts_of_heaven" },
      { type: "LOCATED_IN", target: "cosmological.nameless_origin", note: "origin is not a place; this is a category marker only" },
    ],
    simulationHooks: ["physics","perception","cultivation","politics","history"],
    version: "0.1.0",
  },
  {
    id: "cosmological.cloud_veil",
    kind: "cosmological_feature",
    name: "Cloud Veil",
    nameHanzi: "雲幕",
    tags: ["stratum_boundary","mortal_acquired","qi_gradient","the_sky"],
    description: "The Mortal-Acquired stratum boundary: a qi-density gradient roughly 100 li thick at ~1,000 li altitude — the blue dome of day and the black field of night. To mortals it is the sky; opaque to mortal vision and impermeable to mortal flight. To a Foundation Establishment cultivator it is perceptible as a thickness; a Core Formation cultivator crosses it in about an hour, feeling like diving into water. The stars are Acquired qi leaking through it at points where spirit veins press upward.",
    source: "doc 36 §2.4, §5.1",
    relations: [
      { type: "CONTAINS", target: "cosmological.mortal_stratum", note: "forms the Mortal sky" },
      { type: "CONTAINS", target: "cosmological.acquired_stratum", note: "forms the Acquired Lower Surface" },
    ],
    simulationHooks: ["physics","perception","weather"],
    version: "0.1.0",
  },
  {
    id: "cosmological.heavenly_stem",
    kind: "cosmological_feature",
    name: "Heavenly Stem",
    nameHanzi: "天樞",
    tags: ["stratum_boundary","acquired_precelestial","law_state_discontinuity"],
    description: "The Acquired-Precelestial boundary: roughly 10 li thick but the densest, most law-saturated region in the cosmos; a law-state discontinuity where differentiated qi gives way to undifferentiated qi and inscribed law to pending law. Not crossable by force — a Core Formation cultivator attempting it is metabolized; only a Tribulation Crossing cultivator mid-tribulation can cross, when the tribulation proves their internal architecture can sustain the Precelestial's qi and the Stem admits them as a recognition.",
    source: "doc 36 §5.2",
    relations: [
      { type: "CONTAINS", target: "cosmological.acquired_stratum", note: "forms its upper boundary" },
      { type: "CONTAINS", target: "cosmological.precelestial_stratum", note: "forms its lower boundary" },
    ],
    simulationHooks: ["physics","perception","cultivation"],
    version: "0.1.0",
  },
  {
    id: "cosmological.outer_margin",
    kind: "cosmological_feature",
    name: "Outer Margin",
    nameHanzi: "外涯",
    tags: ["cosmos_edge","law_taper","the_edge_of_being"],
    description: "The edge of the cosmos, where the generative function's output has reached its limit. Not a wall or membrane: qi and law thin in a long slow taper — the inscriptions holding the world's regularities become sparser, fainter, less reliably enforced. A mortal sailor approaching it perceives the sky lowering and the air stilling; a Mahayana cultivator perceives the law-substrate ending, 'the way a sentence ends, with a period and then silence.' The lawful edge of being; beyond it is the Unwritten.",
    source: "doc 36 §1.2",
    relations: [{ type: "CONTAINS", target: "cosmological.unwritten", note: "what lies beyond" }],
    simulationHooks: ["physics","perception"],
    version: "0.1.0",
  },
  {
    id: "cosmological.unwritten",
    kind: "cosmological_feature",
    name: "The Unwritten",
    nameHanzi: "未書",
    tags: ["beyond_the_edge","pre_condition","not_a_place"],
    description: "Beyond the Outer Margin: the condition prior to the conditions of existence — the unresolved possibility of generation, the raw output of the generative function that has not yet condensed into anything. Not void, not chaos, not emptiness, not nothing. Not a place: one cannot go there or perceive it, because perception is a function of law and law has not been inscribed there. Distinct from the Nameless Origin: it is what the Origin's generative function has not yet generated.",
    source: "doc 36 §1.3",
    relations: [],
    simulationHooks: ["physics","perception"],
    version: "0.1.0",
  },
  {
    id: "cosmological.nameless_origin",
    kind: "cosmological_feature",
    name: "Nameless Origin",
    nameHanzi: "無名之始",
    tags: ["generative_function","not_a_place","dao_boundary"],
    description: "The generative function that makes the cosmos possible — not at the center, not at the edge, not beyond the edge, not 'everywhere' and not 'nowhere': not in the cosmos at all, because it is not an interior thing. The lens is the output; the Origin is the function. The project's hard commitment against the 'the Origin is a place you can go' trope: no cultivator can travel to it, no Mahayana law-authorship can write it, no being can become it. The absolute Dao boundary; honored by its absence from the map — the map shows the cosmos, the Origin is the frame around the map.",
    source: "doc 36 §1.4, §8.2",
    relations: [],
    simulationHooks: ["physics","cultivation","history"],
    version: "0.1.0",
  },
];
