/**
 * Stations 6-10 (upper realms) — canonically named beings, reaches, domains,
 * verbs, and the Transcend-ending event, mined from corpus docs 15, 30, 40, 45.
 *
 * Fidelity: only named things; numbers taken verbatim from the docs.
 * Doc 39's pantheon (as treated canonical by doc 45) is the source for the
 * nine Mahayana; doc 38 names for the council seats are NOT used here.
 */

import type { Definition } from '../definitions';

export const STATIONS_6_10_DEFINITIONS: Definition[] = [
  // ---------------------------------------------------------------------
  // SKILLS — named realm verbs (doc 30, "New verbs" per station)
  // ---------------------------------------------------------------------
  { id: "skill.project_spirit", kind: "skill", name: "Project Spirit", nameHanzi: "出神", tags: ["nascent_soul","station_6","projection","new_verb"], description: "Nascent Soul verb: the anchor leaves the body and acts at a distance — perceives, speaks in qi-modulations, leaves traces, performs rites. Range ~50-200 li initially, growing with practice; duration hours to days; the body in trance is undefended.", source: "doc 30 Station 6, New verbs", relations: [{ type: "REQUIRES", target: "realm.nascent_soul" }], simulationHooks: ["perception","cultivation","social","ritual"], version: "0.1.0" },
  { id: "skill.retrieve_bardo_anchor", kind: "skill", name: "Retrieve a Bardo Anchor", nameHanzi: "取陰", tags: ["nascent_soul","station_6","bardo","retrieval","rare"], description: "Nascent Soul verb: fetch a specific anchor from bardo before the window closes, preserving it and returning it to processing (lineage rite, ancestral court, sect soul-rite). Requires the retriever's projection to enter bardo; bardo is hostile to projected anchors. The protagonist's first retrieval left the projected anchor trembling for three days.", source: "doc 30 Station 6, New verbs; doc 45 Station 6", relations: [{ type: "REQUIRES", target: "realm.nascent_soul" }, { type: "REQUIRES", target: "skill.project_spirit" }], simulationHooks: ["perception","cultivation","ritual"], version: "0.1.0" },
  { id: "skill.open_domain", kind: "skill", name: "Open a Domain", nameHanzi: "開域", tags: ["spirit_severance","station_7","domain","sovereignty"], description: "Spirit Severance verb: the upper dantian externalizes as a bounded region (10-100 li radius) where the cultivator's will is partially lawful. The world gains a region that is, partially, the cultivator. The domain's opening triggers tribulation (doc 15 §6.2). The protagonist's domain-law at Li Family Creek: no anchor may be harvested here.", source: "doc 30 Station 7, New verbs", relations: [{ type: "REQUIRES", target: "realm.spirit_severance" }], simulationHooks: ["cultivation","physics","perception","politics"], version: "0.1.0" },
  { id: "skill.sever_attachment", kind: "skill", name: "Sever an Attachment", nameHanzi: "斬緣", tags: ["spirit_severance","station_7","irreversible","heart_mind"], description: "Spirit Severance verb: permanently release a specific emotional bond — love, grief, fear, hatred. Distinct from Foundation Establishment's integration (which transforms the bond) because severance destroys it; irreversible. The verb that gives Spirit Severance its name. Daoist Jade Void's counsel: sever rarely and with great deliberation.", source: "doc 30 Station 7, New verbs", relations: [{ type: "REQUIRES", target: "realm.spirit_severance" }, { type: "COUNTERS", target: "skill.integrate_disturbance", note: "destroys the bond where integration transforms it" }], simulationHooks: ["cultivation","deviation","social"], version: "0.1.0" },
  { id: "skill.bond_to_place", kind: "skill", name: "Bond to a Place", nameHanzi: "合地", tags: ["void_amalgamation","station_8","place_bond","earth_immortal"], description: "Void Amalgamation verb: bond to a grotto-heaven, sacred mountain, or region. The bond is permanent and mutual — the place becomes the cultivator's body; the cultivator becomes the place's will. Distinct from opening a domain: the cultivator does not create the bonded place; they join it. Does NOT trigger tribulation (doc 24 §1.10).", source: "doc 30 Station 8, New verbs", relations: [{ type: "REQUIRES", target: "realm.void_amalgamation" }], simulationHooks: ["cultivation","ecology","physics","aging"], version: "0.1.0" },
  { id: "skill.author_reach_law", kind: "skill", name: "Author a Reach Law", nameHanzi: "創法", tags: ["mahayana","station_10","reach_authorship","world_creation"], description: "Mahayana verb: write a rule that creates a new local substrate in the Precelestial's Law Reaches — a region where no law previously held. Creation, not amendment; the law created is the region's first law and the region becomes a mini-cosmos. The endgame's furthest reach; the Nameless Origin is untouched and new strata cannot be created.", source: "doc 30 Station 10, New verbs; doc 40 §5.3", relations: [{ type: "REQUIRES", target: "realm.mahayana" }, { type: "REQUIRES", target: "realm.tribulation_crossing", note: "stratum-travel is the substrate for Reach authorship" }], simulationHooks: ["cultivation","physics","history","politics"], version: "0.1.0" },

  // ---------------------------------------------------------------------
  // CUSTOM — named Spirit Severance domains (doc 45 Station 7)
  // ---------------------------------------------------------------------
  { id: "custom.hidden_domain", kind: "custom", name: "Daoist Jade Void's Withdrawn Domain", nameHanzi: "隱域", tags: ["spirit_severance","domain","wood_phase","yue_range","protection"], description: "A small wood-phase domain, ~30 li across, opened eight hundred years ago in the Yunwu Range's eastern slope — the only Spirit Severance domain in the Jade Void's territory. Its law: no anchor may be harvested here, world-enforced for eight centuries. The protagonist's first model for what a Spirit Severance domain can do.", source: "doc 45 Station 7, PLACES §1", relations: [{ type: "REQUIRES", target: "realm.spirit_severance" }, { type: "HELD_BY", target: "npc.daoist_jade_void" }], simulationHooks: ["physics","perception","politics","ritual"], version: "0.1.0" },
  { id: "custom.harvest_domain", kind: "custom", name: "Pei Liang's Intended Harvest-Domain", nameHanzi: "奪樞域", tags: ["spirit_severance","domain","anchor_harvest","antagonist"], description: "The domain Pei Liang plans to open at the Cangwu Mountains' latent spirit vein at his Spirit Severance breakthrough. Intended law: anchor-harvesting is lawful within this domain — making his crime his jurisdiction. Does not exist at the protagonist's confrontation; perceived as a potential, a law-structure prepared for 150 years, its residue-feel cold, hungry, full of small absences.", source: "doc 45 Station 7, PLACES §5", relations: [{ type: "REQUIRES", target: "realm.spirit_severance" }, { type: "WILLED_BY", target: "npc.pei_liang" }, { type: "CONTESTED_BY", target: "custom.hidden_domain", note: "the two domains, if both inscribed, will contest" }], simulationHooks: ["physics","perception","politics","deviation"], version: "0.1.0" },
  { id: "custom.forest_last_sap", kind: "custom", name: "Forest of the Last Sap", nameHanzi: "末汁之林", tags: ["spirit_wilds","domain_haunt","yao","dispersal","pilgrimage"], description: "The Pillar Lord of the Last Sap's voluntary dispersal-site (doc 41 §3.5), Southern Spirit Wilds above Nan Continent: a wood-phase domain-haunt where a Spirit Severance-tier yao-cultivator chose dispersal eight thousand years ago rather than outlive his dying dynasty's sustaining vein. The trees are his descendants — Last-Sap Trees (末汁樹), each a cultivator practicing the slow wood-phase descent he taught. Teaches that a cultivator can choose to disperse their own domain.", source: "doc 45 Station 7, PLACES §6", relations: [{ type: "REQUIRES", target: "realm.spirit_severance" }], simulationHooks: ["ecology","history","ritual","perception"], version: "0.1.0" },

  // ---------------------------------------------------------------------
  // CUSTOM — the nine Law Reaches (doc 40 §2; doc 45 Station 10 PLACES)
  // ---------------------------------------------------------------------
  { id: "custom.reach.sundered_stratum", kind: "custom", name: "Reach of the Sundered Stratum", nameHanzi: "斷層法域", tags: ["law_reach","largest","sealed","sundering_scar","fourth_stratum"], description: "The largest reach, ~2,000 li across, the Sundering's scar along the Precelestial's outer ring. Qi is traumatized — a Mahayana cultivator perceives a low continuous keening, like a struck bell ringing for eight thousand years. The Fourth-Stratum Attempt's seal (Gu Wu's coalition-authorship with the six founders, 8,000 years ago) holds at its center — the cosmos's most consequential maintained law. Sealed zone; below Mahayana, the keening disperses within hours. The protagonist never enters it.", source: "doc 40 §2.1; doc 45 Station 10 PLACES §3", relations: [{ type: "SEALS", target: "event.fourth_stratum_attempt", note: "the Fourth-Stratum Attempt's Residue, sealed 8,000 years ago" }], simulationHooks: ["physics","history","perception","politics"], version: "0.1.0" },
  { id: "custom.reach.caged_sky", kind: "custom", name: "Reach of the Caged Sky", nameHanzi: "籠天法域", tags: ["law_reach","prison","sky_devouring_beast","seal"], description: "The prison, ~500 li across in the Precelestial's southern interior — the only reach not on the outer ring. The Sky-Devouring Beast (吞天獸) was sealed here 3,000 years ago by a coalition of three Mahayana; the Seal of the Caged Sky (籠天封) is layered and the most fragile maintained law in the cosmos after the Fourth-Stratum Attempt's seal. Held by the Jinghe (涇河氏) and Wuqiu (烏秋氏) lineages' Tribulation Crossing cultivators in five-hundred-year shifts; ~1,200-1,500 years remain before seal failure. Qi is eaten — a continuous low draw toward the cage.", source: "doc 40 §2.2", relations: [{ type: "SEALS", target: "event.sky_devouring_beast_sealing" }], simulationHooks: ["physics","perception","politics","history"], version: "0.1.0" },
  { id: "custom.reach.held_silence", kind: "custom", name: "Reach of the Held Silence", nameHanzi: "默持法域", tags: ["law_reach","mo_shen","neutral_ground","pre_sundering"], description: "Mo Shen's holding, ~300 li across in the deep Precelestial's central interior — one of the two reaches the Sundering did not create. The cleanest undifferentiated qi in the cosmos; the silence is so profound it has weight, full of the possibility of law. No law has been inscribed for nine thousand years, by Mo Shen's deliberate choice; the Council of Nine convenes here because no Mahayana's law holds here. Stable and slowly healing by presence.", source: "doc 40 §2.3; doc 45 Station 10 PLACES §2", relations: [{ type: "HELD_BY", target: "npc.mo_shen" }], simulationHooks: ["physics","perception","politics","history"], version: "0.1.0" },
  { id: "custom.reach.cleaving", kind: "custom", name: "Reach of the Cleaving", nameHanzi: "裂法法域", tags: ["law_reach","lie_fa","ruins","recursion_risk"], description: "Lie Fa's ruins: originally ~400 li across, currently an 80-li core of stable half-law surrounded by a larger zone of unstable fragments — Lie Fa's attempted Reach-law (殘法) paradoxed 3,000 years ago. The qi is fractured; reading the fragments induces the contagious recursion-perception that broke Lie Fa. The most dangerous text in the cosmos, locked behind a pantheon-maintained seal. Lie Fa's last lucid words: 'Author small. The cosmos is finite, and the finite is the only thing that can be loved.'", source: "doc 40 §2.4, §4; doc 45 Station 10 PLACES §4", relations: [{ type: "WOUND_OF", target: "npc.lie_fa" }], simulationHooks: ["physics","perception","history","deviation"], version: "0.1.0" },
  { id: "custom.reach.last_window", kind: "custom", name: "Reach of the Last Window", nameHanzi: "末窗法域", tags: ["law_reach","protagonist","transcend_ending","healing"], description: "The protagonist's reach, ~80 li across, roughly oval, at the Precelestial's outer ring corresponding horizontally to the Cangli Riverlands' upper stratum. Named by the protagonist for the bardo-window law the authorship amends. Qi is patient — waiting eight thousand years for inscription. The bardo-harvest-loophole amendment is inscribed here; the thinned substrate absorbs ~15% of the law-tribulation's paradox-propagation. After authorship the only reach (besides the Held Silence) that is healing.", source: "doc 40 §2.5, §3; doc 45 Station 10 PLACES §1", relations: [{ type: "SITE_OF", target: "event.bardo_harvest_loophole_amendment" }, { type: "PART_OF", target: "region.cangli_riverlands", note: "horizontal-coordinate correspondence with the Cangli Riverlands' upper stratum" }], simulationHooks: ["physics","history","perception","ritual"], version: "0.1.0" },
  { id: "custom.reach.wandering_edge", kind: "custom", name: "Reach of the Wandering Edge", nameHanzi: "游涯法域", tags: ["law_reach","you_wuya","origin_pull","outer_margin"], description: "You Wuya's approach, ~600 li across, narrow and elongated, extending from the Precelestial's outer ring outward toward the cosmic Outer Margin — the only reach that extends outward. Its outer tip is the closest any living being has come to the Origin's generative function without crossing into it. Qi is drawn — a continuous pull outward, toward the Unwritten. You Wuya walks it repeatedly; the reach is a place to die, expanding at ~1 li per Precelestial century.", source: "doc 40 §2.6; doc 45 Station 10 PLACES §9", relations: [{ type: "WALKED_BY", target: "npc.you_wuya" }], simulationHooks: ["physics","perception","migration","history"], version: "0.1.0" },
  { id: "custom.reach.mirror_tides", kind: "custom", name: "Reach of the Mirror Tides", nameHanzi: "鏡潮法域", tags: ["law_reach","oscillator","substrate_self_inscription","research"], description: "The oscillator, ~350 li across at the Precelestial's outer ring corresponding to Dong's northern shore. Its substrate-law oscillates between a half-inscribed and a half-dissolved state on a period of ~1 Precelestial day; the fragments are the substrate's own attempts at self-inscription, never the same content twice. Unclaimed by tacit agreement; Tu Nan maps it more than any other pantheon member. Home to the Tide-Singer of the Mirror Tides (鏡潮之鳴者), the only being that perceives the fragments as a single continuous text.", source: "doc 40 §2.7, §5.3; doc 45 Station 10 PLACES §7", relations: [{ type: "MAPPED_BY", target: "npc.tu_nan" }], simulationHooks: ["physics","perception","history","ecology"], version: "0.1.0" },
  { id: "custom.reach.empty_hourglass", kind: "custom", name: "Reach of the Empty Hourglass", nameHanzi: "空漏法域", tags: ["law_reach","time_trap","time_distortion"], description: "The time-trap, ~250 li across at the outer ring corresponding to the western continent's interior. Its time-debt is ~1:36,500 (1 reach-day = 100 Acquired years), fluctuating. Named by the pantheon after the third survey expedition — Tribulation Crossing cultivator Shi Kong (時空) — aged two hundred years in a single Precelestial day; the four subsequent surveying expeditions dispersed. Uninhabitable for authored law and for cultivators below Mahayana; expanding ~1 li per Precelestial century.", source: "doc 40 §2.8", relations: [], simulationHooks: ["physics","perception","aging","history"], version: "0.1.0" },
  { id: "custom.reach.sundered_breath", kind: "custom", name: "Reach of the Sundered Breath", nameHanzi: "斷息法域", tags: ["law_reach","bleeding_wound","thinning"], description: "The bleeding wound, ~1,000 li across at the outer ring corresponding to Nan's southern coast — the second-largest reach and the fastest-expanding (~3 li per Precelestial century). Its substrate loses ~1% of its total qi per Precelestial century, flowing outward toward the Unwritten; the perception is of loss, the Thinning concentrated. Per Yin Mu, the place where the Thinning is most clearly the cosmos's grief for itself. Contributes ~5% of the Precelestial's total Thinning-rate.", source: "doc 40 §2.9; doc 45 Station 10 PLACES §8", relations: [], simulationHooks: ["physics","perception","history","ecology"], version: "0.1.0" },

  // ---------------------------------------------------------------------
  // EVENTS — named historical events
  // ---------------------------------------------------------------------
  { id: "event.bardo_harvest_loophole_amendment", kind: "event", name: "The Bardo-Harvest Loophole Amendment", tags: ["transcend_ending","law_authorship","bardo_window","wang_xiaodi"], description: "The protagonist's Mahayana law, authored at the Reach of the Last Window (session ~1,500+): an anchor whose bardo-window has been extended by any means other than natural anchor-coherence is, upon the extension's discovery, immediately released to its lawful dispersal. Scope: the Cangli Riverlands, by precedent and pantheon-ratification the broader Acquired Stratum. Empties every harvest-store in scope lawfully — among them Wang Xiaodi's. The law-tribulation (form 3) is survived; Gu Wu, recognizing the amendment as the completion of their own work, disperses peacefully and the protagonist takes the chair. The law conserves qi-authority, marginally delaying the Thinning.", source: "doc 45 Station 10 CONFLICTS §2, THE PROTAGONIST'S EXPERIENCE; doc 40 §2.5, §3.2", relations: [{ type: "AMENDS", target: "custom.reach.last_window", note: "inscribed from the reach" }, { type: "SUCCEEDS", target: "npc.gu_wu", note: "Gu Wu disperses, recognizing the successor" }], simulationHooks: ["politics","history","ritual","cultivation"], version: "0.1.0" },

  // ---------------------------------------------------------------------
  // NPC_ROLES — doc 45 Station 6 BEINGS
  // ---------------------------------------------------------------------
  { id: "npc.daoist_jade_void", kind: "npc_role", name: "Daoist Jade Void", nameHanzi: "玉虛真人", tags: ["holy_land_patriarch","nascent_soul","jade_void_holy_land","age_2100","ally"], description: "Founder-patriarch of the Jade Void Holy Land, Nascent Soul, age 2,100: patient, withdrawn, grieving. Outlived nineteen successor-generations; declined Tribulation Crossing three times, judging his ancestral-veneration practice more stable at Nascent Soul. Maintains the rotating-shrine rite in the Cangli Riverlands, requiring his continuing anchor-perception. Meets the protagonist at session ~1,000, reads the grief for Wang Xiaodi in the protagonist's anchor, and offers library access and counsel without asking anything in return — the protagonist's primary institutional ally in Act 3.", source: "doc 45 Station 6 BEINGS §1, §4", relations: [{ type: "MEMBER_OF", target: "sect.jade_void", note: "founder-patriarch" }, { type: "DELEGATES_TO", target: "npc.mu_yunfeng", note: "administrative headship delegated four hundred years ago" }, { type: "AT_REALM", target: "realm.nascent_soul" }], simulationHooks: ["politics","social","ritual","history","aging","cultivation"], version: "0.1.0" },
  { id: "npc.mu_yunfeng", kind: "npc_role", name: "Elder Mu Yunfeng", nameHanzi: "穆雲峰", tags: ["acting_head","nascent_soul","jade_void_holy_land","age_800"], description: "Nascent Soul early-stage, age 800, acting head of the Jade Void Holy Land — the 17th-generation successor, delegated the administrative headship four hundred years ago. Competent, anxious, quietly envious of the patriarch's serenity. Manages the Jade Void's 3,000 disciples, 47 Foundation Establishment elders, and 3 Nascent Soul elders. Meets the protagonist first and assesses the vendetta against Pei Liang with an administrator's cold practicality.", source: "doc 45 Station 6 BEINGS §2", relations: [{ type: "MEMBER_OF", target: "sect.jade_void", note: "acting head" }, { type: "SUCCEEDED_TO", target: "npc.daoist_jade_void", note: "17th-generation successor, delegated headship" }, { type: "AT_REALM", target: "realm.nascent_soul" }], simulationHooks: ["politics","social","economy","aging","cultivation"], version: "0.1.0" },
  { id: "npc.daoist_yellow_court", kind: "npc_role", name: "Daoist Yellow Court", nameHanzi: "黃庭真人", tags: ["holy_land_patriarch","nascent_soul","yellow_court_holy_land","age_3400"], description: "Scholastic, hierarchical, slow — operates at the tempo of a 3,400-year-old institution; the Great Yan Dynasty's succession crisis is, for him, a brief inconvenience, the eighth such he has weathered. Nascent Soul late-stage, age 3,400. His compound's walls are lined with the alchemical recipes of eight predecessor dynasties. The protagonist meets him at session ~1,100, when the Yellow Court's records on the Crimson Vow Remnant's corrupted fire-phase tradition become relevant to identifying Pei Liang's technique.", source: "doc 45 Station 6 BEINGS §4", relations: [{ type: "MEMBER_OF", target: "sect.yellow_court", note: "patriarch" }, { type: "AT_REALM", target: "realm.nascent_soul" }], simulationHooks: ["politics","ritual","history","aging","cultivation"], version: "0.1.0" },
  { id: "npc.iron_sage", kind: "npc_role", name: "Patriarch Iron Sage", nameHanzi: "鐵聖上人", tags: ["holy_land_patriarch","nascent_soul","skyfire_holy_land","age_2800","forge"], description: "Of the Skyfire Holy Land on Xi Continent, Nascent Soul, age 2,800: taciturn, exacting, forge-ascetic. Has not spoken in council for three centuries; communicates in hammer-taps and qi-modulations. His forge-domain's law — metal forged here holds its edge for ten thousand cuts — makes the Skyfire's blades the cosmos's most sought-after weapons. The protagonist may commission a sword from him for the Pei Liang confrontation; the commission requires specifying, in hammer-tap language, the law the sword will enforce.", source: "doc 45 Station 6 BEINGS §5, Station 7 BEINGS §3", relations: [{ type: "MEMBER_OF", target: "sect.skyfire", note: "patriarch" }, { type: "AT_REALM", target: "realm.nascent_soul" }], simulationHooks: ["politics","trade","economy","aging","cultivation"], version: "0.1.0" },
  { id: "npc.daoist_pillar_canopy", kind: "npc_role", name: "Daoist Pillar Canopy", nameHanzi: "柱冠真人", tags: ["holy_land_patriarch","nascent_soul","verdant_pillar_holy_land","age_1700"], description: "Human co-founder of the Verdant Pillar Holy Land on Nan Continent, Nascent Soul, age 1,700: hybrid, patient, ecologically-minded. Governs jointly with the tree-yao Old Pillar; the two have not disagreed in 1,700 years. His grief is an ecologist's — the Pillar Root Vein Remnant (柱根脈餘) is dying and the seven Pillar Cities' ruins grow slower each century. The protagonist's primary source on the region's qi-economy's cosmic history.", source: "doc 45 Station 6 BEINGS §6, Station 7 BEINGS §4", relations: [{ type: "MEMBER_OF", target: "sect.verdant_pillar", note: "co-founder" }, { type: "ALLY_OF", target: "npc.old_pillar", note: "joint governance, no disagreement in 1,700 years" }, { type: "AT_REALM", target: "realm.nascent_soul" }], simulationHooks: ["ecology","politics","social","aging","cultivation","history"], version: "0.1.0" },
  { id: "npc.old_pillar", kind: "npc_role", name: "Old Pillar", nameHanzi: "老柱", tags: ["tree_yao","foundation_establishment","verdant_pillar_holy_land","age_3200"], description: "The tree-yao co-founder of the Verdant Pillar Holy Land, Foundation Establishment yao, age ~3,200 — the cultivation world's oldest non-Mahayana yao, and Spirit Severance-tier by presence: his 3,200 years of continuous wood-phase practice in the Pillar Root Vein Remnant give him a domain-perception a Spirit Severance cultivator perceives as a peer. Grieves the dying Pillar Root Vein as a personal illness. Speaks in qi-modulations through his bark; a single sentence takes a mortal day.", source: "doc 45 Station 6 BEINGS §6, Station 7 BEINGS §4", relations: [{ type: "MEMBER_OF", target: "sect.verdant_pillar", note: "co-founder" }, { type: "ALLY_OF", target: "npc.daoist_pillar_canopy" }, { type: "AT_REALM", target: "realm.foundation_establishment", note: "by realm; Spirit Severance-tier by presence" }], simulationHooks: ["ecology","aging","cultivation","social","history"], version: "0.1.0" },
  { id: "npc.matron_northsea", kind: "npc_role", name: "Matriarch NorthSea", nameHanzi: "北海道君", tags: ["holy_land_patriarch","nascent_soul","northsea_holy_land","age_3000"], description: "Of the NorthSea Holy Land on Bei Continent, Nascent Soul, age 3,000: cold, ancient, record-keeping — the cultivation world's oldest non-Mahayana being after the pantheon itself. Has watched Bei's mortals die for 3,000 years and remembers each lineage's name. Her ice-domain's law — the records inscribed in ice do not thaw — preserves the Ice-Record Hall's ancestral-court tablets; the law is her continuous act of reading. The protagonist does not meet her in the canonical narrative.", source: "doc 45 Station 6 BEINGS §7, Station 7 PLACES §3", relations: [{ type: "MEMBER_OF", target: "sect.northsea", note: "matriarch" }, { type: "AT_REALM", target: "realm.nascent_soul" }], simulationHooks: ["history","politics","ritual","aging","cultivation"], version: "0.1.0" },

  // ---------------------------------------------------------------------
  // NPC_ROLES — doc 45 Station 7 BEINGS
  // ---------------------------------------------------------------------
  { id: "npc.hermit_border_twilight", kind: "npc_role", name: "Hermit of the Border Twilight", nameHanzi: "邊薄隱者", tags: ["spirit_severance","border_twilight","age_4000","station_as_destination"], description: "An unnamed Spirit Severance cultivator, age ~4,000, who lives at the Border Twilight's edge where the wilds' undifferentiated qi thins into the Law Reaches' pending substrate. The only Spirit Severance cultivator who has lived four thousand years without bonding a place or attempting Tribulation Crossing. Has severed every attachment except his attachment to the Border Twilight itself — severing it would, he says, sever his perception of the cosmos's finitude, and the perception is his practice. Teaches that the station can be a destination, not just a transit.", source: "doc 45 Station 7 BEINGS §5", relations: [{ type: "AT_REALM", target: "realm.spirit_severance" }], simulationHooks: ["aging","perception","cultivation","deviation"], version: "0.1.0" },

  // ---------------------------------------------------------------------
  // NPC_ROLES — doc 45 Station 8 BEINGS (earth immortals)
  // ---------------------------------------------------------------------
  { id: "npc.elder_han_liang", kind: "npc_role", name: "Elder Han Liang", nameHanzi: "韓良真人", tags: ["void_amalgamation","earth_immortal","mount_qinglu","age_4200"], description: "A named earth immortal, one of perhaps twelve Void Amalgamation cultivators in the cosmos. Bonded Mount Qinglu (青露山), a small peak in Zhong's western interior, 3,800 years ago; has not manifested a flesh-body in 1,500 years. Speaks through the mountain's qi-modulations; counsel arrives, sometimes, weeks after the question. Remembers the dynasty that founded Yumen (fallen 1,200 years ago) as a recent event; the lineage's current patriarch is his twenty-third-generation descendant. His counsel: the refuge is also the tether.", source: "doc 45 Station 8 PLACES §4, BEINGS §1", relations: [{ type: "PART_OF", target: "region.zhong", note: "Mount Qinglu, Zhong's western interior" }, { type: "AT_REALM", target: "realm.void_amalgamation" }], simulationHooks: ["ecology","aging","politics","history","cultivation"], version: "0.1.0" },
  { id: "npc.matron_yun_shu", kind: "npc_role", name: "Matriarch Yun Shu", nameHanzi: "雲舒道君", tags: ["void_amalgamation","earth_immortal","grotto","age_3800"], description: "A named earth immortal, age 3,800. Bonded a small wood-phase grotto-heaven above the Nan Continent's central highlands 3,200 years ago — a pocket-world she did not create but joined; its law is perpetual autumn, leaves perpetually falling, never reaching the ground. The cosmos's most content earth immortal. Her counsel to any visitor: tend what you have been given; do not seek what you have not — by the pantheon's quiet assessment, the most practical Void Amalgamation-tier teaching in the cosmos.", source: "doc 45 Station 8 PLACES §5, BEINGS §2", relations: [{ type: "PART_OF", target: "region.nan", note: "grotto above the Nan highlands" }, { type: "AT_REALM", target: "realm.void_amalgamation" }], simulationHooks: ["ecology","aging","cultivation","history"], version: "0.1.0" },
  { id: "npc.daoist_stream_mountain", kind: "npc_role", name: "Daoist Stream-Mountain", nameHanzi: "流山真人", tags: ["void_amalgamation","earth_immortal","flowing_place","age_5100"], description: "The cosmos's oldest Void Amalgamation cultivator, age 5,100, and the only earth immortal not place-bound in his primary mode: he bonded the Cangli River's upper reaches 4,800 years ago — a bonded place that is a flowing river, not a fixed peak. Moves with the river's current from the Cangwu Mountains' snowmelt to the Eastern Sea's mouth, a continuous circuit taking one Acquired year per cycle. Speaks in the river's babble; his counsel: if you would bond a place, bond a place that moves; the stillness is the trap.", source: "doc 45 Station 8 BEINGS §3, THE PROTAGONIST'S EXPERIENCE", relations: [{ type: "PART_OF", target: "region.cangli_riverlands", note: "bonded the Cangli River's upper reaches" }, { type: "AT_REALM", target: "realm.void_amalgamation" }], simulationHooks: ["ecology","migration","aging","cultivation","history"], version: "0.1.0" },
  { id: "npc.sleeping_immortal_steppe", kind: "npc_role", name: "Sleeping Immortal of the Northern Steppe", nameHanzi: "北原睡仙", tags: ["void_amalgamation","earth_immortal","place_boredom","age_2900","cautionary"], description: "A cautionary case, age 2,900. Bonded a steppe-land on Bei Continent 2,400 years ago as a contemplative practice; the steppe's tempo claimed her. Has not manifested a flesh-body in 1,800 years, not spoken in 1,200; her qi-signature is faint and undifferentiated from the steppe's own. The cosmos's foremost example of the place-boredom heart-mind poison (doc 30 Station 8). Tended, in her sleep, by the Snowstrider Sect's outer disciples, who keep a small shrine at the steppe's center.", source: "doc 45 Station 8 BEINGS §4", relations: [{ type: "PART_OF", target: "region.bei", note: "the Northern Steppe" }, { type: "AT_REALM", target: "realm.void_amalgamation" }], simulationHooks: ["ecology","aging","deviation","ritual","history"], version: "0.1.0" },

  // ---------------------------------------------------------------------
  // NPC_ROLES — doc 45 Station 9 BEINGS (courts' ministers + broker)
  // ---------------------------------------------------------------------
  { id: "npc.yan_jue", kind: "npc_role", name: "Yan Jue", nameHanzi: "閻玦", tags: ["minister_of_records","tribulation_crossing","age_5200","obstacle"], description: "Minister of Records, 5,200 years old, Tribulation Crossing peak: cold, precise, slow to speak, slower to apologize. Has not manifested a flesh-body in eight hundred years. Protector of Scribe Yan's corruption — not complicit personally, but exposure would end the Yan clan's nine-thousand-year claim to Records posts; his defense, when challenged, is procedural: the Records department audits itself. The protagonist's primary obstacle to the audit petition.", source: "doc 45 Station 9 BEINGS §1", relations: [{ type: "MEMBER_OF", target: "institution.courts_of_heaven", note: "Minister of Records" }, { type: "PROTECTS", target: "npc.scribe_yan", note: "protection is structural, not personal" }, { type: "AT_REALM", target: "realm.tribulation_crossing" }], simulationHooks: ["politics","history","aging","social"], version: "0.1.0" },
  { id: "npc.tao_jingxi", kind: "npc_role", name: "Tao Jingxi", nameHanzi: "陶敬熙", tags: ["minister_of_adjudication","tribulation_crossing","age_4400","reform_bloc"], description: "Minister of Adjudication, 4,400 years old, Tribulation Crossing peak: principled, exhausted, qi-alcoholic (sustained on fermented grain-qi distillate the courts tolerate; his breath smells faintly of sorghum at every Council session). Has filed the Records audit petition every century for eight hundred years, blocked each time by Yan Jue. The protagonist's most powerful ally in the courts and the most compromised — his vote-trading with the Lineage Bloc costs the protagonist political capital with the Reform Bloc.", source: "doc 45 Station 9 BEINGS §3", relations: [{ type: "MEMBER_OF", target: "institution.courts_of_heaven", note: "Minister of Adjudication" }, { type: "ALLY_OF", target: "npc.kang_shu", note: "Reform Bloc" }, { type: "RIVAL_OF", target: "npc.yan_jue", note: "audit petitions blocked by Yan Jue for 800 years" }, { type: "AT_REALM", target: "realm.tribulation_crossing" }], simulationHooks: ["politics","history","aging","deviation"], version: "0.1.0" },
  { id: "npc.kang_shu", kind: "npc_role", name: "Kang Shu", nameHanzi: "康姝", tags: ["minister_of_roads","tribulation_crossing","age_1800","reform_bloc"], description: "Minister of Roads, 1,800 years old, Tribulation Crossing: efficient, ironic, secretly Reform Bloc. Keeps a private archive of every Minister's pedantry and reads from it at dinner parties; Yan Jue has not spoken to her socially in three hundred years. The first court official the protagonist meets at Tribulation Crossing; becomes the protagonist's primary ally in the flight across the courts' territory.", source: "doc 45 Station 9 BEINGS §4", relations: [{ type: "MEMBER_OF", target: "institution.courts_of_heaven", note: "Minister of Roads" }, { type: "ALLY_OF", target: "npc.tao_jingxi", note: "Reform Bloc" }, { type: "AT_REALM", target: "realm.tribulation_crossing" }], simulationHooks: ["politics","social","history","aging"], version: "0.1.0" },
  { id: "npc.gao_tieshan", kind: "npc_role", name: "Gao Tieshan", nameHanzi: "高鐵山", tags: ["minister_of_defense","tribulation_crossing","age_6800","wild_suppression"], description: "Minister of Defense, 6,800 years old, Tribulation Crossing peak: militaristic, suspicious, patient in the way of a general waiting for an enemy that has not yet arrived. Speaks in clipped clauses; considers eloquence a form of dishonesty. Has advocated the Wild Suppression campaign for four thousand years and been defeated each time, by cost. The protagonist's natural ally on the bardo-harvest issue, but will not act without Council authorization; his support is conditional and reluctant.", source: "doc 45 Station 9 BEINGS §5", relations: [{ type: "MEMBER_OF", target: "institution.courts_of_heaven", note: "Minister of Defense" }, { type: "AT_REALM", target: "realm.tribulation_crossing" }], simulationHooks: ["politics","combat","history","aging"], version: "0.1.0" },
  { id: "npc.xue_qingshi", kind: "npc_role", name: "Xue Qingshi", nameHanzi: "薛清石", tags: ["underworld_broker","tribulation_crossing","age_2000","rogue"], description: "The underworld-market broker, Tribulation Crossing, age 2,000: the rogue cultivator who supplies the harvest-operation by connecting Scribe Yan's falsified dispersals to demonic cultivator customers (doc 38 §6.3). Garrulous, ambitious only to retire to a grotto-heaven he has been building for a millennium, entirely indifferent to the moral weight of the anchors he brokers. Went rogue rather than take office two thousand years ago; his network includes Scribe Yan and Pei Liang. The protagonist must decide whether to prosecute him or flip him.", source: "doc 45 Station 9 BEINGS §9", relations: [{ type: "SUPPLIES", target: "npc.pei_liang", note: "connects falsified dispersals to customers" }, { type: "SUPPLIES", target: "npc.scribe_yan", note: "one of his network of discontented minor officials" }, { type: "AT_REALM", target: "realm.tribulation_crossing" }], simulationHooks: ["politics","trade","economy","social","history"], version: "0.1.0" },

  // ---------------------------------------------------------------------
  // NPC_ROLES — doc 45 Station 10 BEINGS (the pantheon of nine, doc 39 as canonical)
  // ---------------------------------------------------------------------
      { id: "npc.you_wuya", kind: "npc_role", name: "You Wuya", nameHanzi: "游無涯", tags: ["mahayana","the_wanderer","place_spirit_law","age_6000"], description: "The Wanderer, ~6,000 years old: curious, distant, generous, melancholic. Author of the place-spirit jurisdiction law (土地轄界法). Does not ratify the protagonist's law — not, by temperament, a coalition-builder. Visits the protagonist once in the Reach of the Last Window, says 'Walk it, later. The Reach is small but it is yours', and leaves. Walks the Reach of the Wandering Edge toward the Origin's edge; has not spoken directly to Lu Shen in eight hundred years, since a dispute over the tribulation-trigger law's application to a wild-path cultivator.", source: "doc 45 Station 10 BEINGS §3", relations: [{ type: "WALKS", target: "custom.reach.wandering_edge" }, { type: "RIVAL_OF", target: "npc.lu_shen", note: "no direct speech in 800 years since a dispute over the tribulation-trigger law" }, { type: "AT_REALM", target: "realm.mahayana" }], simulationHooks: ["migration","politics","history","perception"], version: "0.1.0" },
        { id: "npc.mo_shen", kind: "npc_role", name: "Mo Shen", nameHanzi: "默深", tags: ["mahayana","the_hermit","no_law_authored","age_9000"], description: "The Hermit, ~9,000 years old: silent, kind, enigmatic. The only Mahayana who has not authored a law — his restraint is his contribution. Has held the Reach of the Held Silence for nine thousand years (longer than it has been named). Visits the protagonist once, sits in silence for a Precelestial day (= an Acquired year), and leaves without speaking; the silence is the teaching. Sits with Gu Wu once per Precelestial year — six thousand years of annual silence, the pantheon's longest-running practice. His holding is a presence, not an authorship.", source: "doc 45 Station 10 BEINGS §7", relations: [{ type: "HELD_BY", target: "custom.reach.held_silence" }, { type: "COMPANION_OF", target: "npc.gu_wu", note: "annual silence together for six thousand years" }, { type: "AT_REALM", target: "realm.mahayana" }], simulationHooks: ["history","politics","aging","perception"], version: "0.1.0" },
    { id: "npc.lie_fa", kind: "npc_role", name: "Lie Fa", nameHanzi: "裂法", tags: ["mahayana","the_fallen","fractured_anchor","age_indeterminate"], description: "The Fallen, age indeterminate: fragmented, lucid in flashes, in agony. Attempted to mimic the Nameless Origin's generative function within a single reach; the law paradoxed recursively, and the paradox was at the level of what perception itself is. His fractured anchor — the closest thing the Reach of the Cleaving has to a holder — persists half in the reach's collapsed core, half in the Precelestial; lucid moments come approximately once per Precelestial year. His cautionary instruction, the protagonist's final teaching before authoring: 'Author small. The cosmos is finite, and the finite is the only thing that can be loved.'", source: "doc 45 Station 10 BEINGS §9; doc 40 §2.4, §4.2", relations: [{ type: "WOUND_OF", target: "custom.reach.cleaving" }, { type: "AT_REALM", target: "realm.mahayana" }], simulationHooks: ["deviation","history","perception","aging"], version: "0.1.0" },
];
