/**
 * Techniques wiki layer — combat techniques, cultivation practices, and
 * station-gated skills mined from corpus docs 27, 32, 13, and 03.
 *
 * Fidelity contract: every entry is NAMED in the cited doc with exact
 * stats (frames, qwu, effects, counters, failure modes, root gates).
 * No invented techniques; no invented numbers.
 *
 * Pre-existing core techniques (route_qi, burning_palm, mortal_strike,
 * water_shield) are NOT duplicated here — they are referenced via relations.
 */

import type { Definition } from '../definitions';

export const TECHNIQUE_DEFINITIONS: Definition[] = [
  // -----------------------------------------------------------------------
  // Doc 32 §3.1 — Mortal (no qi, frame-cost only)
  // -----------------------------------------------------------------------
  { id: "technique.rice_seed_punch", kind: "technique", name: "Rice-Seed Punch", nameHanzi: "稻種拳", tags: ["mortal","unarmed","fast","physical"], description: "Mortal blunt strike with no phase or routing. Fast 8/4/8 frames (20 total), 400 J. Counter: block (medium). Failure: stamina -10, tempo fatigue +4 frames.", source: "doc 32 §3.1", relations: [{ type: "REQUIRES", target: "realm.mortal" }], simulationHooks: ["combat","physics"], version: "0.1.0" },
  { id: "technique.levee_stance", kind: "technique", name: "Levee Stance", nameHanzi: "堤步", tags: ["mortal","defensive","heavy","physical"], description: "Mortal braced block. Heavy 12/8/24 frames (44 total); halves incoming blunt damage during active frames. Counter: feint then strike. Failure: locked in stance, cannot pursuit.", source: "doc 32 §3.1", relations: [{ type: "REQUIRES", target: "realm.mortal" }], simulationHooks: ["combat","physics"], version: "0.1.0" },
  { id: "technique.river_eel_dodge", kind: "technique", name: "River-Eel Dodge", nameHanzi: "河鰻閃", tags: ["mortal","mobility","fast","physical"], description: "Mortal ducking side-step. Fast 6/2/8 frames (16 total); +50% dodge distance. Counter: low strike. Failure: lands off-balance, +6 recovery.", source: "doc 32 §3.1", relations: [{ type: "REQUIRES", target: "realm.mortal" }], simulationHooks: ["combat","physics"], version: "0.1.0" },
  { id: "technique.sickle_reap", kind: "technique", name: "Sickle Reap", nameHanzi: "鐮割", tags: ["mortal","tool_weapon","medium","physical"], description: "Mortal cut with a farm tool. Medium 10/6/14 frames (30 total), 600 J slash. Counter: parry (medium). Failure: tool stuck in cloth, disarmable.", source: "doc 32 §3.1", relations: [{ type: "REQUIRES", target: "realm.mortal" }], simulationHooks: ["combat","physics"], version: "0.1.0" },

  // -----------------------------------------------------------------------
  // Doc 32 §3.2 — Qi Induction (qi-perception enhancing mortal verbs)
  // -----------------------------------------------------------------------
  { id: "technique.tell_read", kind: "technique", name: "Tell-Read", nameHanzi: "讀勢", tags: ["qi_induction","perception","committed","attention_cost"], description: "Medium 10/4/8 frames (22 total); +30% perception of opponent's next action; consumes 15 attention. Counter: feint. Failure: perception burn — headache, nosebleed, -50% perception for 60 sec.", source: "doc 32 §3.2", relations: [{ type: "REQUIRES", target: "realm.qi_induction" }, { type: "ENHANCES", target: "essence.qi" }], simulationHooks: ["combat","perception"], version: "0.1.0" },
  { id: "technique.qi_watch", kind: "technique", name: "Qi-Watch", nameHanzi: "觀氣", tags: ["qi_induction","perception","heavy","reservoir_read"], description: "Heavy 20/0/30 frames (50 total); reads opponent's reservoir state and phase-affinity. Counter: interrupt (any hit). Failure: temporary blindness, 10 sec.", source: "doc 32 §3.2", relations: [{ type: "REQUIRES", target: "realm.qi_induction" }, { type: "ENHANCES", target: "essence.qi" }], simulationHooks: ["combat","perception"], version: "0.1.0" },
  { id: "technique.echo_step", kind: "technique", name: "Echo Step", nameHanzi: "回響步", tags: ["qi_induction","mobility","fast","perception_bonus"], description: "Fast 6/2/8 frames (16 total); dodge with qi-perception bonus; +20% accuracy on next attack. Counter: faster strike. Failure: misread — hit lands anyway, no dodge.", source: "doc 32 §3.2", relations: [{ type: "REQUIRES", target: "realm.qi_induction" }, { type: "ENHANCES", target: "essence.qi" }], simulationHooks: ["combat","perception","physics"], version: "0.1.0" },

  // -----------------------------------------------------------------------
  // Doc 32 §3.3 — Qi Condensation (first routing; root gates per §3.6)
  // -----------------------------------------------------------------------
  { id: "technique.river_circling_step", kind: "technique", name: "River-Circling Step", nameHanzi: "河旋步", tags: ["water_phase","legs_routing","mobility","qi_condensation"], description: "Water-routed Legs mobility. Fast 6/2/8 frames (16 total), 4 qwu; +50% dodge; qi-trail grants allies +20% accuracy for 2 ticks. Counter: wood-routed pursuit. Failure: water-stagnation (route fixation) if held >60 frames. Root gate: water.sensitivity >= 0.4 and water.admission >= 0.3.", source: "doc 32 §3.3, doc 32 §3.6", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "ENHANCES", target: "essence.water" }, { type: "RISKS", target: "deviation.route_fixation" }], simulationHooks: ["combat","physics","perception"], renderProfile: "technique_river_circling_step", version: "0.1.0" },
  { id: "technique.metal_edge_fist", kind: "technique", name: "Metal-Edge Fist", nameHanzi: "金刃拳", tags: ["metal_phase","hands_routing","armor_pierce","bleed","qi_condensation"], description: "Metal-routed Hands strike. Medium 10/6/14 frames (30 total), 8 qwu; AP ignores x2 blunt resistance; bleed 1 qwu per tick until treated. Counter: fire-routed defense (x1.3 vs metal). Failure: metal-rigidity (cross-current) if switched into too fast. Root gate: metal.sensitivity >= 0.5 and metal.conversion >= 0.4.", source: "doc 32 §3.3, doc 32 §3.6", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "ENHANCES", target: "essence.metal" }, { type: "RISKS", target: "deviation.cross_current" }], simulationHooks: ["combat","physics","deviation"], version: "0.1.0" },
  { id: "technique.wood_root_stance", kind: "technique", name: "Wood-Root Stance", nameHanzi: "木根樁", tags: ["wood_phase","skin_routing","defensive","heal","qi_condensation"], description: "Wood-routed Skin defense. Heavy 20/8/24 frames (52 total), 12 qwu; +200% posture threshold; heals 1 qwu per tick for 5 ticks after being hit. Counter: metal-routed cutting (x1.3). Failure: wood-fixation (borrowed signature adhesion); roots drain soil. Root gate: wood.admission >= 0.4 and wood.conversion >= 0.3.", source: "doc 32 §3.3, doc 32 §3.6", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "ENHANCES", target: "essence.wood" }, { type: "COUNTERED_BY", target: "technique.metal_edge_fist" }, { type: "RISKS", target: "deviation.borrowed_signature" }], simulationHooks: ["combat","physics","deviation"], version: "0.1.0" },
  { id: "technique.earth_press_slam", kind: "technique", name: "Earth-Press Slam", nameHanzi: "土壓砸", tags: ["earth_phase","hands_routing","crowd_control","stagger","qi_condensation"], description: "Earth-routed Hands slam. Heavy 20/8/24 frames (52 total), 15 qwu; 5 m radius stagger; stagger extends 1.2x. Counter: air dodge (Legs routing). Failure: earth-heaviness (breath-motion desync); -10% max speed for 60 sec. Root gate: earth.sensitivity >= 0.4 and earth.conversion >= 0.4.", source: "doc 32 §3.3, doc 32 §3.6", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "ENHANCES", target: "essence.earth" }, { type: "COUNTERED_BY", target: "technique.river_circling_step" }, { type: "RISKS", target: "deviation.breath_desync" }], simulationHooks: ["combat","physics","deviation"], version: "0.1.0" },
  { id: "technique.trace_anchor", kind: "technique", name: "Trace Anchor", nameHanzi: "留痕", tags: ["senses_routing","tracking","qi_trace","qi_condensation"], description: "Senses-routed trace (no phase). Heavy 20/4/30 frames (54 total), 5 qwu; leaves a qi-trace at a location persisting 24 hr. Counter: read then destroy. Failure: trace decays instantly if reservoir <20 qwu.", source: "doc 32 §3.3", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "ENHANCES", target: "essence.qi" }], simulationHooks: ["combat","perception","history"], renderProfile: "technique_trace_anchor", version: "0.1.0" },

  // -----------------------------------------------------------------------
  // Doc 32 §3.4 — Foundation Establishment
  // -----------------------------------------------------------------------
  { id: "technique.oath_of_restraint", kind: "technique", name: "Oath of Restraint", nameHanzi: "受職 — 約誓", tags: ["foundation_establishment","oath","social","ritual"], description: "Ritual 60/0/30 frames (90 total), 50 qwu; a qi-bound promise (any routing) whose breaker suffers reservoir contamination and deviation risk. Counter: outlast oath scope. Failure: oath-break backlash — -50% reservoir, xinmo risk.", source: "doc 32 §3.4", relations: [{ type: "REQUIRES", target: "realm.foundation_establishment" }, { type: "ENHANCES", target: "essence.qi" }], simulationHooks: ["combat","social","politics","ritual","deviation"], version: "0.1.0" },
  { id: "technique.five_phase_cascade", kind: "technique", name: "Five-Phase Cascade", nameHanzi: "五段連擊", tags: ["five_phase","hands_routing","combo","foundation_establishment"], description: "Hands-routed cycle wood to fire to earth to metal to water. 5x (12/6/16) = 170 total frames, 60 qwu; each strike boosted by the generation-previous phase (+15% per step). Counter: predict the cycle, defend with conquering phase. Failure: cross-current; forced switch lock. Root gate: all five phases' sensitivity >= 0.3.", source: "doc 32 §3.4, doc 32 §3.6", relations: [{ type: "REQUIRES", target: "realm.foundation_establishment" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "ENHANCES", target: "essence.qi" }, { type: "RISKS", target: "deviation.cross_current" }], simulationHooks: ["combat","physics","deviation"], version: "0.1.0" },
  { id: "technique.heart_mind_blade", kind: "technique", name: "Heart-Mind Blade", nameHanzi: "心劍", tags: ["xin_based","hands_routing","psychospiritual","foundation_establishment"], description: "Xin-based Hands strike (no phase). Medium 10/6/14 frames (30 total), 20 qwu; strikes the opponent's heart-mind state and bypasses physical defense. Counter: high emotional-balance defender. Failure: rebounds on attacker; xinmo risk. Gate: no root gate; requires heart_mind.attention >= 0.6.", source: "doc 32 §3.4, doc 32 §3.6", relations: [{ type: "REQUIRES", target: "realm.foundation_establishment" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "REQUIRES", target: "practice.xinggong", note: "attention dimension gate (heart_mind.attention >= 0.6)" }], simulationHooks: ["combat","perception","deviation","social"], version: "0.1.0" },
  { id: "technique.foundation_pillar", kind: "technique", name: "Foundation Pillar", nameHanzi: "基柱", tags: ["earth_phase","skin_routing","immovable","foundation_establishment"], description: "Earth-routed Skin ritual. Ritual 40/0/30 frames (70 total), 80 qwu; immovable stance for 30 sec; doubles meridian throughput. Counter: bypass with Legs routing. Failure: foundation collapse if disrupted; rare, severe.", source: "doc 32 §3.4", relations: [{ type: "REQUIRES", target: "realm.foundation_establishment" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "ENHANCES", target: "essence.earth" }, { type: "COUNTERED_BY", target: "technique.river_circling_step" }], simulationHooks: ["combat","physics","cultivation"], version: "0.1.0" },
  { id: "technique.meridian_deep_read", kind: "technique", name: "Meridian-Deep Read", nameHanzi: "深脈讀", tags: ["senses_routing","perception","diagnostic","foundation_establishment"], description: "Senses-routed read (no phase). Heavy 20/0/20 frames (40 total), 15 qwu; reads opponent's meridian state, revealing injuries and deviations. Counter: disguise meridian state (advanced). Failure: perception overload — -30% perception for 1 hr.", source: "doc 32 §3.4", relations: [{ type: "REQUIRES", target: "realm.foundation_establishment" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "ENHANCES", target: "essence.qi" }], simulationHooks: ["combat","perception","deviation"], version: "0.1.0" },

  // -----------------------------------------------------------------------
  // Doc 32 §3.5 — Core Formation (treasure-assisted, self-sustaining)
  // -----------------------------------------------------------------------
  { id: "technique.golden_sun_lance", kind: "technique", name: "Golden Sun Lance", nameHanzi: "金陽矛", tags: ["fire_phase","hands_routing","treasure","projectile","core_formation"], description: "Fire-routed Hands + treasure lance. Heavy 20/8/24 frames (52 total), 200 qwu; projected fire-lance, 10 m range, 1 MJ strike + DoT. Counter: water-domain or wide water defense. Failure: cracked core if over-extended (rare, severe). Root gate: fire.sensitivity >= 0.6, fire.conversion >= 0.5, and a treasure with fire.affinity >= 0.5.", source: "doc 32 §3.5, doc 32 §3.6", relations: [{ type: "REQUIRES", target: "realm.core_formation" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "ENHANCES", target: "essence.fire" }, { type: "COUNTERED_BY", target: "technique.water_shield" }], simulationHooks: ["combat","physics","economy"], renderProfile: "technique_golden_sun_lance", version: "0.1.0" },
  { id: "technique.anchor_sight_strike", kind: "technique", name: "Anchor-Sight Strike", nameHanzi: "見樞擊", tags: ["senses_routing","spiritual_strike","anchor","core_formation"], description: "Senses + Hands routed spiritual strike (no phase). Heavy 20/8/24 frames (52 total), 150 qwu; bypasses physical defense and strikes the anchor directly. Counter: spirit-shielded target (Nascent Soul+). Failure: perception overload; own anchor-bruise.", source: "doc 32 §3.5", relations: [{ type: "REQUIRES", target: "realm.core_formation" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "REQUIRES", target: "skill.perceive_anchors" }], simulationHooks: ["combat","perception","deviation"], version: "0.1.0" },
  { id: "technique.core_sustained_field", kind: "technique", name: "Core-Sustained Field", nameHanzi: "丹田自養", tags: ["skin_routing","self_sustaining","ritual","core_formation"], description: "Skin-routed ritual (no phase). Ritual 60/0/30 frames (90 total), 0 qwu (self-sustaining); maintains any routing indefinitely without reservoir drain. Counter: drain local qi-environment; tribulation. Failure: field collapse if the core destabilizes.", source: "doc 32 §3.5", relations: [{ type: "REQUIRES", target: "realm.core_formation" }, { type: "REQUIRES", target: "technique.route_qi" }], simulationHooks: ["combat","cultivation","ecology"], version: "0.1.0" },
  { id: "technique.treasure_unleashed_cangwu", kind: "technique", name: "Treasure-Unleashed: Sword of Cangwu", nameHanzi: "蒼梧劍解", tags: ["metal_phase","treasure","sword","core_formation"], description: "Metal-routed Hands + treasure unleash. Heavy 20/8/24 frames (52 total), 100 qwu + treasure charge; 50 MJ cutting strike; ignores x5 AP resistance. Counter: fire-melt (x1.3) or domain-suppress. Failure: treasure damage; long refit.", source: "doc 32 §3.5", relations: [{ type: "REQUIRES", target: "realm.core_formation" }, { type: "REQUIRES", target: "technique.route_qi" }, { type: "ENHANCES", target: "essence.metal" }, { type: "COUNTERED_BY", target: "technique.burning_palm" }], simulationHooks: ["combat","physics","economy"], version: "0.1.0" },
  { id: "technique.minor_law_no_fire_here", kind: "technique", name: "Minor Law: No-Fire-Here", nameHanzi: "立法 — 禁火", tags: ["domain_edge","law_authorship","area_denial","core_formation"], description: "Domain-edge ritual (no phase). Ritual 90/0/60 frames (150 total), 500 qwu; within 100 m radius no fire-phase qi burns, law enforced by the world. Counter: Spirit Severance+ domain contest. Failure: law-backlash if contested — reservoir halved. Gate: comprehended law-fragment with domain fire-phase suppression.", source: "doc 32 §3.5, doc 32 §3.6", relations: [{ type: "REQUIRES", target: "realm.core_formation" }, { type: "REQUIRES", target: "practice.comprehension" }, { type: "COUNTERED_BY", target: "technique.domain_contest" }], simulationHooks: ["combat","politics","ritual","physics"], version: "0.1.0" },

  // -----------------------------------------------------------------------
  // Doc 13 — realm combat verbs named as techniques
  // -----------------------------------------------------------------------
  { id: "technique.possession", kind: "technique", name: "Possession", nameHanzi: "奪舍", tags: ["nascent_soul","spiritual","criminal","ritual"], description: "Nascent Soul ritual action (90+ frames). The projected spirit seizes an opponent's body, displacing the opponent's anchor. Criminal, slow, punishable by law — but possible. Failure: possession backlash (the displaced anchor's kin take revenge).", source: "doc 13 §6.6, doc 03 Station 6", relations: [{ type: "REQUIRES", target: "realm.nascent_soul" }], simulationHooks: ["combat","politics","social","ritual","history"], version: "0.1.0" },
  { id: "technique.open_domain", kind: "technique", name: "Open Domain", nameHanzi: "開域", tags: ["spirit_severance","domain","ritual","law_authorship"], description: "Spirit Severance ritual-class action (startup 60+, active 0, recovery 30+, total 90+). Opens a bounded region where the cultivator's will is partially authoritative and local laws are enforced by the world; the cost is paid at opening, not per enforcement. Failure: domain collapse.", source: "doc 13 §6.7, doc 13 §2.1, doc 03 Station 7", relations: [{ type: "REQUIRES", target: "realm.spirit_severance" }], simulationHooks: ["combat","politics","ritual","social"], version: "0.1.0" },
  { id: "technique.domain_contest", kind: "technique", name: "Domain Contest", nameHanzi: "破域", tags: ["spirit_severance","domain","law_conflict"], description: "Spirit Severance law-conflict: two cultivators contest whose law holds in the contested space via the Law-Proposed to Law-Contested to Law-Resolved state machine; the loser's domain collapses. Resolved by withdrawal, exhaustion, external adjudication, or mutual destruction. No physical state machine applies.", source: "doc 13 §6.7, doc 13 §7.5", relations: [{ type: "REQUIRES", target: "realm.spirit_severance" }, { type: "REQUIRES", target: "technique.open_domain" }, { type: "COUNTERS", target: "technique.minor_law_no_fire_here" }], simulationHooks: ["combat","politics","ritual","social"], version: "0.1.0" },

  // -----------------------------------------------------------------------
  // Doc 27 — named cultivation practices
  // -----------------------------------------------------------------------
  { id: "practice.breakthrough_rite", kind: "cultivation_practice", name: "Breakthrough Rite", tags: ["station_transition","five_stage","ritual","forced_attempt"], description: "The five-stage integration event (Preparation, Threshold, Confrontation, Integration, Settlement). Four boolean gates: phase-affinity balanced within +/-0.30, psychospiritual-resolved >= 0.7, reservoir >= 0.85 capacity with purity >= 0.7, meridians stable. forced_attempt bypasses the gate and multiplies Confrontation instability by 2.5. Threshold fails below 0.4 coherence (reverts, no damage unless forced). Confrontation: integrate (requires resolved >= 0.5 for that material), push-past (sets xinmo risk high), or abort (reservoir halved). Unstable integration: 50% seeded coin to settlement-with-xinmo or failure-with-xinmo. External interruption aborts at any stage paying the reservoir cost.", source: "doc 27 §1.2-§1.6", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }, { type: "IMPLEMENTS", target: "event.breakthrough" }, { type: "ENHANCES", target: "essence.qi" }], simulationHooks: ["cultivation","ritual","deviation","perception"], version: "0.1.0" },
  { id: "practice.comprehension", kind: "cultivation_practice", name: "Comprehension", nameHanzi: "悟道", tags: ["wudao","law_fragment","committed","attention_cost"], description: "A Committed verb producing law-fragments (domain, intensity 1-5, integration 0.0-1.0). A single attempt costs 30-60 minutes in-game and 60-100 attention units; a high-intensity fragment takes months. A fragment with integration < 0.6 is unintegrated; when unintegrated count exceeds heart-mind capacity the fifth xinmo, delusional conviction, onsets. Domains above the cultivator's station double unintegrated difficulty and halve the threshold.", source: "doc 27 §3", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }, { type: "RISKS", target: "deviation.delusional_conviction" }], simulationHooks: ["cultivation","perception","ritual","deviation"], version: "0.1.0" },
  { id: "practice.minggong", kind: "cultivation_practice", name: "Minggong", nameHanzi: "命功", tags: ["life_track","body_and_qi","dantian","balance_requirement"], description: "The life track: body cultivation, meridian opening, lower and middle dantian development. Verbs: route qi, form a meridian, integrate a practice. Develops reservoir capacity, routing speed, and physical durability; does not develop the upper dantian, heart-mind, or comprehension. Deviation risk multiplier 1 + (|minggong_level - xinggong_level| / 3); at asymmetry >= 4 the cultivator is flagged unstable with forced_attempt set true.", source: "doc 27 §6.3, doc 27 §6.5", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }, { type: "COMPLEMENTED_BY", target: "practice.xinggong" }], simulationHooks: ["cultivation","combat","deviation","aging"], version: "0.1.0" },
  { id: "practice.xinggong", kind: "cultivation_practice", name: "Xinggong", nameHanzi: "性功", tags: ["nature_track","heart_mind","comprehension","balance_requirement"], description: "The nature track: heart-mind, comprehension, xinmo integration, upper dantian self-perception. Verbs: sense self, integrate a disturbance, comprehend a fragment, confront a xinmo. Develops the upper dantian, heart-mind state vector (attention, will, emotional-balance, unresolved-attachments), comprehension skill, and integration capacity; does not develop the reservoir or body. Asymmetry against minggong raises deviation risk; >= 4 flags unstable.", source: "doc 27 §6.4, doc 27 §6.5", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }, { type: "COMPLEMENTED_BY", target: "practice.minggong" }], simulationHooks: ["cultivation","perception","deviation","social"], version: "0.1.0" },
  { id: "practice.dual_cultivation", kind: "cultivation_practice", name: "Dual Cultivation", nameHanzi: "性命雙修", tags: ["partnership","balance_not_acceleration","consent","shared_risk"], description: "The esoteric practice between consenting partners with complementary (not identical) phase-profiles; a session is hours and meaningful benefit requires regular practice over months. Produces balance, not acceleration: deviation_risk x0.7 and comprehension_rate x1.3 per partner, sustained while the practice continues and decaying over weeks. No reservoir, routing, or station gain. Costs: mutual commitment (betrayal produces xinmo in both), shared risk, and social visibility to higher-realm cultivators.", source: "doc 27 §6.6", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }, { type: "ENHANCES", target: "essence.yin" }, { type: "ENHANCES", target: "essence.yang" }, { type: "BOOSTS", target: "practice.xinggong", note: "comprehension_rate x1.3 while sustained" }], simulationHooks: ["cultivation","deviation","social","ritual"], version: "0.1.0" },
  { id: "practice.sever_attachment", kind: "cultivation_practice", name: "Sever Attachment", nameHanzi: "斬緣", tags: ["spirit_severance","emotional_bond","irreversible"], description: "The Spirit Severance verb that gives the station its name: permanently release a specific emotional bond (love, grief, fear) with real consequences. The severed piece is gone — the cultivator is different and less. Failure mode: severance regret (severing an attachment later needed).", source: "doc 03 Station 7, doc 13 §6.7", relations: [{ type: "REQUIRES", target: "realm.spirit_severance" }, { type: "COUNTERS", target: "deviation.obsession" }], simulationHooks: ["cultivation","social","deviation","perception"], version: "0.1.0" },

  // -----------------------------------------------------------------------
  // Doc 27 §7.3 — station-gated heart-mind verbs
  // -----------------------------------------------------------------------
  { id: "skill.sense_own_emotional_state", kind: "skill", name: "Sense Own Emotional State", nameHanzi: "感心", tags: ["qi_induction","heart_mind","perception"], description: "Qi Induction heart-mind verb: the cultivator can perceive their own emotional state as a qi-quality, not just feel it.", source: "doc 27 §7.3", relations: [{ type: "REQUIRES", target: "realm.qi_induction" }], simulationHooks: ["perception","cultivation","social"], version: "0.1.0" },
  { id: "skill.regulate_emotional_state", kind: "skill", name: "Regulate Emotional State", nameHanzi: "調心", tags: ["qi_condensation","heart_mind","self_regulation"], description: "Qi Condensation heart-mind verb: intentionally shift the emotional state by routing and breathing (per doc 05 §2.4).", source: "doc 27 §7.3", relations: [{ type: "REQUIRES", target: "realm.qi_condensation" }], simulationHooks: ["perception","cultivation","deviation"], version: "0.1.0" },
  { id: "skill.integrate_disturbance", kind: "skill", name: "Integrate a Disturbance", nameHanzi: "合", tags: ["foundation_establishment","heart_mind","integration"], description: "Foundation Establishment heart-mind verb: integrate a strong emotion into the heart-mind, resolving it. The verb used in breakthrough Confrontation, generalized to non-rite contexts.", source: "doc 27 §7.3", relations: [{ type: "REQUIRES", target: "realm.foundation_establishment" }], simulationHooks: ["cultivation","deviation","perception","social"], version: "0.1.0" },
  { id: "skill.perceive_others_heart_mind", kind: "skill", name: "Perceive Others' Heart-Mind States", nameHanzi: "見心", tags: ["core_formation","heart_mind","empathy_read"], description: "Core Formation heart-mind verb: perceive another being's emotional state — faintly, with consent or with attention — by attending to their qi-signature.", source: "doc 27 §7.3", relations: [{ type: "REQUIRES", target: "realm.core_formation" }], simulationHooks: ["perception","cultivation","social","politics"], version: "0.1.0" },
  { id: "skill.project_heart_mind_influence", kind: "skill", name: "Project Heart-Mind Influence", nameHanzi: "傳心", tags: ["nascent_soul","heart_mind","influence"], description: "Nascent Soul heart-mind verb: intentionally project an emotional state (calm, fear, awe) outward, affecting those around. A controlled, costly verb; its misuse is a crime.", source: "doc 27 §7.3", relations: [{ type: "REQUIRES", target: "realm.nascent_soul" }], simulationHooks: ["perception","cultivation","social","politics"], version: "0.1.0" },
];
