/**
 * Xianxia Concept Review — multiverse-sanity audit of every Genesis concept.
 *
 * For each concept: its causal FUNCTION in the xianxia multiverse, its
 * INTERACTIONS (what can affect it, what it affects), and its diegetic
 * VISUALS (how the player/observer reads it in-world — the "make the world
 * readable" rule). Naming follows universal xianxia English terms; engine
 * internals are marked non-diegetic so nobody mistakes them for canon.
 *
 * Machine-audited: every concept id must exist in the registry, every review
 * must have non-trivial function/interactions/visuals, and concept NAMES
 * must not contain CJK/pinyin remnants.
 */

export interface XianxiaConceptReview {
  conceptId: string;
  function: string;
  interactions: string;
  visuals: string;
  nameNote?: string;
}

export const XIANXIA_CONCEPT_REVIEWS: XianxiaConceptReview[] = [
  // ---- foundations (engine-level, non-diegetic) ---------------------------
  { conceptId: 'canon.determinism', function: 'Seed-reproducible simulation contract; same inputs always produce the same world state.', interactions: 'Governs every simulation core; violated by wall-clock time, Math.random, or unordered iteration.', visuals: 'Non-diegetic. Surfaces only in replay/repro tools.', nameNote: 'Engine invariant, not canon lore.' },
  { conceptId: 'canon.realm-ladder', function: 'The ten-station progression from Mortal to Mahayana that every cultivator climbs; each station adds perceptions, verbs, and failure modes.', interactions: 'Gates techniques, lifespan, perception, social rank, and law authority; stations cannot be skipped.', visuals: 'Station rank reads in auras, robe hues, pressure in the air; breakthroughs read as gathering light and local qi disturbance.' },
  { conceptId: 'canon.qi-capacity-doubling', function: 'Each station doubles the cultivator\'s internal qi capacity (multiplier exactly 2.0).', interactions: 'Bounds technique cost budgets, combat stamina, and depletion risk at each station.', visuals: 'Non-diegetic; implied by how long a cultivator can sustain technique output.' },
  { conceptId: 'canon.visual-truth-packets', function: 'Every visual concept carries an exhaustive physical/visual spec the generators and Oracle must satisfy.', interactions: 'Consumed by generation, style grammars, and the accuracy Oracle.', visuals: 'Non-diegetic; the spec behind every rendered asset.' },
  { conceptId: 'canon.oracle-authority', function: 'The Visual Accuracy Oracle can reject any asset; the Grand Architect cannot override a rejection.', interactions: 'Final gate between candidate and validated status for all generated work.', visuals: 'Non-diegetic; surfaces in the validation pipeline and review boards.' },
  { conceptId: 'canon.truth-levels', function: 'Exactly five truth levels (canonical, derived, art, procedural, unresolved) classify every claim.', interactions: 'Determines whether a claim may be changed and how it may be used downstream.', visuals: 'Non-diegetic; tag on every spec and definition.' },
  { conceptId: 'canon.supernatural-exceptions', function: 'Every supernatural event must declare the ordinary rule it overrides plus power, limits, cues, failure, and system interactions.', interactions: 'Binds every cultivation technique, artifact, and phenomenon to explicit laws; prevents unbounded fantasy.', visuals: 'Diegetic cues per exception: visible technique signature, failure behavior, limits the viewer can perceive.' },
  { conceptId: 'canon.si-units', function: 'All simulation uses SI units (meters, seconds, kilograms, radians, kelvin).', interactions: 'Underpins physics, economy, and measurement consistency across worlds.', visuals: 'Non-diegetic; UI may render culturally appropriate units.' },
  { conceptId: 'canon.generation-pipeline', function: 'The 13-stage deterministic pipeline from world truth to generated instances.', interactions: 'Every generator stage consumes canon and grammars and feeds the next stage.', visuals: 'Non-diegetic.' },
  { conceptId: 'canon.golden-scenes', function: 'Authored visual moments the engine must be able to produce; art-direction targets, not gameplay scripts.', interactions: 'Sets the bar for scene composition and validation.', visuals: 'The benchmark images themselves — canonical frames for lighting, layout, mood.' },

  // ---- cultivation --------------------------------------------------------
  { conceptId: 'canon.power-scaling', function: 'Exponential power growth (2x qi per realm); combat power and world impact scale nonlinearly with station.', interactions: 'Drives combat math, technique packets, and what a cultivator can physically do to the world.', visuals: 'Higher stations read as effortless motion, denser qi glow, and larger-scale world responses (clefts, shockwaves).' },
  { conceptId: 'canon.realm-perceptions', function: 'Each station grants new perceptions the cultivator could not access before.', interactions: 'Unlocks sensory verbs; gates what can be sensed, scanned, and tracked.', visuals: 'Perception upgrades read as expanded auric/qi-veil visibility; new layers of the world become faintly visible.' },
  { conceptId: 'canon.trace-anchoring', function: 'Cultivators can leave qi-traces (markers, warnings) that others with sufficient perception can later read.', interactions: 'Persists in the world; readable by the writer and others; carries intent.', visuals: 'Faint luminous glyph or mark at the anchored location, decaying over time; readable only through qi sense.' },
  { conceptId: 'canon.heart-demons', function: 'Unresolved strong emotions (grief, fear, desire, hatred) persist, deepen, and begin to color perception.', interactions: 'Stains qi-state, biases decisions, threatens deviation and madness; counterplayed by cultivation practices.', visuals: 'In-world: the cultivator\'s aura reads wrong; shadow-like presence in their qi; disturbed countenance.' },
  { conceptId: 'canon.root-gated-techniques', function: 'Some techniques require a minimum spiritual-root profile in the matching phase to practice at all.', interactions: 'Unreadable manuals, unusable techniques below the gate; hard class boundaries between cultivators.', visuals: 'Manuals physically resist weak cultivators; attempts fizzle with visible phase-colored failure.' },
  { conceptId: 'canon.domain-sovereignty', function: 'Spirit Severance lets a cultivator\'s will become law inside a bounded domain.', interactions: 'Domain law overrides local law inside the radius; everything inside obeys the domain holder\'s rules.', visuals: 'The domain reads as a subtly wrong, law-tinted space — light bends to its rules, physics visibly defer.' },
  { conceptId: 'canon.combat-domain', function: 'During combat, a cultivator may open a bounded region where their will is partially authoritative.', interactions: 'Modifies capability vectors, technique behavior, and environment response inside the region.', visuals: 'A faint spatial boundary shimmers at the domain edge; effects inside obey the holder\'s intent.' },
  { conceptId: 'canon.phase-combat', function: 'Five-phase (wood/fire/earth/metal/water) matchup resolves technique interplay; water counters fire, and so on.', interactions: 'Determines technique effectiveness, counters, and elemental consequence in every exchange.', visuals: 'Technique colors and particle languages follow phase: fire glows red-hot, water flows cyan, metal glints white.' },
  { conceptId: 'canon.divine-sense', function: 'The spiritual perception ability (the corpus\'s Residual Error Sense family): perceive qi-residue of events, detect wrongness, scan the environment.', interactions: 'Feeds NPC knowledge, detection, tracking, and investigation; range limited by terrain and suppression.', visuals: 'Blue-tinted X-ray overlay of the world (per UI board): spirit veins, ores, herb clusters, residue gradients, dead nodes.' },
  { conceptId: 'canon.qi-sense', function: 'The basic perception of ambient qi as a flowing presence: rivers read cool/yin/water, noon sun hot/yang/fire.', interactions: 'Station-gated; requires attention and is exhausting; foundation of all higher perception.', visuals: 'Faint flowing luminous currents in the air when actively sensed; color follows phase.' },
  { conceptId: 'canon.divination', function: 'Perception of qi-residue patterns at temporal scale — reading current momentum of the qi-topography, not the future.', interactions: 'Shapes NPC belief and rumor; skilled diviners misread as prophecy; feeds the knowledge layer.', visuals: 'Hexagram casts, compass-like readings, shimmering residue trails flowing toward outcomes.' },
  { conceptId: 'canon.soul-anchor', function: 'The primordial spirit (yuan-ying) — the self-perceiving spirit that can act without the body, project, possess, and survive death if a refuge is prepared.', interactions: 'Death is not final above Core Formation; soul damage, possession, and anchor-harvesting become possible.', visuals: 'The spirit reads as a condensed humanoid light-form; projection leaves the body still and dim.' },
  { conceptId: 'canon.heavenly-dao', function: 'The Dao — the totality of lawful pattern the cosmos runs on, distinct from the Nameless Origin.', interactions: 'Karma is the causal expression of the Dao; comprehension of Dao gates law authorship at Mahayana.', visuals: 'Dao comprehension reads as moments where the world\'s pattern becomes visible — flowing law-lines, resonant stillness.' },
  { conceptId: 'canon.underworld', function: 'The realm of the dead under the Courts of Heaven\'s jurisdiction — judgment and the fate of souls.', interactions: 'Receives the dead; sub-jurisdiction of the courts; anchors retrieve the dead from bardo.', visuals: 'A dim, still, misty domain; pale lantern-light; souls as drifting motes awaiting judgment.' },

  // ---- combat & ecology ---------------------------------------------------
  { conceptId: 'canon.spirit-veins', function: 'Underground channels of condensed ambient qi — the qi-topology skeleton of every world.', interactions: 'Raises cultivation potential, feeds formations, gates sects; damage depletes local qi ecology.', visuals: 'Luminous blue-green currents under the terrain; denser near nodes and springs; visible only to qi sense (per UI board: Spirit Vein scan).' },
  { conceptId: 'canon.spirit-beasts', function: 'Animals with cultivator-parallel realm tiers; they climb the same ten-station ladder with species variations.', interactions: 'Predator/prey, harvest targets, companions, regional threats; realm tier decides threat level.', visuals: 'Beasts read their tier in size, aura, and distinct elemental traits; high-tier beasts glow with condensed qi.' },
  { conceptId: 'canon.cangwu-roster', function: 'The named Cangwu ecology: every beast is a node with inputs, outputs, predators, death schedule; every herb a producer with growth cycle, harvest consequence, market.', interactions: 'Feeds ecology simulation, harvest economy, and faction supply chains.', visuals: 'Herb patches read seasonally (growth stages), beasts leave tracks and territory signs.' },
  { conceptId: 'canon.demography-aggregation', function: 'S4 individuals aggregate into S2 populations preserving counts, qi-magnitude moments, and named identities.', interactions: 'Distant simulation stays truthful: three families that left are really gone when you visit.', visuals: 'Non-diegetic; guarantees history matches experience.' },

  // ---- economy ------------------------------------------------------------
  { conceptId: 'canon.spirit-stone-economy', function: 'Spirit stones are crystallized qi concentrate — the currency of cultivation commerce.', interactions: 'Pays for pills, talismans, formations, sect dues, mercenary contracts; produced by veins or Core Formation+ cultivators.', visuals: 'Small translucent stones with inner light; quality reads in clarity and glow intensity.' },
  { conceptId: 'canon.qi-authority', function: 'The cosmic reserve currency — measurable qi-density in anchors and court reservoirs; finite and non-regenerating.', interactions: 'Every cosmic transaction consumes it; the Thinning is its decline; conservation is the cosmic economy\'s central practice.', visuals: 'Reads at cosmic scale: dimming heavens, thinning law-lines, reservoirs visibly draining.' },

  // ---- society ------------------------------------------------------------
  { conceptId: 'canon.sect-hierarchy', function: 'Strict sect order: patriarch to elders to inner disciples to outer disciples to servants; each sect holds exactly one spirit vein or grotto-heaven.', interactions: 'Gates teachings, access, authority, and vestments; sect competition centers on the single vein.', visuals: 'Ranked vestment colors and trims per style grammar; inner disciples carry better quality gear.' },
  { conceptId: 'canon.ancestral-lineages', function: 'Lineages with explicit progenitor-to-present chains; ancestral courts follow their realm\'s style grammars.', interactions: 'Inheritance, claims, grudges, and obligations flow along the chains.', visuals: 'Ancestral halls with portrait/tablet rows; lineage names carved into founding stones.' },
  { conceptId: 'canon.courts-of-heaven', function: 'The celestial bureaucracy: named geography, personnel, factions, history, and a named political crisis.', interactions: 'Jurisdiction over heavens and the Underworld; politics ripple into mortal faith and sects.', visuals: 'A sky-bureaucracy of pavilions and seals; officials in ranked celestial robes; judgment halls.' },

  // ---- cosmology ----------------------------------------------------------
  { conceptId: 'canon.strata-geometry', function: 'Three coextensive strata (Mortal, Acquired, Precelestial) — same horizontal coordinates, distinct altitude and law.', interactions: 'Grotto anchors connect strata vertically; tribulation ascends through the boundary.', visuals: 'Vertical qi-density gradient; horizon bands where strata thin; ascension lights along the boundary.' },
  { conceptId: 'canon.grotto-anchors', function: 'A grotto-heaven in the Acquired Stratum anchors to a geographic point in the Mortal Stratum at the same coordinate.', interactions: 'Pocket domains with own geography, time rate, law; entry via the anchor point.', visuals: 'The anchor reads as a resonant spot on the mortal world; entry glows and folds space.' },
  { conceptId: 'canon.grotto-heaven-time', function: 'Grotto-heavens may run faster or slower than the mortal rate (1:10 to 10:1).', interactions: 'Training time, aging, formation maintenance all follow local time; never as extreme as the Precelestial\'s 1:365.', visuals: 'Time bleed at boundaries; seasons visibly race inside fast grottoes.' },
  { conceptId: 'canon.precelestial', function: 'The uppermost stratum — older, slower, denser, less lawful; the workshop where the Acquired laws were inscribed.', interactions: 'Law authorship happens here; entering it is entering the workshop, not the showroom.', visuals: 'Denser, slower-moving light; law-lines still unwritten; majestic unfinished geometry.' },
  { conceptId: 'canon.world-law-pressure', function: 'Law pressure varies by world and realm — the same action (cut, fly, teleport) behaves differently under different law fields.', interactions: 'Modifies capability vectors, technique dissipation, movement suppression, destruction scale.', visuals: 'Pressure reads in how the world resists techniques: shallow scars, absorbed blasts, suppressed flight.' },
  { conceptId: 'canon.higher-worlds', function: 'The immortal worlds beyond Mahayana, built on the ran substrate.', interactions: 'The endgame horizon; higher laws, higher stakes, sequel-hook setting.', visuals: 'Substrate light instead of qi; law visibly denser; worlds as vast architectures of law.' },

  // ---- formations & matter ------------------------------------------------
  { conceptId: 'canon.formation-barriers', function: 'Formation shields protect those within from physical or qi attack.', interactions: 'Absorb impacts, drain node energy, resist brute force; energy supply and nodes become attack surface.', visuals: 'Barrier as rippling translucent field; flickering nodes, dimming spirit stones, spreading ripples as it fails.' },
  { conceptId: 'canon.formation-topology', function: 'Formations are geometric qi-circuits with explicit node/edge topology; talismans are single-use qi-storage; alchemy follows recipe-constraint.', interactions: 'Formation strength depends on node quality, qi-climate, and precision; nodes are damageable, fuelable, drainable.', visuals: 'Geometric glowing circuits on ground/air; nodes as bright focal points; talismans as paper-thin glowing slips.' },
  { conceptId: 'canon.storage-treasures', function: 'Storage talismans and rings hold items in folded space; rings are Core Formation artifacts.', interactions: 'Inventory capacity, looting loops, smuggling; target for theft.', visuals: 'Items shimmer and collapse into the talisman/ring on storage; release reads as unfolding light.' },
  { conceptId: 'canon.matter-conservation', function: 'Destroyed matter is conserved: debris → collectible matter → storage → crafting → new capability.', interactions: 'Closes the destruction loop; economy consumes the same physical resources the player touches.', visuals: 'Destruction yields physical debris and loot orbs; removed terrain leaves readable cavities.' },

  // ---- motion & physics ---------------------------------------------------
  { conceptId: 'canon.motion-synchronization', function: 'Every moving entity, technique, and phenomenon is specified with synchronized timing across animation, VFX, audio, hitbox, terrain.', interactions: 'Technique timing is simulation-owned; all presentation layers share one clock.', visuals: 'Non-diegetic; manifests as the 5-layer synchronized presentation.' },
  { conceptId: 'canon.physics-determinism', function: 'Physics runs on a deterministic core (Jolt + determinism wrapper).', interactions: 'Physics outcomes replay identically; AI control sits on top.', visuals: 'Non-diegetic.' },
  { conceptId: 'canon.fidelity-tiers', function: 'Five simulation tiers S0-S4 govern how much of an entity is simulated based on relevance.', interactions: 'Distant = aggregate truth; nearby = full physics/animation; transitions never change history.', visuals: 'Non-diegetic; determines whether you see embodied NPCs or only hear reports of them.' },

  // ---- derived / directives -----------------------------------------------
  { conceptId: 'derived.settlement-daily-life', function: 'Named villagers wake, work, eat, rest, and sleep on a deterministic daily schedule.', interactions: 'Schedules, locations, reactions all tick per frame; village feels alive when visited.', visuals: 'Morning smoke, market bustle at noon, empty streets at night; schedules readable by watching.' },
  { conceptId: 'derived.universal-interaction-lattice', function: 'Every meaningful thing exposes state, affordances, resistances, relationships, consequences, and history.', interactions: 'Anything can be acted upon through shared world rules; no bespoke quest wiring.', visuals: 'Readable affordances: cracks before collapse, dimming before failure, tracks before presence.' },
  { conceptId: 'derived.causal-event-fabric', function: 'Events propagate to independent systems via a shared fabric instead of direct system-to-system wiring.', interactions: 'One action fans out: recovery, structure, nav, hydrology, ecology, ownership, knowledge, factions, economy, history, narrative.', visuals: 'Consequences are observable: water entering excavations, routes rebuilt, prices shifting, rumors spreading.' },
  { conceptId: 'derived.obstacle-attack-axes', function: 'Obstacles expose several independent attack axes (brute force, excavate, nodes, energy, owner, token, social, timing, backdoor).', interactions: 'The systems, not authored quests, generate the solution space.', visuals: 'Each axis reads: formation nodes visible, energy lines traceable, owners identifiable, terrain excavatable.' },
  { conceptId: 'derived.wiki-definition-database', function: 'The authored canon content database: 278 definitions across 22 layers the Architect and generators query.', interactions: 'Feeds lore retrieval, generation constraints, and the Genesis gate.', visuals: 'Non-diegetic; the wiki layer behind every query.' },
  { conceptId: 'derived.modular-asset-factory', function: 'The asset production doctrine: readable silhouettes, modular kits, hide-masks, texture budgets, streaming LOD/HLOD.', interactions: 'Governs character/terrain/structure factories and their naming conventions.', visuals: 'The factory outputs: clean silhouettes, phase-colored materials, terrain with qi-affinity families.' },
  { conceptId: 'derived.directed-scene-production', function: 'The directed-production pipeline: canonical scale registry, handcrafted set blueprint, donghua shot script, deep world hierarchy.', interactions: 'Dimensions every structure/room/prop against canonical scale; directs camera cuts, lighting, audio, art-board references; feeds the studio hierarchy.', visuals: 'The result is the "lush, beautiful, cinematic" frame: correct 1.8 m-to-5,000 m relativity, painterly materials, directed camera language.' },
  { conceptId: 'canon.mortal-realm', function: 'The Mortal Realm is a complete lower-order cosmos: ordinary civilization and cultivation civilization coexist in overlapping geographies.', interactions: 'Sects, clans, loose cultivators, beasts, formations, and mortal states occupy the same planet; separation is a local historical outcome, not a rule.', visuals: 'A hidden sect reads as persistent mist to mortals, as an outer ward to a disciple, as a spatially folded mountain to an elder — same coordinates, different access.' },
  { conceptId: 'derived.gameplay-clock', function: 'One authoritative 60 Hz gameplay clock; the render clock interpolates poses at display rate; animation events split into authoritative vs presentation.', interactions: 'Hit registration, qi cost, terrain changes, and action phases bind to fixed ticks; cloth, particles, and camera interpolate freely.', visuals: 'Non-diegetic; manifests as identical hit timing on 60 Hz and 144 Hz displays.' },
  { conceptId: 'derived.planetary-cultivation-ecology', function: 'The planet is a set of interacting continuous fields (qi, beast pressure, mortal density, jurisdiction, concealment) rather than mortal/cultivator zones.', interactions: 'CultivationEcologyCell drives where sects emerge, where populations grow, where wilderness lies; beast territories can redirect roads and villages.', visuals: 'From orbit the planet is patchy: mortal heartlands, mixed influence, spirit wilderness, sect domains, forbidden zones interleaved.' },
  { conceptId: 'derived.xianxia-terminology', function: 'The database speaks universally understood xianxia: Qi Condensation, Foundation Establishment, Core Formation, Nascent Soul, Soul Formation, Soul Transformation, Tribulation, Mahayana, Immortal — with hanzi.', interactions: 'Every realm definition carries standard aliases; the glossary maps universal terms to corpus ids and is machine-audited.', visuals: 'Non-diegetic; it is the vocabulary every xianxia reader recognizes — the world reads as real cultivation fiction, not a cheap copy.' },
  { conceptId: 'derived.scene-universe-slice', function: 'Every scene compiles a Scene Universe Slice: only the relevant part of the enormous universe graph, in 16 named sections (cosmology, world law, regional, history, architecture, formation, ecology, materials, NPC/history, cultivation, economy, motion, audio, gameplay, persistence, validation).', interactions: 'The slice is deterministic per location; it feeds scene generation, motion harvest, audio layering, and gameplay affordances without loading the full universe.', visuals: 'A cave shot knows its history (excavated 312 years ago), its formation state (failed 22 years ago), its ecology (moss, bats), and its sounds (drip, reverberation) — nothing relevant omitted.' },
  { conceptId: 'derived.perceptual-evidence-examiner', function: 'The Perceptual Evidence Examiner is the forensic vision sensor: blind player read first, then full-frame, multi-scale density, materials, architecture, ecology, animation, lighting, shadows, game-readability and technical-defect inspection of every rendered frame.', interactions: 'Genesis passes tell it what must be true (per-pass obligation manifests); it reports what the pixels actually show with PASS/PARTIAL/FAIL/NOT_EVALUABLE, defect severities, edit-scope diagnosis, and a channel-split verdict.', visuals: 'It never upgrades a primitive proxy because code claims more exists — the player read is brutally accurate, and the AAA-completeness question finds where the frame stops rewarding closer inspection.' },
  { conceptId: 'derived.substance-preservation', function: 'The performance constitution: optimization may reduce the cost of representing the universe, never the universe itself.', interactions: 'Every optimization PR reports PERFORMANCE DELTA + SEMANTIC DELTA (all-zero required); the escalation ladder orders engineering before fidelity changes; NPCs walk the S4->S0 fidelity ladder instead of being deleted.', visuals: 'A distant mountain shows HLOD canopy clusters and landmark silhouettes; fly there and the 280,000-tree forest, caves, spirit vein, and abode materialize from deterministic truth — nothing invented by approach, nothing lost by distance.' },
];

const REVIEW_BY_ID = new Map(XIANXIA_CONCEPT_REVIEWS.map((r) => [r.conceptId, r]));
export function getReview(conceptId: string): XianxiaConceptReview | undefined {
  return REVIEW_BY_ID.get(conceptId);
}
