#!/usr/bin/env node
/**
 * generate-build-manifest.ts
 *
 * Runs BEFORE `next build` to produce an immutable build provenance manifest.
 * The manifest is written to src/generated/build-manifest.ts and committed
 * by the build process (not by the developer).
 *
 * This addresses the audit finding that runtime git commands don't prove
 * which artifact produced the loaded JavaScript — they only show what's
 * underneath the running server right now.
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createHash } from 'crypto';

function tryGit(command: string): string | null {
  try {
    return execSync(command, {
      cwd: process.cwd(),
      encoding: 'utf-8',
      timeout: 5000,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
  } catch {
    return null;
  }
}

function getPackageVersion(): string {
  try {
    const pkg = JSON.parse(readFileSync(join(process.cwd(), 'package.json'), 'utf-8'));
    return pkg.version ?? 'unknown';
  } catch {
    return 'unknown';
  }
}

function getSourceTreeHash(): string | null {
  // Hash the current source state: commit SHA + any uncommitted changes.
  // This lets the client detect "workspace changed after build" by
  // comparing the build-time hash to a runtime hash.
  const commit = tryGit('git rev-parse HEAD');
  const diff = tryGit('git diff HEAD') ?? '';
  if (!commit) return null;
  const h = createHash('sha256');
  h.update(commit);
  h.update(diff);
  return h.digest('hex').slice(0, 16);
}

const commitSha = tryGit('git rev-parse HEAD');
const branch = tryGit('git rev-parse --abbrev-ref HEAD');
const status = tryGit('git status --porcelain');
const dirty = status !== null && status.length > 0;

const manifest = {
  commitSha,
  commitShort: commitSha ? commitSha.slice(0, 12) : null,
  branch,
  dirty,
  buildTimestamp: new Date().toISOString(),
  packageVersion: getPackageVersion(),
  sourceTreeHash: getSourceTreeHash(),
  buildId: crypto.randomUUID(),
};

const content = `/**
 * Build provenance manifest.
 *
 * AUTO-GENERATED by scripts/generate-build-manifest.ts — DO NOT EDIT.
 * Regenerated before every \`next build\`.
 *
 * The runtime /api/build-info route reads this file and returns it
 * immutably. It does NOT shell out to git at request time.
 */

export interface BuildManifest {
  commitSha: string | null;
  commitShort: string | null;
  branch: string | null;
  dirty: boolean;
  buildTimestamp: string;
  packageVersion: string;
  sourceTreeHash: string | null;
  buildId: string;
}

export const BUILD_MANIFEST: BuildManifest = ${JSON.stringify(manifest, null, 2)};
`;

const outPath = join(process.cwd(), 'src', 'generated', 'build-manifest.ts');
writeFileSync(outPath, content, 'utf-8');
console.log(`[build-manifest] wrote ${outPath}`);
console.log(`[build-manifest] commit=${manifest.commitShort} branch=${manifest.branch} dirty=${manifest.dirty}`);
